.gitmodules
BUILD
WORKSPACE
core/java/com/google/census/Census.java
core/java/com/google/census/CensusContext.java
core/java/com/google/census/CensusContextFactory.java
core/javatests/com/google/census/CensusContextFactoryTest.java
core/javatests/com/google/census/CensusContextTest.java
core_native/java/com/google/census/CensusContextFactoryImpl.java
core_native/java/com/google/census/CensusContextImpl.java
core_native/java/com/google/census/CensusSerializer.java

This PR adds census-proto as a git submodule and then uses it for the `CensusContext` serialization format.

Serializes CensusContextImpl as a Protocol Buffer.

---

.travis.yml
core/java/com/google/census/Census.java
core/java/com/google/census/CensusContext.java
core/java/com/google/census/CensusContextFactory.java
core/java/com/google/census/Metric.java
core/java/com/google/census/MetricMap.java
core/java/com/google/census/MetricName.java
core/java/com/google/census/StringUtil.java
core/java/com/google/census/TagKey.java
core/java/com/google/census/TagValue.java
core/pom.xml
core_native/java/com/google/census/CensusContextFactoryImpl.java
core_native/java/com/google/census/CensusContextImpl.java
core_native/java/com/google/census/CensusCurrentContext.java
core_native/java/com/google/census/CensusSerializer.java
core_native/pom.xml

This PR also fixes the existing style violations.

Runs Maven Checkstyle plugin to enforce Google style.

---

core/pom.xml
core_impl/pom.xml
pom.xml

Maven build file fixes

---

core/src/main/java/com/google/instrumentation/common/Provider.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/common/ProviderTest.java

We want to share the same logic between stats and trace.
Add more tests for the loading code.

Move the loading with reflection logic from the Tracer to Provider.

---

core/src/main/java/com/google/instrumentation/trace/BlankSpan.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/trace/BlankSpanTest.java
core/src/test/java/com/google/instrumentation/trace/StartSpanOptionsTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java
core_context_impl/src/test/java/com/google/instrumentation/trace/ContextSpanHandlerImplTest.java

Use directly INSTANCE instead of getInstance for BlankSpan. 

---

BUILD
core/src/main/java/com/google/instrumentation/trace/BlankSpan.java
core/src/main/java/com/google/instrumentation/trace/EndSpanOptions.java
core/src/main/java/com/google/instrumentation/trace/Sampler.java
core/src/main/java/com/google/instrumentation/trace/Samplers.java
core/src/main/java/com/google/instrumentation/trace/ScopedSpanHandle.java
core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/main/java/com/google/instrumentation/trace/SpanContext.java
core/src/main/java/com/google/instrumentation/trace/SpanId.java
core/src/main/java/com/google/instrumentation/trace/TraceId.java
core/src/test/java/com/google/instrumentation/trace/BlankSpanTest.java
core/src/test/java/com/google/instrumentation/trace/EndSpanOptionsTest.java
core/src/test/java/com/google/instrumentation/trace/SamplersTest.java
core/src/test/java/com/google/instrumentation/trace/ScopedSpanHandleTest.java
core/src/test/java/com/google/instrumentation/trace/SpanContextTest.java
core/src/test/java/com/google/instrumentation/trace/SpanIdTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java
core/src/test/java/com/google/instrumentation/trace/TraceIdTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java

Use directly the static final variable for INVALID and DEFAULT.
Add SpanId class.

Cleanup trace API

---

.bazelrc
.travis.yml

Enable all Error Prone warnings in Travis Bazel build.

---

BUILD
core/src/main/java/com/google/instrumentation/trace/SpanId.java
core/src/main/java/com/google/instrumentation/trace/TraceId.java
core/src/test/java/com/google/instrumentation/trace/BlankSpanTest.java
core/src/test/java/com/google/instrumentation/trace/SamplersTest.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/SpanContextTest.java
core/src/test/java/com/google/instrumentation/trace/SpanIdTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java
core/src/test/java/com/google/instrumentation/trace/TraceIdTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java

Refactor these classes to use a factory method.

Change TraceId and SpanId to use byte[].

---

.travis.yml
BUILD
benchmarks/README.md
benchmarks/build.gradle
benchmarks/src/jmh/java/com/google/instrumentation/trace/HttpPropagationUtilBenchmark.java
build.gradle
core/build.gradle
core_impl/build.gradle
examples/build.gradle
examples/src/main/java/com/google/instrumentation/stats/StatsRunner.java
examples/src/main/java/com/google/instrumentation/trace/BasicContextTracing.java
examples/src/main/java/com/google/instrumentation/trace/BasicScopedTracing.java
examples/src/main/java/com/google/instrumentation/trace/BasicTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansContextTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansScopedTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansTracing.java
settings.gradle

Add instructions on how to run the benchmarks.
Enable checkstyle and all the warnings all the time when build with gradle.

Add gradle build support for benchmarks and examples.

---

.travis.yml
check-git-history.py

The script runs on Travis and only checks the commit history when the commit is
from a pull request. It fails the build if the pull request contains merge
commits ~~or does not start from the branch that it is being merged into~~. If there
is an unexpected exception, the script does not fail the build.

Checks the commit history of pull requests in CI.

---

core/src/main/java/com/google/instrumentation/trace/Annotation.java
core/src/main/java/com/google/instrumentation/trace/Link.java
core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/test/java/com/google/instrumentation/trace/AnnotationTest.java
core/src/test/java/com/google/instrumentation/trace/LinkTest.java
core_impl/src/main/java/com/google/instrumentation/trace/SpanData.java
core_impl/src/main/java/com/google/instrumentation/trace/TimedEvent.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanDataTest.java
core_impl/src/test/java/com/google/instrumentation/trace/TimedEventTest.java

Add toString methods for Annotation and Link.
The SpanData class si the main class that will expose Span's data outside the internal library.

Add SpanData and TimedEvent classes.

---

CONTRIBUTING.md
build.gradle
core/build.gradle
core/src/main/java/com/google/instrumentation/stats/MeasurementDescriptor.java
core/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorTest.java

This PR applies AutoValue to `MeasurementDescriptor` and `MeasurementUnit` and adds some tests.

Starts using AutoValue for classes in stats-core.

---

core_impl/build.gradle
core_impl/src/main/java/com/google/instrumentation/trace/TraceParams.java
core_impl/src/test/java/com/google/instrumentation/trace/TraceParamsTest.java

This is a global configuration/parameters class that can control default values for the tracing library.

Add a TraceParams class.

---

core/src/main/java/com/google/instrumentation/common/Timestamp.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanDataTest.java

Fix style issues in order to import these changes to our internal repo.

Fix a few style issues.

---

appveyor.yml

There is just one build job for now.
See #153.

Add simple configuration file for AppVeyor.

---

benchmarks/src/jmh/java/com/google/instrumentation/trace/PropagationUtilBenchmark.java
core/src/main/java/com/google/instrumentation/trace/PropagationUtil.java
core/src/main/java/com/google/instrumentation/trace/SpanId.java
core/src/main/java/com/google/instrumentation/trace/TraceId.java
core/src/main/java/com/google/instrumentation/trace/TraceOptions.java
core/src/test/java/com/google/instrumentation/trace/PropagationUtilTest.java
core/src/test/java/com/google/instrumentation/trace/TraceOptionsTest.java

Change the PropagationUtil to use the new binary encoding.
Change the TraceOptions to be 1B instead of 4B.
Remove the HTTP encoding for the moment until we define the common encoding between projects.

Update to use the new proposed encoding.

---

core/src/main/java/com/google/instrumentation/stats/BucketBoundaries.java
core/src/main/java/com/google/instrumentation/stats/Distribution.java
core/src/main/java/com/google/instrumentation/stats/DistributionAggregation.java
core/src/main/java/com/google/instrumentation/stats/DistributionAggregationDescriptor.java
core/src/test/java/com/google/instrumentation/stats/BucketBoundariesTest.java
core/src/test/java/com/google/instrumentation/stats/DistributionTest.java

Merged code changes from @a-veitch 's PR  #196, made some modifications and addressed most of the review comments from @sebright. Also added a new BucketBoundaries class for storing the histogram bucket boundaries.

Address comments for Distribution class

---

benchmarks/src/jmh/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplBenchmark.java
core/src/main/java/com/google/instrumentation/trace/BinaryPropagationHandler.java
core/src/test/java/com/google/instrumentation/trace/BinaryPropagationHandlerTest.java

This is a preparation for the https://github.com/google/instrumentation-java/pull/201

Move PropagationUtil to BinaryPropagationHandler.

---

benchmarks/build.gradle
benchmarks/src/jmh/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplBenchmark.java
core/src/main/java/com/google/instrumentation/trace/BinaryPropagationHandler.java
core/src/test/java/com/google/instrumentation/trace/BinaryPropagationHandlerTest.java
core_impl/src/main/java/com/google/instrumentation/trace/BinaryPropagationHandlerImpl.java
core_impl/src/test/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplTest.java

This is a preparation for https://github.com/google/instrumentation-java/pull/201

BinaryPropagationHandler split between interface and implementation.

---

build.gradle
core/build.gradle

This adds only the gradle support for pushing binaries to maven central. A followup PR will add instructions.

Add initial gradle support to push to maven central.

---

build.gradle
settings.gradle

Related issue: https://github.com/google/instrumentation-java/issues/214

Remove proto directory.

---

core/src/main/java/com/google/instrumentation/stats/Stats.java

Please note Provider.newInstance() is Nullable.

Fix NullPointerException for Stats.getStatsContextFactory()

---

build.gradle
core/src/main/java/com/google/instrumentation/stats/Distribution.java
core/src/main/java/com/google/instrumentation/stats/MutableDistribution.java
core/src/test/java/com/google/instrumentation/stats/DistributionTest.java
core/src/test/java/com/google/instrumentation/stats/MutableDistributionTest.java
findbugs-exclude.xml

Distribution is an immutable AutoValue class, and MutableDistribution is a
mutable version of Distribution.  We can use MutableDistribution to store stats
as they are recorded and then copy them into a Distribution before returning
them in a View.  We can also use Distribution to store the distribution data in
DistributionAggregation.
I copied/renamed files in separate commits to try to make the diffs smaller.
/cc @a-veitch @dinooliva

Split Distribution into mutable and immutable classes.

---

core/src/main/java/com/google/instrumentation/stats/MutableView.java
core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImpl.java
core_impl/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMapTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java

Use MutableView to record stats in distribution, and convert MutableView to View when getView() is called.
This is a skeleton of MutableView, it has not fully been implemented yet, since some of the implementation needs to depend on changes on DistributionAggregation: https://github.com/google/instrumentation-java/pull/233

Add MutableView, modify mapping and implement process.

---

core_impl/src/test/java/com/google/instrumentation/stats/StatsContextTest.java

Temporarily disable flaky test.

---

core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/MutableView.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImpl.java
core_impl/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMapTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java

Finish implementation on MutableView, add several tests for record().

---

benchmarks/src/jmh/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplBenchmark.java
core/src/main/java/com/google/instrumentation/trace/SpanContext.java
core/src/main/java/com/google/instrumentation/trace/SpanFactory.java
core/src/main/java/com/google/instrumentation/trace/StartSpanOptions.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/trace/LinkTest.java
core/src/test/java/com/google/instrumentation/trace/SamplersTest.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/SpanContextTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java
core/src/test/java/com/google/instrumentation/trace/TracingTest.java
core_impl/src/main/java/com/google/instrumentation/trace/BinaryPropagationHandlerImpl.java
core_impl/src/test/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplTest.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanDataTest.java

We have to allow testing and implementation.
Also add a public SpanContext.create.

Change visibility for SpanFactory and StartSpanOptions

---

core/build.gradle
core_impl/build.gradle

Cherry-pick commit 81819f2

---

.travis.yml

This information could be useful if
https://github.com/travis-ci/travis-ci/issues/5882 is still an issue.

Run "git log" in .travis.yml.

---

.travis.yml

Fix the issue https://github.com/google/instrumentation-java/issues/153

Update travis to build on osx as well.

---

core_impl/src/test/java/com/google/instrumentation/stats/StatsContextTest.java

Fix issue https://github.com/google/instrumentation-java/issues/224.

Fix a flaky test in StatsContextTest.java.

---

core/src/main/java/com/google/instrumentation/common/Clock.java

Clock is an abstract class. It can have different implementations for Java 7,
Java 8, and tests.

Add an interface for getting the time throughout the Instrumentation library.

---

core/src/main/java/com/google/instrumentation/stats/RpcConstants.java
core/src/main/java/com/google/instrumentation/stats/RpcMeasurementConstants.java
core/src/main/java/com/google/instrumentation/stats/RpcViewConstants.java
core/src/test/java/com/google/instrumentation/stats/RpcConstantsTest.java
core/src/test/java/com/google/instrumentation/stats/RpcMeasurementConstantsTest.java
core/src/test/java/com/google/instrumentation/stats/RpcViewConstantsTest.java
core_impl/src/main/java/com/google/instrumentation/stats/SupportedViews.java
core_impl/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMapTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsContextTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsTest.java

Fix https://github.com/google/instrumentation-java/issues/188.

Split RpcConstants into two files.

---

core_impl/build.gradle
core_impl/src/main/java/com/google/instrumentation/trace/SpanData.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanDataTest.java

Fix the compileOnly build for auto_value library.

Change SpanData to use AutoValue.

---

core_impl/src/main/java/com/google/instrumentation/trace/SpanImpl.java
core_impl/src/main/java/com/google/instrumentation/trace/TimestampConverter.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanImplTest.java
core_impl/src/test/java/com/google/instrumentation/trace/TimestampConverterTest.java

* The implementation is not completed but allows us to implement the StartEndHandler in parallel with the rest of the implementation.

Add initial span implementation.

---

core_impl/src/main/java/com/google/instrumentation/trace/SpanImpl.java
core_impl/src/main/java/com/google/instrumentation/trace/TraceComponentImplBase.java
core_impl/src/main/java/com/google/instrumentation/trace/TraceExporterImpl.java
core_impl/src/test/java/com/google/instrumentation/trace/TraceComponentImplBaseTest.java
core_impl/src/test/java/com/google/instrumentation/trace/TraceExporterImplTest.java
core_impl_android/src/main/java/com/google/instrumentation/trace/TraceComponentImpl.java
core_impl_java/src/main/java/com/google/instrumentation/trace/TraceComponentImplJava.java

Supports only service export for the moment.
Different design for https://github.com/google/instrumentation-java/pull/287

Change TraceExporterImpl to implement also the StartEndHandler.

---

core/src/main/java/com/google/instrumentation/stats/DistributionAggregation.java
core/src/test/java/com/google/instrumentation/stats/DistributionAggregationTest.java

The first commit is from #293.

Improve formatting of DistributionAggregation's Javadocs and check invariants.

---

.travis.yml
all/build.gradle
benchmarks/build.gradle
build.gradle
core/build.gradle
core_impl/build.gradle
core_impl_android/build.gradle
core_impl_java/build.gradle
examples/build.gradle
settings.gradle

Change the api jar name to match the maven artifact.

Rename gradle subprojects name to match the directories name.

---

checkstyle.license
checkstyle.xml

Fix the issue https://github.com/google/instrumentation-java/issues/274
Found one file without the license using this check.

Add check for the license header.

---

core/src/main/java/com/google/instrumentation/trace/Samplers.java
core/src/main/java/com/google/instrumentation/trace/SpanData.java
core/src/main/java/com/google/instrumentation/trace/TraceConfig.java
core/src/test/java/com/google/instrumentation/trace/SamplersTest.java
core/src/test/java/com/google/instrumentation/trace/TraceParamsTest.java

Make the probability sampler with a default probability of 1/10000 the default sampler for instrumentation library.

Change the default sampler.

---

core/src/main/java/com/google/instrumentation/stats/BucketBoundaries.java
core/src/main/java/com/google/instrumentation/stats/Distribution.java
core/src/main/java/com/google/instrumentation/stats/MutableDistribution.java
core/src/test/java/com/google/instrumentation/stats/BucketBoundariesTest.java
core/src/test/java/com/google/instrumentation/stats/MutableDistributionTest.java

Resolves some TODO's in the original Distribution code:
* Allows for zero-length bucketBoundaries (creates single bucket for over and underflow bucket, matching documentation allowing N=1 total buckets)
* Simplifies Range by not using null for initial min/max.

Fix Distribution TODOs

---

examples/build.gradle
examples/src/main/java/com/google/instrumentation/examples/stats/StatsRunner.java

Update stats example to use APIs in StatsContextFactory.

---

build.gradle
core/src/main/java/com/google/instrumentation/stats/ContextUtils.java
core/src/main/java/com/google/instrumentation/stats/StatsContext.java
core/src/main/java/com/google/instrumentation/stats/StatsContextFactory.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/stats/ContextUtilsTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsContextFactoryTest.java

Cherry-picked the commits related to STATS_CONTEXT_KEY and getCurrentStatsContext() and withStatsContext() APIs.
/cc @dinooliva

Bump version to 0.4.3

---

api/src/main/java/io/opencensus/trace/config/TraceConfig.java
api/src/test/java/io/opencensus/trace/config/TraceConfigTest.java
api/src/test/java/io/opencensus/trace/config/TraceParamsTest.java
core_impl/src/main/java/io/opencensus/trace/TraceComponentImplBase.java
core_impl/src/main/java/io/opencensus/trace/config/TraceConfigImpl.java
core_impl/src/test/java/io/opencensus/trace/config/TraceConfigImplTest.java

Summary of the PR:
- Remove unimplemented method from TraceConfig.
- Move config implementations to config package.
- Add tests for NoopTraceConfig.

Cleanup in config package.

---

api/src/main/java/io/opencensus/trace/SpanBuilder.java
api/src/main/java/io/opencensus/trace/Tracer.java
api/src/main/java/io/opencensus/trace/internal/SpanFactory.java
api/src/test/java/io/opencensus/trace/SpanBuilderTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
core_impl/src/main/java/io/opencensus/trace/SpanFactoryImpl.java

For testing/mocking we will add a separate artifact that allows users to test their instrumentation without depending on the internal classes.

Move SpanFactory into internal package. No need to be in the public API.

---

api/src/main/java/io/opencensus/trace/export/ExportComponent.java
api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
api/src/test/java/io/opencensus/trace/export/ExportComponentTest.java
impl_core/src/main/java/io/opencensus/trace/StartEndHandlerImpl.java
impl_core/src/main/java/io/opencensus/trace/TraceComponentImplBase.java
impl_core/src/main/java/io/opencensus/trace/export/ExportComponentImpl.java
impl_core/src/main/java/io/opencensus/trace/export/RunningSpanStoreImpl.java
impl_core/src/test/java/io/opencensus/trace/export/ExportComponentImplTest.java
impl_core/src/test/java/io/opencensus/trace/export/RunningSpanStoreTest.java

Based on a comment from https://github.com/census-instrumentation/instrumentation-java/pull/356

Rename ActiveSpansExporter to RunningSpanStore.

---

core/src/main/java/io/opencensus/tags/TagContext.java
core/src/main/java/io/opencensus/tags/TagKey.java
core/src/test/java/io/opencensus/tags/TagContextTest.java

I'm working on #323, but I wanted to rename TagMap in a separate PR to reduce the size of the diff.

Rename TagMap to TagContext.

---

core/src/main/java/io/opencensus/stats/RpcMeasurementConstants.java

Change RpcMeasurementConstants.RPC_STATUS to "canonical_status".

---

core/src/main/java/com/google/instrumentation/stats/RpcConstants.java

This is similar to #397, but applied to 0.4.x.
/cc @zhangkun83 @dinooliva

Change RpcConstants.RPC_STATUS to "canonical_status".

---

api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
api/src/main/java/io/opencensus/trace/ScopedSpanHandle.java
api/src/main/java/io/opencensus/trace/Tracer.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
api/src/test/java/io/opencensus/trace/ContextUtilsTest.java
api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java

Move ContextUtils to io.opencensus.trace.unsafe package.

---

core/src/main/java/io/opencensus/stats/ViewData.java
core/src/main/java/io/opencensus/stats/ViewManager.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/stats/ViewManagerImpl.java
core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

Rename: View -> ViewData, MutableView -> MutableViewData
This PR only contains renaming stuff, so I believe it doesn't conflict with our ongoing discussion on View refactoring.

Rename View to ViewData.

---

core/src/main/java/io/opencensus/stats/RpcViewConstants.java
core/src/main/java/io/opencensus/stats/View.java
core/src/main/java/io/opencensus/stats/ViewData.java
core/src/main/java/io/opencensus/stats/ViewManager.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/stats/ViewManagerImpl.java
core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

Rename: ViewDescriptor -> View, ViewDescriptor.TagKeys -> View.Dimensions
Just renaming stuff, doesn't involve any data structure changes.

Refactor ViewDescriptor.

---

core/src/main/java/io/opencensus/stats/DistributionAggregate.java
core/src/main/java/io/opencensus/stats/IntervalAggregate.java
core/src/main/java/io/opencensus/stats/ViewData.java
core/src/test/java/io/opencensus/stats/DistributionAggregateTest.java
core/src/test/java/io/opencensus/stats/IntervalAggregateTest.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

More renaming changes... Aggregation -> Aggregate

Rename Aggregation to Aggregate.

---

.github/ISSUE_TEMPLATE

This is based on a comment in #436.

Specify that the issue template only applies to bug reports.

---

RELEASING.md

We fixed the problem in tag v0.5.1.

Update releasing known issues.

---

build.gradle

This property contains the version of the FindBugs tool and the
FindBugs JSR 305 jar.

Introduce a new property "findBugsVersion" and use it consistently.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/ExecutorInstrumentation.java

This PR contains a few trivial commits that I've managed to accidentally drop from #411 when rebasing from a different machine.

Add commits accidentally dropped from #411.

---

api/src/main/java/io/opencensus/internal/Provider.java
api/src/test/java/io/opencensus/internal/ProviderTest.java

newInstance was replaced by Provider.createInstance, which was designed to work
with shading and Android.  This is part of
https://github.com/census-instrumentation/opencensus-java/issues/151 .
/cc @dinooliva @bogdandrutu

Remove Provider.newInstance(...).

---

core/src/main/java/io/opencensus/tags/TagKey.java
core/src/main/java/io/opencensus/tags/TagValueString.java

Improve class-level documentation for TagKey and TagValueString.

---

core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

Change the impl tests based on the refactored stats implementation.

Update tests on implementations.

---

core_impl/src/test/java/io/opencensus/impl/tags/TagContextsImplTest.java

The new name matches the class under test.

Rename TagContextFactoryImplTest to TagContextsImplTest.

---

api/src/main/java/io/opencensus/internal/Provider.java
api/src/main/java/io/opencensus/trace/Tracing.java
api/src/test/java/io/opencensus/internal/ProviderTest.java
core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/tags/Tags.java

This fixes https://github.com/census-instrumentation/opencensus-java/issues/487

Stop using context ClassLoader in Provider

---

build.gradle
core/src/test/java/io/opencensus/stats/MeasureMapTest.java
core/src/test/java/io/opencensus/stats/MeasureTest.java
core/src/test/java/io/opencensus/stats/RpcViewConstantsTest.java
core/src/test/java/io/opencensus/stats/StatsTest.java
core/src/test/java/io/opencensus/stats/TagKeyTest.java
core/src/test/java/io/opencensus/stats/TagTest.java
core/src/test/java/io/opencensus/stats/TagValueTest.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextFactoryTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

Enable checkstyle for tests in stats package.

---

core/src/main/java/io/opencensus/stats/Aggregation.java
core/src/main/java/io/opencensus/stats/AggregationData.java
core/src/main/java/io/opencensus/stats/MeasureMap.java
core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/stats/StatsRecorder.java
core_impl/src/main/java/io/opencensus/impl/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/impl/stats/MutableAggregation.java
core_impl/src/main/java/io/opencensus/impl/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/impl/stats/StatsComponentImplBase.java
core_impl/src/main/java/io/opencensus/impl/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/impl/stats/StatsRecorderImpl.java
core_impl/src/main/java/io/opencensus/impl/stats/ViewManagerImpl.java
core_impl/src/test/java/io/opencensus/impl/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/impl/stats/MutableAggregationTest.java
core_impl/src/test/java/io/opencensus/impl/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/impl/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/impl/stats/ViewManagerImplTest.java
core_impl/src/test/java/io/opencensus/stats/UnreleasedApiAccessor.java
core_impl_android/src/main/java/io/opencensus/impl/stats/StatsComponentImplLite.java
core_impl_android/src/test/java/io/opencensus/impl/stats/StatsTest.java
core_impl_java/src/main/java/io/opencensus/impl/stats/StatsComponentImpl.java
core_impl_java/src/test/java/io/opencensus/impl/stats/StatsTest.java

Will remove `StatsContextFactory`, `Tag`, `TagKey`, `TagValue` under stats package, and use new APIs in tags package in the next PR.

Move stats to impl.stats, change some visibility.

---

contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationTest.java

Add missing @RunWith(JUnit4.class) annotation.

---

core/src/main/java/io/opencensus/stats/Measure.java
core/src/main/java/io/opencensus/stats/View.java
core/src/test/java/io/opencensus/stats/MeasureTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java

Add documentation on name restrictions.

---

api/src/main/java/io/opencensus/trace/BlankSpan.java
api/src/main/java/io/opencensus/trace/Span.java
api/src/test/java/io/opencensus/trace/BlankSpanTest.java
api/src/test/java/io/opencensus/trace/SpanTest.java
benchmarks/src/jmh/java/io/opencensus/trace/RecordTraceEventsNonSampledSpanBenchmark.java
benchmarks/src/jmh/java/io/opencensus/trace/RecordTraceEventsSampledSpanBenchmark.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHttpHandler.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/SpanImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/520.

Add new api that is easier to use for user to add only one Attribute.

---

core_impl/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsRecorderImpl.java

Make MutableViewData abstract, so that we can have two separate sub-classes for Cumulative and Interval stats.

Make MutableViewData abstract.

---

all/build.gradle
build.gradle
contrib/grpc_util/README.md
contrib/grpc_util/build.gradle
contrib/grpc_util/src/main/java/io/opencensus/contrib/grpc/util/StatusConverter.java
contrib/grpc_util/src/test/java/io/opencensus/contrib/grpc/util/StatusConverterTest.java
settings.gradle

Fixes https://github.com/census-instrumentation/opencensus-java/issues/576

Add a new artifact for gRPC utility classes for instrumentation.

---

api/src/main/java/io/opencensus/common/Duration.java
api/src/main/java/io/opencensus/common/TimeUtil.java
api/src/main/java/io/opencensus/common/Timestamp.java
api/src/test/java/io/opencensus/common/DurationTest.java
core/src/main/java/io/opencensus/stats/View.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
core_impl/src/test/java/io/opencensus/implcore/stats/IntervalBucketTest.java
findbugs-exclude.xml

Add compareTo() method for Duration. Duration will be ordered similar to Timestamp.

Implement Duration.compareTo()

---

api/src/main/java/io/opencensus/trace/Sampler.java
api/src/main/java/io/opencensus/trace/samplers/AlwaysSampleSampler.java
api/src/main/java/io/opencensus/trace/samplers/NeverSampleSampler.java
api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
contrib/zpages/build.gradle
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TraceConfigzZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java

To test this change:
./gradlew installDist && ./examples/build/install/examples/bin/ZPagesTester
Go to:
localhost:8080/traceconfigz
Missing tests, will be added later because this is a P0 for 0.6 and is relatively simple code.

Add a simple traceconfigz page.

---

core/src/main/java/io/opencensus/stats/Stats.java

This change should have been included in #468.

Remove redundant null checks from Stats class.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/Resources.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/616

Fix opencensus agent to be java6 compatible.

---

core_impl/src/main/java/io/opencensus/implcore/tags/SerializationUtils.java

This commit also creates constants for two of the classes, since the instances
can be reused.

Replace anonymous classes in SerializationUtils with nested classes.

---

api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SampledSpanStoreImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/622

Add a method to list all registered span names.

---

api/src/main/java/io/opencensus/trace/BlankSpan.java
api/src/main/java/io/opencensus/trace/Span.java
api/src/test/java/io/opencensus/trace/SpanTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/624

Implement deprecated method addAttributes in the Span and remove it from anywhere else.

---

core/src/main/java/io/opencensus/stats/AggregationData.java
core/src/test/java/io/opencensus/stats/AggregationDataTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

API change to support long typed AggregationData.

Add SumDataDouble and SumDataLong

---

core/src/main/java/io/opencensus/stats/NoopStats.java
core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/stats/StatsComponent.java
core/src/main/java/io/opencensus/stats/StatsRecorder.java
core/src/test/java/io/opencensus/stats/NoopStatsTest.java
core/src/test/java/io/opencensus/stats/StatsTest.java

This design is more consistent with the 'tags' package.

Move stats no-op classes into a new class, NoopStats.

---

core_impl/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

This PR addresses https://github.com/census-instrumentation/opencensus-java/pull/672#discussion_r141222897.

Add tag key to message about deserializing invalid tag value.

---

core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/stats/StatsComponent.java

#677 added a no-op ViewManager.

Remove out of date Nullable annotations.

---

core/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
core/src/main/java/io/opencensus/tags/propagation/TagPropagationComponent.java

Add link to the cross-language binary serialization format for TagConext.

---

core/src/main/java/io/opencensus/stats/Measure.java
core/src/main/java/io/opencensus/stats/Measurement.java

Add Javadoc for Measure and Measurement

---

core_impl/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

The refactoring will simplify testing more cases for #655.  Checking error
messages ensures that we are testing the right error cases.

Refactor deserialization unit tests, and test error messages.

---

impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java

Resolves https://github.com/grpc/grpc-java/issues/3578

Make disruptor thread daemon.

---

api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/StatsRecord.java
api/src/test/java/io/opencensus/stats/NoopStatsTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsRecordImpl.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

See https://github.com/census-instrumentation/opencensus-java/pull/676/files#r146735409.

Rename 'StatsRecord.recordWithExplicitTagContext' to 'record'.

---

build.gradle

Update grpc Context version and junit.

---

core_impl/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/649
Calculate sum of squared deviations by using the Parallel algorithm. Thanks @isturdy for providing a solution to this issue.

Calculate sum of squared deviations for IntervalView

---

api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/ViewManager.java
api/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/718

Returns null when getting unregistered views

---

api/src/main/java/io/opencensus/stats/Measure.java
api/src/test/java/io/opencensus/stats/MeasureTest.java

To be consistent with TagKey and TagValue.

Update max length of Measure name to 255

---

contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/Resources.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/ResourcesTest.java

- Also test the "public" method.
- Remove precondition checks in private methods.

Improve test coverage.

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/754

Combine RPC_CLIENT_METHOD and RPC_SERVER_METHOD

---

api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
build.gradle

Bump version to 0.8.0
Bump version to 0.8.1-SNAPSHOT

Prepare release.

---

api/src/test/java/io/opencensus/trace/ScopedSpanHandleTest.java
api/src/test/java/io/opencensus/trace/SpanTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
build.gradle
exporters/trace/logging/src/test/java/io/opencensus/exporter/trace/logging/LoggingExporterTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporterTest.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java

I'm not sure if anything is blocking this update. In any case, the required changes seem straightforward enough, thus just sending this PR.

Use the current release version of Mockito.

---

impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
testing/src/main/java/io/opencensus/testing/export/TestHandler.java

Move FakeServiceHandler to -testing so that I can use it from the agent's integration tests.

Move FakeServiceHandler to -testing.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceStrategy.java

Don't import classes that are not visible from the bootstrap classloader.

---

api/src/main/java/io/opencensus/trace/BlankSpan.java
api/src/main/java/io/opencensus/trace/EndSpanOptions.java
api/src/main/java/io/opencensus/trace/Span.java
api/src/test/java/io/opencensus/trace/BlankSpanTest.java
api/src/test/java/io/opencensus/trace/EndSpanOptionsTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/SpanImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/597

Add a setStatus method in the Span.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceStrategyImpl.java

Uses https://github.com/census-instrumentation/opencensus-java/pull/779.

Simplify the code for setting the span status.

---

contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationIT.java

The previous code was using low-level synchronization based on
notify and wait - and it was wrong. The code allowed for a race condition
where notify is called before wait. In that case, notify will have no effect,
and wait will wait forever until interrupted by the test timeout.
I believe this to be the root cause of #793 (and the previous occurrences
in #540).
Just avoid the low-level synchronization and use Semaphore instead.

Fix the wrong use of notify and wait.

---

build.gradle
contrib/agent/README.md
contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextTrampolineInitializer.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/Instrumenter.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceTrampolineInitializer.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentation.java
contrib/agent/src/main/resources/reference.conf
contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationTest.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentationTest.java

This is just an initial version to get basic infrastructure in place together with preliminary end-to-end examples. To keep this PR small, I want to leave most refinements to future PRs, such as the introduction of a Settings class with proper accessors. Same for the config-driven instrumentation for tracing.

Add initial support for configuring the agent.

---

README.md

Fixes https://github.com/census-instrumentation/opencensus-java/issues/821

Add badge to javadoc from javadoc.io.

---

impl_core/src/main/java/io/opencensus/implcore/internal/DaemonThreadFactory.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java

This fixes the compatibility issue in GAE Java 7.
Please refer to [comment](https://github.com/census-instrumentation/opencensus-java/pull/868#issuecomment-348715397) for test result details.
- Summary
GAE Java 7 forbids spawning new threads manually (see [link](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/ThreadManager) for detail). Besides, modifying thread name and setting as daemon are also prohibited. 
- Solution
As recommended [here](https://github.com/grpc/grpc-java/blob/v1.7.0/core/src/main/java/io/grpc/internal/GrpcUtil.java#L517).
- Refactor `DaemonThreadFactory` to utilize `MoreExecutors`
- Change `SpanExporterImpl#WorkerThread` to `Runnable` and use `DaemonThreadFactory` to perform creation.

Use AppEngine compatible way to create threads. (fixes #707 and #777)

---

exporters/stats/stackdriver/README.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

* Add task_id label.
* Update README to explain the new label.
(cherry picked from commit 18d065a63a422f50cfa3895a476a3212ec00ef36)

Add task_id label. (#880)

---

exporters/stats/stackdriver/README.md

(cherry picked from commit 69aa742a314f847f846de7b10c8cf464e5c41ee9)

Slight update to exporter README (#884)

---

api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/test/java/io/opencensus/trace/SpanIdTest.java
api/src/test/java/io/opencensus/trace/TraceIdTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/B3FormatTest.java

Code extracted from https://github.com/census-instrumentation/opencensus-java/pull/606.

Add initial support for b3-propagation headers.

---

impl_core/src/main/java/io/opencensus/implcore/trace/propagation/CloudTraceFormat.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/CloudTraceFormatTest.java

Implementation based on Bogdan's [initial commit](https://github.com/bogdandrutu/opencensus-java/commit/e933b283ba3a5c23d66d9126c3408c79ff243a5a).

Add initial support fox X-Cloud-Trace-Context.

---

impl_core/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java

See https://github.com/census-instrumentation/opencensus-java/pull/909#discussion_r157324986.

Fix typo in test name.

---

api/src/main/java/io/opencensus/stats/ViewData.java
api/src/test/java/io/opencensus/stats/ViewDataTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/838

Validate types of Aggregation and AggregationData when creating ViewData

---

build.gradle
checker-framework/stubs/guava.astub
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TraceConfigzZPageHandler.java

This commit adds a stub file as described in ~~https://checkerframework.org/releases/0.9.9/checkers-manual.html#stub-creating-and-using~~
https://checkerframework.org/manual/#stub.  The initial file contains annotations for
com.google.common.base.Strings.isNullOrEmpty.
/cc @songy23

Add Checker Framework stub file for Guava (fixes #920).

---

exporters/stats/stackdriver/README.md

Change "opencensus-task" to "opencensus_task" in documentation to match the implementation.

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/453

Add Javadocs for tag keys in RpcMeasureConstants.java

---

build.gradle
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java

The new google cloud java also uses grpc 1.9

Update google cloud java version.

---

RELEASING.md
examples/build.gradle
examples/pom.xml

Fix #940 in v0.11.x release branch.

[v0.11.x] Update scripts in RELEASING.md to include build.gradlew and examples/pom.xml, and apply the change.

---

README.md
RELEASING.md
contrib/grpc_util/README.md
contrib/http_util/README.md
contrib/zpages/README.md
examples/build.gradle
examples/opencensus_workspace.bzl
examples/pom.xml
exporters/stats/signalfx/README.md
exporters/stats/stackdriver/README.md
exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

I added sections in `RELEASING.md` on how to announce a new release and update release versions in readmes and build files.
This PR also contains the result of executing these added scripts. I've manually checked there are no more occurrences of old version "0.10.1".

Update script in RELEASING.md and use them to update release version in all readmes and build files. (fixes #941)

---

exporters/stats/stackdriver/README.md

Closes https://github.com/census-instrumentation/opencensus-java/issues/895.

Update StackdriverStatsExporter to use the new configuration class.

---

exporters/stats/signalfx/README.md
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporter.java

Fix some typos in SignalFX exporter code examples

---

README.md
contrib/grpc_util/README.md
contrib/http_util/README.md
contrib/zpages/README.md
examples/build.gradle
examples/opencensus_workspace.bzl
examples/pom.xml
exporters/stats/signalfx/README.md
exporters/stats/stackdriver/README.md
exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

Update release versions for all readme and build files to `0.11.1`.

---

build.gradle

The idea plugin is there already, this gives eclipse users a much easier start.

Adds Eclipse plugin to build.gradle

---

.travis.yml
README.md
all/build.gradle

This PR also adds a status badge for Codecov.

Remove Coveralls code coverage (closes #791).

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/984.

Add javadoc for all RPC measures and views

---

exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/967.
A screenshot of the tracez page:

Instrument the Prometheus Stats Exporter with trace

---

contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java

To resolve the potential race condition when getting the Statsz page.

Synchronize the access to the tree, views and measures for Statsz.

---

README.md
contrib/grpc_util/README.md
contrib/http_util/README.md
contrib/zpages/README.md
examples/build.gradle
examples/pom.xml
exporters/stats/signalfx/README.md
exporters/stats/stackdriver/README.md
exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

Created https://github.com/census-instrumentation/opencensus-java/issues/1009 to update some remaining files (don't have bazel installed on my laptop).

Update release versions for all readme and build files.

---

examples/opencensus_workspace.bzl

Closes https://github.com/census-instrumentation/opencensus-java/issues/1009
Auto-generated by https://github.com/census-instrumentation/opencensus-java/blob/master/RELEASING.md#update-release-versions-in-documentations-and-build-files.

Update opencensus version for bazel build file in examples

---

.travis.yml
api/src/main/java/io/opencensus/stats/Stats.java
api/src/main/java/io/opencensus/tags/Tags.java
api/src/main/java/io/opencensus/trace/Tracing.java
build.gradle
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
scripts/travis_script

This PR adds a Java 9 build job.  Previously, the build applied -Werror when the Java version was 8 or greater.  Since the Java 9 build currently has some warnings (issue #1014), I applied -Werror only with Java 8 and added a TODO.  I also fixed some Error Prone warnings.

Test with oraclejdk9 on Travis.

---

build.gradle
impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java

* Update disruptor and fix warnings.
* Fix bug that holds the memory to all recorded events in disruptor.
(cherry picked from commit 2e9b2f02c5b02e541e6941add4ee28f4fd44636c)

Fix bugs, fix warnings and update disruptor. (#1021)

---

exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java

@jorgheymans and I noticed when plotting brave+census integration

Fixes copy/paste errors

---

README.md

Fixes https://github.com/census-instrumentation/opencensus-java/issues/740.

Add quick start example to README

---

examples/BUILD.bazel
examples/README.md
examples/build.gradle
examples/pom.xml
examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldClient.java
examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldServer.java
examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldUtils.java
examples/src/main/proto/helloworld.proto

Provides an (almost) identical gRPC Hello World example to [OpenCensus-C++](https://github.com/census-instrumentation/opencensus-cpp/tree/master/examples/grpc).
For now this example supports Maven and Gradle build. I'll post another PR to add support for bazel to avoid making this PR too huge (adding bazel build for this example introduces a huge amount of new dependencies).
EDIT: closes https://github.com/census-instrumentation/opencensus-java/issues/599.
~~For now this example only supports Maven build. I'll post another PR to add support for gradle and bazel to avoid making this PR too huge.~~
/cc @g-easy 
~~Maven building is working - I'm working on getting gradle/bazel work as well~~
~~TODO:~~
~~- [ ] Fix gradle and bazel build.~~
~~- [ ] Read port number from args.~~
~~- [ ] Add …

Add a gRPC Hello World example.

---

examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java

Raised in https://github.com/census-instrumentation/opencensus-cpp/issues/112.

Fix comment about bucket boundaries in the helloworld example.

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

Fixes #1066.
Though this executes another process, this is hopefully more reliable and faster than scanning the `PATH` for a `docker` executable, and therefore fixes AppVeyor's CI builds.

Run docker -v to find whether Jaeger integration test can be performed.

---

exporters/stats/stackdriver/README.md

The default instructions should rely on default settings. There's a section further below that provides instructions on how to configure auth + project.

Simplify README.md

---

api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
benchmarks/build.gradle
build.gradle

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1090.
Also replace a deprecated guava method.
I wasn't able to upgrade to the latest guava version, since it conflicted with Jmh findBugs.

Update Guava and Jmh versions

---

api/src/main/java/io/opencensus/stats/Aggregation.java
api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/main/java/io/opencensus/stats/ViewData.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1094
/cc @dinooliva

Deprecate Mean and MeanData

---

exporters/stats/stackdriver/README.md

As a follow up of https://github.com/census-instrumentation/opencensus-java/pull/1071.

Update StackdriverStatsExporter README about auto-detecting resources.

---

api/src/main/java/io/opencensus/stats/View.java
api/src/test/java/io/opencensus/stats/ViewTest.java

This PR also contains some cleanup changes in ViewTest.java.

Sort TagKeys in View.create(...) (fixes #1080).

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java

As a follow up for https://github.com/census-instrumentation/opencensus-java/pull/1115.

Fix issues in RPC constants

---

api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java

eyes crossed until I figured out why this comment was there!

Clarifies implementation details on BinaryFormat

---

exporters/trace/jaeger/build.gradle
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java

Before, the Jaeger integration test hand-rolled docker setup which
failed on my machine, distracting from other unrelated change. When
looking at it, I noticed it wasn't using the normal test libraries as well.
This cleans up everything and now works as expected.

This fixes the Jaeger integration test and generally cleans it up

---

api/src/main/java/io/opencensus/common/Duration.java
api/src/test/java/io/opencensus/common/DurationTest.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java

As a follow up of https://github.com/census-instrumentation/opencensus-java/pull/1114.

Improve Duration.toMillis()

---

exporters/stats/stackdriver/README.md

Update README about auto detecting AWS EC2 resource.

Update the MonitoredResource section in SD readme

---

api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
build.gradle
examples/build.gradle
examples/pom.xml

Start 0.14.0 development cycle

---

README.md
contrib/grpc_util/README.md
contrib/http_util/README.md
contrib/zpages/README.md
examples/build.gradle
examples/pom.xml
exporters/stats/prometheus/README.md
exporters/stats/signalfx/README.md
exporters/stats/stackdriver/README.md
exporters/trace/instana/README.md
exporters/trace/jaeger/README.md
exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

~~TODO:~~
~~- [ ] Update `examples/opencensus_workspace.bzl` once v0.13.0 is available on Maven central.~~

Update release versions for readme and build files.

---

CHANGELOG.md

(cherry picked from commit 6dfa99f4613404bc0dd0bc7c44bb62833e35a9b4)
This PR is for v0.13.x branch.

Update CHANGELOG.md for v0.13.0 release. (#1161)

---

examples/WORKSPACE
examples/opencensus_workspace.bzl

Closes https://github.com/census-instrumentation/opencensus-java/issues/1163

Update release versions for Bazel BUILD.

---

buildscripts/kokoro/linux.cfg
buildscripts/kokoro/linux.sh

Start with Linux build. Subsequently add other platforms.

Add build script and configure for Internal CI build.

---

buildscripts/kokoro/windows.bat
buildscripts/kokoro/windows.cfg

* compiled buildscripts/kokoro/windows.bat on Windows instance.

Add kokoro build scripts for windows platform.

---

buildscripts/kokoro/linux.sh
buildscripts/kokoro/macos.cfg

Add kokoro build scripts for osx platform.

---

exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

Map http attributes to the stackdriver format, resolves #1153

---

exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

(cherry picked from commit a1a6cf16ec5e6ec3c1e08e96b1e8dd9a45dce13e)
/cc @Sebruck

Map http attributes to the stackdriver format, resolves #1153 (#1183)

---

CHANGELOG.md

(cherry picked from commit 3ec4997322d8fe0dd809f99de19f923ff2cc8d15)

Update CHANGELOG about v0.13.2 release. (#1188)

---

CHANGELOG.md
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/1202.
/cc @Sebruck

Prometheus exporter: remove namespace and prefix for help message.

---

exporters/trace/stackdriver/README.md

Related to https://github.com/census-instrumentation/opencensus-java/issues/1184.

Stackdriver Trace Exporter: update README about auth setup and project id in bad format.

---

buildscripts/kokoro/linux_build.cfg
buildscripts/kokoro/linux_example_bazel.cfg
buildscripts/kokoro/linux_example_format.cfg
buildscripts/kokoro/linux_example_gradle.cfg
buildscripts/kokoro/linux_example_license.cfg
buildscripts/kokoro/linux_example_maven.cfg
buildscripts/kokoro/linux_framework.cfg
buildscripts/kokoro/linux_git_history.cfg
buildscripts/kokoro/linux_presubmit.sh
scripts/check-git-history.py

- Each task is treated as separate job to run in parallel.
- single script linux_presumbit.sh performs all task based TASK env.

To bring parity with travis build add missing tasks to kokoro build.

---

buildscripts/kokoro/linux_presubmit.sh

- Added option -Z to exit with 1 on failure.

Run codecov reporting only if running as a part of kokoro build.

---

exporters/stats/stackdriver/README.md

Related to https://github.com/census-instrumentation/opencensus-java/issues/1220.

Add a note about Guava version conflicts in cloud client library.

---

CHANGELOG.md

(cherry picked from commit c2ad4c3e84c90aaa600c8c28ef4bb75a0513804d)

Update CHANGELOG (#1235)

---

contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

The project ID used for formatting trace IDs can be overridden with the property
"`io.opencensus.contrib.logcorrelation.stackdriver.OpenCensusTraceLoggingEnhancer.projectId`".
The property can be set as a java.util.logging property or a system property.
OpenCensusTraceLoggingEnhancer continues to use the google-cloud-logging default
project ID when the projectId property is not set.
This commit also caches the project ID on the OpenCensusTraceLoggingEnhancer
instance instead of looking it up for every log entry.

Allow overriding the Project ID used by OpenCensusTraceLoggingEnhancer.

---

RELEASING.md

The readme contains build file snippets that need to be updated for each
release.

Add contrib/log_correlation/stackdriver/README.md to RELEASING.md.

---

examples/src/main/java/io/opencensus/examples/zpages/ZPagesTester.java

So that there will be some useful information on the z pages.
**Before**:
Tracez
Statsz
Rpcz
**After**:
Tracez
Statsz
Rpcz
/cc @adamgarza

Examples: Record some stats and spans for ZPageTester.

---

CHANGELOG.md
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1209.

gRPC metrics: Add APIs to register gRPC client and server views separately.

---

api/src/main/java/io/opencensus/tags/Tagger.java

See census-instrumentation/opencensus-specs#99.

Clarify Javadoc for Tagger.withTagContext.

---

CHANGELOG.md

Forgot to add this change to CHANGELOG in https://github.com/census-instrumentation/opencensus-java/pull/1287.

Update CHANGELOG about Exemplar.

---

buildscripts/import-control.xml

Allow `metrics` classes import classes from the same package.

Update import control on metrics.

---

metrics/src/main/java/io/opencensus/metrics/Distribution.java
metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
metrics/src/test/java/io/opencensus/metrics/PointTest.java
metrics/src/test/java/io/opencensus/metrics/ValueTest.java

Pretty much a copy-and-paste of https://github.com/census-instrumentation/opencensus-java/pull/1287.

Metrics: Add Exemplar to Distribution.

---

exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1330.

Zipkin exporter: Use the correct attribute value.

---

metrics/src/main/java/io/opencensus/metrics/Distribution.java
metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
metrics/src/test/java/io/opencensus/metrics/PointTest.java
metrics/src/test/java/io/opencensus/metrics/ValueTest.java

According to Specs: https://github.com/census-instrumentation/opencensus-proto/pull/67.

Metrics: Remove Range from Distribution.

---

contrib/zpages/build.gradle
contrib/zpages/src/resources/style.css

Zpage handlers will need to be updated after resource path is resolved.

Zpages external CSS added and gradle modified to include this resource

---

impl_core/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Some internal clean up. None of these changes are user-visible.

Cleanup: Move static util methods to util class.

---

metrics/src/main/java/io/opencensus/metrics/Distribution.java
metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
metrics/src/test/java/io/opencensus/metrics/PointTest.java
metrics/src/test/java/io/opencensus/metrics/ValueTest.java

Per the proto definition: https://github.com/census-instrumentation/opencensus-proto/pull/70.

Metrics: Move Exemplar to be part of Bucket.

---

api/src/main/java/io/opencensus/trace/TraceState.java
api/src/main/java/io/opencensus/trace/Tracestate.java
api/src/test/java/io/opencensus/trace/TracestateTest.java

Please focus on the public API, I will add tests and benchmarks before submitting. Any other feedback is welcome as well.
/cc @lmolkova @adriancole @songy23 @SergeyKanzhelev

Add the initial version of the TraceState class.

---

api/src/main/java/io/opencensus/trace/Tracestate.java
api/src/test/java/io/opencensus/trace/TracestateTest.java

Improve how the builder is created for empty tracestate.

Minor improvements for Tracestate.

---

api/src/main/java/io/opencensus/common/ToDoubleFunction.java
api/src/main/java/io/opencensus/common/ToLongFunction.java
metrics/src/main/java/io/opencensus/metrics/MetricProducer.java
metrics/src/main/java/io/opencensus/metrics/MetricRegistry.java
metrics/src/main/java/io/opencensus/metrics/Metrics.java
metrics/src/main/java/io/opencensus/metrics/MetricsComponent.java
metrics/src/main/java/io/opencensus/metrics/export/MetricProducerManager.java
metrics/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
metrics/src/test/java/io/opencensus/metrics/MetricsComponentTest.java
metrics/src/test/java/io/opencensus/metrics/export/MetricProducerManagerTest.java

Add a new concept of MetricRegistry that can create new types of Metrics like Gauges and keeps a reference to all registered metrics.

Add support for recording Gauges.

---

api/src/main/java/io/opencensus/common/ToDoubleFunction.java
api/src/main/java/io/opencensus/common/ToLongFunction.java
api/src/main/java/io/opencensus/metrics/export/ExportComponent.java
api/src/main/java/io/opencensus/metrics/export/MetricProducerManager.java
api/src/test/java/io/opencensus/metrics/export/MetricProducerManagerTest.java
buildscripts/import-control.xml
impl/src/main/java/io/opencensus/impl/metrics/MetricsComponentImpl.java
impl/src/test/java/io/opencensus/impl/metrics/MetricsTest.java
impl_core/src/main/java/io/opencensus/implcore/metrics/MetricsComponentImplBase.java
impl_core/src/main/java/io/opencensus/implcore/metrics/export/ExportComponentImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/export/MetricProducerManagerImpl.java
impl_core/src/test/java/io/opencensus/implcore/metrics/MetricsComponentImplBaseTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/export/ExportComponentImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/export/MetricProducerManagerImplTest.java
impl_lite/src/main/java/io/opencensus/impllite/metrics/MetricsComponentImplLite.java
impl_lite/src/test/java/io/opencensus/impllite/metrics/MetricsTest.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1346.~~

 Metrics: Implement ExportComponent, make ProducerManager abstract.

---

impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java

A follow-up of https://github.com/census-instrumentation/opencensus-java/pull/1372.

Make an internal function static.

---

contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java

Avoiding accessing the OpenCensus tracing implementation early in initialization
is more robust.  See the discussion in
https://github.com/census-instrumentation/opencensus-java/pull/1371#discussion_r211440915
and
https://github.com/census-instrumentation/opencensus-java/pull/1371#discussion_r211441000.

Access current span using gRPC context key in OpenCensusTraceLoggingEnhancer.

---

build.gradle
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextStrategyImpl.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1403.

Update gRPC version to 1.14.

---

RELEASING.md
contrib/log_correlation/log4j/README.md

Add readme for opencensus-contrib-log-correlation-log4j.

---

contrib/log_correlation/stackdriver/README.md

This change is similar to a change made to Log4j log correlation: https://github.com/census-instrumentation/opencensus-java/pull/1402#discussion_r213934235

Stackdriver log correlation: Improve description of library stability.

---

contrib/log_correlation/log4j2/README.md

This commit is a continuation of #1411.

Update opencensus-contrib-log-correlation-log4j2 artifact/package names in readme.

---

CHANGELOG.md
api/src/main/java/io/opencensus/trace/AttributeValue.java
api/src/test/java/io/opencensus/trace/AttributeValueTest.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java

Also update Trace exporters and ZPages, and fix a few typos.
Fixes https://github.com/census-instrumentation/opencensus-java/issues/1441.

Tracing: Add AttributeValueDouble.

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

allow arbitrary metric prefixes

---

CHANGELOG.md

(cherry picked from commit 5faef17f74e5d8d857b50cc9e66e0f595080c488)

Update changelog for 0.16.0 release. (v0.16.x)

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

(cherry picked from commit 69360e984884902e60c0ffafe4c73a18702896ad)

allow arbitrary metric prefixes (v0.16.x)

---

CHANGELOG.md

(cherry picked from commit c78686d8ffb058723ebedda040ca5efd860aefe5)

Update changelog for 0.16.1 release. (v0.16.x)

---

api/src/main/java/io/opencensus/metrics/Distribution.java
api/src/main/java/io/opencensus/metrics/Metric.java
api/src/main/java/io/opencensus/metrics/MetricDescriptor.java
api/src/main/java/io/opencensus/metrics/Summary.java
api/src/main/java/io/opencensus/metrics/Value.java
api/src/test/java/io/opencensus/metrics/DistributionTest.java
api/src/test/java/io/opencensus/metrics/PointTest.java
api/src/test/java/io/opencensus/metrics/SummaryTest.java
api/src/test/java/io/opencensus/metrics/ValueTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java

* Add GAUGE_DISTRIBUTION and SUMMARY types.
* Modify Distribution to use sum instead of mean.

Make metrics compatible with the current proto definition.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java

Split from https://github.com/census-instrumentation/opencensus-java/pull/1476, to make that PR shorter.

Exporter/OcAgent: Add options on retry interval and config.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtils.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtilsTest.java

Split from #1476, to make that PR shorter.

Exporter/OcAgent: Add methods for getting and applying config.

---

build.gradle

So that Intellij would recognize the AutoValue classes.
/cc @dhaval24

Gradle: Add plug-in net.ltgt.apt-idea.

---

build.gradle

https://github.com/LMAX-Exchange/disruptor#342

Update disruptor to fix a race condition.

---

buildscripts/import-control.xml
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporter.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThreadTest.java

Exporter/Stats/SignalFx: export data using metrics API

---

api/src/main/java/io/opencensus/trace/Span.java
api/src/test/java/io/opencensus/common/ServerStatsEncodingTest.java
api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java
build.gradle
contrib/agent/src/jmh/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationBenchmark.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentation.java
contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpMeasureConstants.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
impl_core/src/main/java/io/opencensus/implcore/internal/CurrentState.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java

This commit also fixes and suppresses some new warnings.

Error Prone: 2.3.1 -> 2.3.2

---

api/src/main/java/io/opencensus/trace/Status.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpTraceUtil.java
contrib/http_util/src/test/java/io/opencensus/contrib/http/util/HttpTraceUtilTest.java

This is a split from PR https://github.com/census-instrumentation/opencensus-java/pull/1537.

Helper utility for Http Tracing.

---

build.gradle
exporters/trace/ocagent/README.md
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java

Add the Agent exporter to release artifacts and update `@since` tag for all public APIs.

Exporter/Trace/OcAgent: Update versions.

---

api/src/test/java/io/opencensus/internal/UtilsTest.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/util/HttpTraceUtil.java

This has caused failures for our import tool.

Style: Fix typos.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceExportRpcHandler.java

Split from https://github.com/census-instrumentation/opencensus-java/pull/1492.

Exporter/OcAgent: Add export RPC handler.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java

See https://github.com/census-instrumentation/opencensus-proto/blob/master/src/opencensus/proto/agent/trace/v1/trace_service.proto#L81.

Exporter/OcAgent: Use dedicated Resource proto instead of string map.

---

exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java

Related to https://github.com/census-instrumentation/opencensus-java/pull/1573.
The fake agent service impl will be used with an InProcessServer in the unit tests.

Exporter/OcAgent/Test: Make fake agent thread-safe.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1583.
Similar to https://github.com/census-instrumentation/opencensus-java/pull/1585.

Exporter/OcAgent: Use core resource API.

---

build.gradle
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java

Related to https://github.com/census-instrumentation/opencensus-java/issues/1578.

Build: Exclude OC-Agent exporter from this release for now.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

Exporter/Stats/Stackdriver: handle Summary Type

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java

Per https://github.com/census-instrumentation/opencensus-cpp/pull/234#issuecomment-443089712

Make our user-agent consistent with other user-agents.

---

CHANGELOG.md
contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java

Add ability to filter metrics we want to export

---

buildscripts/travis_script

This is a temporary fix until proper fix is figured out.

Fixing bazel build.

---

contrib/http_servlet/README.md
contrib/http_servlet/build.gradle

Remove version from build.gradle

fix version for http servlet in Readme file.

---

exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterWorker.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1637.~~
Fixes https://github.com/census-instrumentation/opencensus-java/issues/1567.

Exporter/Metrics/OcAgent: Add worker thread and exporter.

---

exporters/stats/signalfx/build.gradle
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricExporter.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporter.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricExporterTest.java

EDIT: updates https://github.com/census-instrumentation/opencensus-java/issues/1657.

Change SignalFx stats exporter to use metrics util.

---

contrib/http_servlet/build.gradle
contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletUtil.java

Remove jetty server dependency in http_servlet.

---

exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1680

Add option to add attributes to all exported spans to Stackdriver.

---

.travis.yml
appveyor.yml
buildscripts/travis_script

This is also what gRPC does for their tests.

Remove build for java7.

---

exporters/trace/datadog/README.md

Thanks @tylerbenson for reporting.

Exporter/Datadog: Fix typos in README.

---

impl_core/src/main/java/io/opencensus/implcore/tags/TagMapImpl.java

Add missing javadoc to public class, variable and method.

Tags: Fix Javadoc warnings.

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java

(cherry picked from commit 6e65fc407d3ca851169786b7d7f7bada1ec3d71a)

Clarify that realtime views are only for streaming rpcs (#1741)

---

RELEASING.md
contrib/dropwizard/README.md
contrib/dropwizard5/README.md
contrib/http_jaxrs/README.md
contrib/http_jetty_client/README.md
contrib/http_servlet/README.md
examples/build.gradle
exporters/trace/datadog/README.md

Just found we haven't included a few new artifacts in the releasing instructions. Added them to the list and updated the versions.

Update the REAME list in RELEASING.md

---

contrib/dropwizard/README.md
contrib/dropwizard5/README.md

Align the Gradle dependencies with the Maven dependencies.

Documentation: Fix Gradle dependency specs

---

.github/CODEOWNERS

Adding more people for code reviews and maintenance.

Add dinooliva and rghetia to code owners.

---

CHANGELOG.md
contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java

Modify default value to false for publicEndpoint in Http-Servlet.

---

exporters/metrics/ocagent/build.gradle
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java

Metrics counterpart of https://github.com/census-instrumentation/opencensus-java/pull/1776.

Exporter/Metrics/OcAgent: Add integration test.

---

contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractor.java
contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletExtractorTest.java

fix path and URL HttpServlet according to spec.

---

api/src/main/java/io/opencensus/metrics/data/package-info.java
buildscripts/import-control.xml

From https://github.com/census-instrumentation/opencensus-java/pull/1791#issuecomment-471727359.

Metrics: Add metrics.data package to hold common classes.

---

CHANGELOG.md
api/src/main/java/io/opencensus/tags/NoopTags.java
api/src/main/java/io/opencensus/tags/Tag.java
api/src/main/java/io/opencensus/tags/TagContextBuilder.java
api/src/main/java/io/opencensus/tags/TagMetadata.java
api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
api/src/test/java/io/opencensus/tags/NoopTagsTest.java
api/src/test/java/io/opencensus/tags/TagMetadataTest.java
api/src/test/java/io/opencensus/tags/TagTest.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpRequestContext.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java
impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
impl_core/src/main/java/io/opencensus/implcore/tags/NoopTagMapBuilder.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagContextUtils.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagMapBuilderImpl.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagMapImpl.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagValueWithMetadata.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/ScopedTagMapTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/TagMapImplTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1666.
~~DO NOT MERGE before https://github.com/census-instrumentation/opencensus-specs/pull/233 is submitted.~~

Tags: Add TagMetadata.

---

CHANGELOG.md
exporters/metrics/util/src/main/java/io/opencensus/exporter/metrics/util/QueueMetricProducer.java
exporters/metrics/util/src/test/java/io/opencensus/exporter/metrics/util/QueueMetricProducerTest.java

Metrics/Util: Add QueueMetricProducer.

---

api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
build.gradle
examples/build.gradle
examples/pom.xml
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java

Reverts census-instrumentation/opencensus-java#1819

Revert "Release"

---

examples/build.gradle
examples/pom.xml

Manually verified that example is working.

Examples: Uncomment OcAgentExportersQuickStart.

---

exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java

Use ThriftSender in JaegerExporter

---

impl_core/src/main/java/io/opencensus/implcore/tags/propagation/BinarySerializationUtils.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/CorrelationContextFormat.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagPropagationComponentImpl.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/CorrelationContextFormatTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

Fixes #1667.
~~Blocked by PR #1800.~~

Tags: Implementation of w3c correlation context format.

---

examples/build.gradle
examples/pom.xml

Examples: Upgrade Jetty version.

---

.github/ISSUE_TEMPLATE/feature_request.md

Also adds newline in form to be consistent with the bug report template.

Fixes typo in feature request.

---

impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedDoubleCumulativeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedLongCumulativeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DoubleCumulativeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/LongCumulativeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/MetricRegistryImpl.java
impl_core/src/test/java/io/opencensus/implcore/metrics/DerivedDoubleCumulativeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/DerivedLongCumulativeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/DoubleCumulativeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/LongCumulativeImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1815.
Everything is pretty much a copy-and-paste from Gauge implementation: https://github.com/census-instrumentation/opencensus-java/tree/master/impl_core/src/main/java/io/opencensus/implcore/metrics.

Metrics: Implementation of Cumulative APIs.

---

api/src/test/java/io/opencensus/metrics/DoubleCumulativeTest.java
api/src/test/java/io/opencensus/metrics/DoubleGaugeTest.java
api/src/test/java/io/opencensus/metrics/LongCumulativeTest.java
api/src/test/java/io/opencensus/metrics/LongGaugeTest.java
api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
api/src/test/java/io/opencensus/stats/NoopStatsTest.java
api/src/test/java/io/opencensus/tags/InternalUtilsTest.java
api/src/test/java/io/opencensus/tags/NoopTagsTest.java
api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java
api/src/test/java/io/opencensus/trace/SpanBuilderTest.java
api/src/test/java/io/opencensus/trace/TraceComponentTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
api/src/test/java/io/opencensus/trace/TracingTest.java
api/src/test/java/io/opencensus/trace/propagation/PropagationComponentTest.java
api/src/test/java/io/opencensus/trace/propagation/TextFormatTest.java
build.gradle
impl_core/src/test/java/io/opencensus/implcore/metrics/DoubleCumulativeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/DoubleGaugeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/LongCumulativeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/LongGaugeImplTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/export/MetricProducerManagerImplTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/CurrentTagMapUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/ScopedTagMapTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java

Also updated the version of `com.google.truth`.

Tests: Migrate from is(Not)SameAs to is(Not)SameInstanceAs.

---

impl_core/src/main/java/io/opencensus/implcore/trace/RecordEventsSpanImpl.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1876.

Log error if Spans are gc-ed without being closed.

---

CHANGELOG.md
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

Stackdriver Trace part of https://github.com/census-instrumentation/opencensus-java/issues/1880.

Exporter/Trace/Stackdriver: Provide Deadline option and don't do retry by default.

---

CHANGELOG.md
exporters/trace/zipkin/build.gradle
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterConfiguration.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinTraceExporter.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterConfigurationTest.java

Zipkin part of https://github.com/census-instrumentation/opencensus-java/issues/1880.
Almost identical to #1884.

Exporter/Zipkin: Use configurations and add deadline.

---

contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/ContainerResourceTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1903.

Contrib/Resource: Fix a typo in test.

---

impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java

Updates https://github.com/census-instrumentation/opencensus-java/issues/1910

Increase the buffer size for the trace export batch.

---

impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java

(cherry picked from commit 9c14ba219bcda73e0f15d0a639539a2b9eb225a7)

Increase the buffer size for the trace export batch. (#1911)

---

impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java

(cherry picked from commit 3cbeae0db312295781f39053164e68992f1b678e)

Trace: Further increase span export buffer size to 2.5k. (#1913)

---

build.gradle
impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java

This commit also suppresses a new nullness warning.

Checker Framework: 2.8.1 -> 2.8.2

---

build.gradle

add dependency to .pom file instead of .jar file.

---

examples/spring/servlet/src/main/java/io/opencensus/examples/spring/servlet/HelloController.java

The fix for [review comment](https://github.com/census-instrumentation/opencensus-java/pull/1939#discussion_r293495378) was left out in the commit 7eb24997be4bef9ad4fa195257fc3c3a18dd0c97

spring servlet example: make port configurable.

---

impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java

Count metrics should have unit '1'.

---

impl_core/src/main/java/io/opencensus/implcore/internal/DaemonThreadFactory.java

Removing AppEngine restriction on Java version.

---

exporters/stats/stackdriver/README.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1947.

Exporter/Stackdriver: Fix stale document on interval.

---

.travis.yml
buildscripts/travis_script

Replace oraclejdk8 with openjdk8 and remove jdk_switcher from Travis

---

contrib/http_servlet/build.gradle
contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/WriteListenerWrapper.java
contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/WriteListenerWrapperTest.java

Add Wrapper for WriteListener.

---

README.md

Drive-by fix for a dead link in the README.

Fix quickstart link in README

---

RELEASING.md

Originates from https://github.com/census-instrumentation/opencensus-java/pull/2008#pullrequestreview-356148528
/cc @rghetia

chore(RELEASING.md): update list of VERSION_FILES

---

README.md

@mayurkale22 let's see if this works

docs: 1.0 no longer expected

---

build.gradle

deps: update auth libraries

---

build.gradle

deps: update GSON

---

build.gradle

deps: update Guava to 29.0

---

CHANGELOG.md
api/src/main/java/io/opencensus/trace/unsafe/ContextHandleUtils.java
api/src/main/java/io/opencensus/trace/unsafe/ContextManagerImpl.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
api/src/test/java/io/opencensus/trace/unsafe/ContextUtilsTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java

Still going through release process, so there may be more necessary to get a full release, but at a minimum this backports fixes onto 0.28.x in preparation for a 0.28.3

Cherry-pick criticial fixes into 0.28.x branch for 0.28.3 release

---

CHANGELOG.md
README.md
build.gradle
contrib/appengine_standard_util/README.md
contrib/dropwizard/README.md
contrib/dropwizard5/README.md
contrib/exemplar_util/README.md
contrib/grpc_util/README.md
contrib/http_jaxrs/README.md
contrib/http_jetty_client/README.md
contrib/http_servlet/README.md
contrib/http_util/README.md
contrib/log_correlation/log4j2/README.md
contrib/log_correlation/stackdriver/README.md
contrib/spring/README.md
contrib/spring_sleuth_v1x/README.md
contrib/zpages/README.md
examples/build.gradle
examples/pom.xml
exporters/stats/prometheus/README.md
exporters/stats/signalfx/README.md
exporters/stats/stackdriver/README.md
exporters/trace/datadog/README.md
exporters/trace/elasticsearch/README.md
exporters/trace/instana/README.md
exporters/trace/jaeger/README.md
exporters/trace/logging/README.md
exporters/trace/ocagent/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

- Add missing changelog from 0.28.x series.
- Update docs for latest release.
- Update signing jar to allow GPG agent usage

Forward-fix things from 0.28.x branch

---

README.md
build.gradle
examples/build.gradle
examples/pom.xml
examples/spring/servlet/build.gradle
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java

Bump release version.

---

README.md
api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
build.gradle
examples/build.gradle
examples/pom.xml
examples/spring/servlet/build.gradle
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java

- Bump version to 0.31.1
- Bump versions

Bump version to 0.31.2-SNAPSHOT
