census-instrumentation/opencensus-java

core/java/com/google/census/CensusContext.java
core/java/com/google/census/CensusContextFactory.java
core_native/java/com/google/census/CensusContextFactoryImpl.java
core_native/java/com/google/census/CensusContextImpl.java

This will allow us to add methods without breaking existing implementations. Fixes issue #6.

Converts CensusContext, CensusContext.Builder, and CensusContextFactory into abstract classes.

---

.gitmodules
.travis.yml
core/java/com/google/census/CensusContext.java
core/java/com/google/census/CensusScope.java
core/java/com/google/census/MetricMap.java
core/java/com/google/census/Provider.java
core/javatests/com/google/census/CensusScopeTest.java
core/javatests/com/google/census/MetricMapTest.java
core/javatests/com/google/census/ProviderTest.java
core/pom.xml
core_native/java/com/google/census/CensusContextFactoryImpl.java
core_native/java/com/google/census/CensusContextImpl.java
core_native/java/com/google/census/CensusSerializer.java
core_native/pom.xml
examples/java/com/google/census/CensusRunner.java
pom.xml

This PR includes #2, because it uses the Maven build files to build with Java 6 and 7 in .travis.yml.

Makes census-java compatible with Java 6

---

BUILD
core/java/com/google/census/MetricMap.java
core/java/com/google/census/RpcConstants.java

This fixes #13. Another way to document methods that can return null is to add a new Nullable class to census-core.

Removes dependency on guava from census-core.

---

.travis.yml
core/java/com/google/census/MetricMap.java
core/pom.xml
core_native/pom.xml

This PR also fixes an existing warning and creates a separate build profile for Java 6.  The Java 6 profile skips the FindBugs check, which requires Java 7.

Runs Maven FindBugs plugin.

---

.travis.yml
checkstyle_custom_checks.xml
core/java/com/google/instrumentation/stats/RpcConstants.java
core/pom.xml
core_impl/pom.xml

This commit runs Checkstyle with two separate configurations, Google's Java style guide and a configuration file within the repository.

Checks for unused imports with Checkstyle.

---

core/java/com/google/instrumentation/stats/StatsContext.java
core/java/com/google/instrumentation/stats/StatsContextFactory.java
core/java/com/google/instrumentation/stats/StatsManager.java
core/javatests/com/google/instrumentation/stats/StatsContextFactoryTest.java
core/javatests/com/google/instrumentation/stats/StatsContextTest.java
core_impl/java/com/google/instrumentation/stats/StatsContextFactoryImpl.java
core_impl/java/com/google/instrumentation/stats/StatsContextImpl.java
core_impl/java/com/google/instrumentation/stats/StatsSerializer.java

If we decide to go with this change, there will be a dual change to deserialize to take an InputStream rather than a ByteBuffer.

Changes serialize() to take an OutputStream as a parameter.

---

core/java/com/google/instrumentation/common/NonThrowingCloseable.java

This helps with support for try-with-resource idiom.
Sample use case:
try (NonThrowingAutoCloseable ctx = tryEnter()) {
...
}

Add an interface that extends Closeable which cannot throw a checked exception.

---

core/java/com/google/instrumentation/common/Provider.java

1. Log impl loading results.
2. Fall back to default only if class not found, which is considered a
normal case.  If the class does exist, it is intended to be loaded
successfuly, thus other exceptions should be treated as error and thrown
to the caller.

Improve error handling in Provider.

---

core/java/com/google/instrumentation/stats/RpcConstants.java

These measurements allow monitoring the number of active RPCs.
/cc @zhangkun83 @dinooliva

Adds /rpc/server/started_count and /rpc/server/finished_count measurements.

---

core/java/com/google/instrumentation/stats/View.java

These accessor methods need to be public for external code to properly serialize Views.

Make View.getStart() and View.getEnd() public

---

.travis.yml
WORKSPACE
pom.xml

This change also requires downgrading truth to 0.30.
See https://github.com/grpc/grpc-java/issues/2688#issuecomment-280205113 .  I tested with multiple `guava` versions by adding a Maven property for the version, because I couldn't find a way to specify the version of a dependency on the command line.  Let me know if there is a better way to test multiple versions.
/cc @zhangkun83 @dinooliva

Downgrades default guava version to 19.0, and tests with guava 19.0, 20.0, and 21.0.

---

BUILD
core/src/main/java/com/google/instrumentation/common/Timestamp.java
core/src/main/java/com/google/instrumentation/common/TimestampFactory.java
core/src/main/java/com/google/instrumentation/trace/SpanFactory.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/common/TimestampFactoryTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java

Default implementation uses System#currentTimeMillis.
Add a way to provide other implementation using java8.
Remove the Tracer#timeNow.

Add a default implementation for TimestampFactory.

---

core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/main/java/com/google/instrumentation/trace/SpanBuilder.java
core/src/main/java/com/google/instrumentation/trace/SpanFactory.java
core/src/main/java/com/google/instrumentation/trace/StartSpanOptions.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/StartSpanOptionsTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java
examples/src/main/java/com/google/instrumentation/trace/BasicContextTracing.java
examples/src/main/java/com/google/instrumentation/trace/BasicScopedTracing.java
examples/src/main/java/com/google/instrumentation/trace/BasicTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansContextTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansScopedTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansTracing.java

To avoid exponential increase in the number of startSpan[XXX] methods in the Tracer class.

Add a SpanBuilder class.

---

core/src/main/java/com/google/instrumentation/trace/ScopedSpanHandle.java
core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/main/java/com/google/instrumentation/trace/SpanBuilder.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java
examples/src/main/java/com/google/instrumentation/trace/BasicTracing.java
examples/src/main/java/com/google/instrumentation/trace/MultiSpansTracing.java

This is important because we want to discourage the usage of the Span and encourage the usage of ScopedSpan.
Now SpanBuild#startSpan is only for manual propagation and there is no confusion that the try-with-resources objects will interact with the Context and Span does not.

Remove the try-with-resources support for the Span.

---

.travis.yml

Guava 21 works only on java8. See https://github.com/google/guava/wiki/Release21.

Update travis to run guava 21 only for java8 

---

pom.xml

This change allows us to run google-java-format to automatically format the code. Followup PRs to format the code will be send after this gets merged.

Ignore SingleLineJavadoc validation until google_checks gets updated in checkstyle.

---

core/pom.xml
core_context_impl/pom.xml
core_impl/pom.xml
shared/pom.xml

These fields were the same as the parent pom.xml.

Remove redundant fields in pom.xml files.

---

.bazelrc

The Bazel upgrade caused another warning in the Protocol Buffers generated classes.

Fix build with Bazel 0.4.5.

---

benchmarks/pom.xml
core_impl/pom.xml
pom.xml
shared/pom.xml

Use the current version for dependencies between different internal packages.
Avoid generating javadocs for implementation packages.

Cleanup pom.xml in our implementation packages.

---

core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java

Remove forgotten method from a previous PR.
Add check for consistency between SpanContext sampled and RECORD_EVENTS.

Fix a bug in the Span where the returned options was not unmodifiable.

---

BUILD
CONTRIBUTING.md
README.md
benchmarks/pom.xml
core/pom.xml
core/src/main/java/com/google/instrumentation/stats/RpcConstants.java
core/src/main/java/com/google/instrumentation/stats/TagKey.java
core/src/main/java/com/google/instrumentation/stats/TagValue.java
core_impl/pom.xml
pom.xml

Now we only use "Census" for existing Protocol Buffer messages, Maven group IDs,
and Maven artifact IDs.

Remove all occurrences of "Census" from documentation.

---

.travis.yml
all/build.gradle
benchmarks/README.md
benchmarks/build.gradle
core/build.gradle
core_impl/build.gradle
examples/build.gradle
settings.gradle

Helps IDEs to have the same name as the main directory.

Change project name to be instrumentation-java.

---

build.gradle
core/src/main/java/com/google/instrumentation/trace/Annotation.java
core/src/main/java/com/google/instrumentation/trace/Attributes.java
core/src/main/java/com/google/instrumentation/trace/BlankSpan.java
core/src/main/java/com/google/instrumentation/trace/Link.java
core/src/main/java/com/google/instrumentation/trace/Span.java
core/src/test/java/com/google/instrumentation/trace/AnnotationTest.java
core/src/test/java/com/google/instrumentation/trace/AttributeValueTest.java
core/src/test/java/com/google/instrumentation/trace/AttributesTest.java
core/src/test/java/com/google/instrumentation/trace/BlankSpanTest.java
core/src/test/java/com/google/instrumentation/trace/HttpPropagationUtilTest.java
core/src/test/java/com/google/instrumentation/trace/LinkTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java

Change Span to accept Links and Annotations.
This change allows to expose later an interface to export SpanData without depending on protos which is mandatory when using Stackdriver tracer.

Add Annotation and Link as classes in the trace API.

---

examples/build.gradle
examples/src/main/java/com/google/instrumentation/examples/stats/StatsRunner.java
examples/src/main/java/com/google/instrumentation/examples/trace/BasicContextTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/BasicScopedTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/BasicTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansContextTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansScopedTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansTracing.java

Fix javadoc errors in examples.
Move all the examples in a different package than the implementation to avoid using (by mistake) package-protected methods that others cannot use.

Add build rule for examples to generate executable binaries.

---

core/src/main/java/com/google/instrumentation/stats/RpcConstants.java
core/src/test/java/com/google/instrumentation/stats/RpcConstantsTest.java

Update the name of measurement and view descriptors based on our new naming convention;
Add measurement and view descriptors for started/finished/request/response count on client and server;
Add unit tests for new descriptors.

Add measurement and view descriptors for client/server started/finished and res/req count.

---

CONTRIBUTING.md

@a-veitch suggested the initial guidelines, and I edited them to fit into a
section in CONTRIBUTING.md.

Adds Javadoc guidelines to CONTRIBUTING.md.

---

build.gradle

Helps IDEs to recognize the auto-generated files.

Gradle plugin making it easier/safer to use Java annotation processors

---

core/src/main/java/com/google/instrumentation/trace/EndSpanOptions.java
core/src/main/java/com/google/instrumentation/trace/SpanBuilder.java
core/src/main/java/com/google/instrumentation/trace/StartSpanOptions.java
core/src/test/java/com/google/instrumentation/trace/EndSpanOptionsTest.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/StartSpanOptionsTest.java

Until we have a better design on how are we going to support them we should not have this functionality in our public API.

Remove start/end timestamps from our public interface.

---

core/src/main/java/com/google/instrumentation/stats/Stats.java
core/src/main/java/com/google/instrumentation/stats/StatsManager.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsContextFactoryImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImpl.java
examples/src/main/java/com/google/instrumentation/examples/stats/StatsRunner.java

Previously, the `Stats` class used reflection to instantiate subclasses for both
`StatsManager` and `StatsContextFactory`.  That design forced the `StatsManager`
and `StatsContextFactory` subclasses to only interact through their public APIs.
This commit changes `Stats` so that it only instantiates `StatsManager`.  The
`StatsManager` instance then creates the one `StatsContextFactory` instance by
calling a constructor.  The main difference is that `StatsManager` now knows
what subclass of `StatsContextFactory` is in use, and all of the stats
implementation classes can interact through package-private methods.

Only load one stats class with reflection.

---

core/src/main/java/com/google/instrumentation/stats/MeasurementDescriptor.java
core/src/main/java/com/google/instrumentation/stats/MeasurementMap.java
core/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorTest.java
core/src/test/java/com/google/instrumentation/stats/MeasurementMapTest.java
core/src/test/java/com/google/instrumentation/stats/ViewDescriptorTest.java

We need to associate data with MeasurementDescriptors in several places in the
stats implementation.  For example, MeasurementMap maps MeasurementDescriptors
to recorded values.  Using MeasurementDescriptor as the key is not ideal,
because it is not obvious how the keys should be compared.  The keys could be
compared by name, since names are unique, or they could be compared by all
fields.
I think that we should always compare MeasurementDescriptors by name.  It is
more efficient, and it means that two MeasurementDescriptors with slightly
different descriptions won't be treated as distinct.  Having a separate key type
will make it clearer how the MeasurementDescriptors will be compared.
This commit just adds the class and doesn't change any existing APIs.

Adds a class to represent a MeasurementDescriptor name.

---

core/src/main/java/com/google/instrumentation/trace/SpanBuilder.java
core/src/main/java/com/google/instrumentation/trace/SpanFactory.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/trace/BlankSpanTest.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/StartSpanOptionsTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java

Reason is that this way we can ensure an order between events recorded in different spans from the same trace.
We will calculate the timestamp using delay since the start time of the initial Span in the trace in the process (root span or a span with remote parent).

Roll back the change to have different factory methods for spans and spans with remote parent.

---

core_impl/src/main/java/com/google/instrumentation/common/DisruptorEventQueue.java
core_impl/src/main/java/com/google/instrumentation/common/EventQueue.java
core_impl/src/main/java/com/google/instrumentation/common/EventQueueEntry.java
core_impl/src/main/java/com/google/instrumentation/common/SimpleEventQueue.java
core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsContextImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/SupportedViews.java
core_impl/src/test/java/com/google/instrumentation/common/DisruptorEventQueueTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java

Changes in this PR:
- Store `StatsContextImpl`'s map of tags in an unmodifiable map so that it is safe to access from other classes.
- Add a field for an event queue to `StatsManagerImpl`.
- Create an `EventQueue` interface to allow testing with a simple `EventQueue`.  I renamed the original `EventQueue` class to `DisruptorEventQueue`.
- Add a `StatsEvent` class that can be added to the `EventQueue`.
- Add a record method to `StatsManagerImpl`.  It doesn't do anything yet.
It is much easier to review the individual commits, because git didn't follow the rename of `EventQueue`.
/cc @a-veitch @dinooliva @bogdandrutu

Start implementing StatsManagerImpl.record(...).

---

.travis.yml

The Gradle build command is the command that should determine whether the build
succeeds or fails, so it should go in the "script" section.  Failed commands in
the "install" section mark the build as "Errored".

Move Gradle build from "install" to "script" section of .travis.yml.

---

.travis.yml
build.gradle
core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
gradle/errorprone/experimental_suggestions

This includes RemoveUnusedImports. I excluded PrivateConstructorForUtilityClass
because there were too many warnings in the examples directory.

Enable Error Prone experimental suggestions.

---

core/src/main/java/com/google/instrumentation/common/TimestampFactory.java
core/src/main/java/com/google/instrumentation/internal/Provider.java
core/src/main/java/com/google/instrumentation/stats/Stats.java
core/src/main/java/com/google/instrumentation/trace/Tracing.java
core/src/test/java/com/google/instrumentation/internal/ProviderTest.java

Provider is shared by all of the instrumentation packages, but it isn't part of
the API.

Move Provider to internal package.

---

core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/MutableView.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsContextFactoryImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsContextImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImpl.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsSerializer.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsContextFactoryTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java

This just adds a little more type-safety.  ~~The first commit is from #236.~~  I don't want this PR to conflict with #233, so I will wait to merge it.

Use StatsContext, TagKey, and TagValue types in more places.

---

benchmarks/src/jmh/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplBenchmark.java
core/src/main/java/com/google/instrumentation/trace/SpanContext.java
core/src/main/java/com/google/instrumentation/trace/SpanFactory.java
core/src/main/java/com/google/instrumentation/trace/StartSpanOptions.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core/src/test/java/com/google/instrumentation/trace/LinkTest.java
core/src/test/java/com/google/instrumentation/trace/SamplersTest.java
core/src/test/java/com/google/instrumentation/trace/SpanBuilderTest.java
core/src/test/java/com/google/instrumentation/trace/SpanContextTest.java
core/src/test/java/com/google/instrumentation/trace/SpanTest.java
core/src/test/java/com/google/instrumentation/trace/TracerTest.java
core/src/test/java/com/google/instrumentation/trace/TracingTest.java
core_impl/src/main/java/com/google/instrumentation/trace/BinaryPropagationHandlerImpl.java
core_impl/src/test/java/com/google/instrumentation/trace/BinaryPropagationHandlerImplTest.java
core_impl/src/test/java/com/google/instrumentation/trace/SpanDataTest.java

* Change visibility for SpanFactory and StartSpanOptions to allow testing and implementation. Add a public SpanContext.create. Make SpanFactory methods protected and StartSpanOptions getters public.
(cherry picked from commit 473af8e4205feac693b5f40d91824e0c5102b849)

Change visibility for SpanFactory and StartSpanOptions (#240)

---

core/src/main/java/com/google/instrumentation/internal/StringUtil.java
core/src/main/java/com/google/instrumentation/stats/MeasurementDescriptor.java
core/src/main/java/com/google/instrumentation/stats/TagKey.java
core/src/main/java/com/google/instrumentation/stats/TagValue.java
core/src/test/java/com/google/instrumentation/internal/StringUtilTest.java
core/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorTest.java
core/src/test/java/com/google/instrumentation/stats/TagKeyTest.java
core/src/test/java/com/google/instrumentation/stats/TagValueTest.java

This will allow the class to be used by multiple packages.
This commit was part of #219.

Move StringUtil into the "internal" package.

---

core/src/main/java/com/google/instrumentation/trace/TraceOptions.java

(cherry picked from commit cfe26b220b4731b3c95fea03058131db565a615d)

Make the TraceOptions Builder methods public for testing. (#247)

---

.travis.yml

We have been using the git history check for a few weeks, so I think it's safe
to enforce the check.

Move git history check out of "allow_failures" in .travis.yml.  Fixes #225.

---

core/build.gradle

Because it's not needed at runtime.  With `compile`, auto-value is downloaded by downstream users, which triggers warnings like `warning: No processor claimed any of these annotations: ` with error-prone compiler (grpc/grpc-java/pull/2938). With `compileOnly`, auto-value is not downloaded by downstream users.

Make auto-value compileOnly dependency.

---

core/build.gradle

Because it's not needed at runtime.  Having it in runtime classpath
triggers warnings like `warning: No processor claimed any of these
annotations: ` with error-prone compiler (grpc/grpc-java/pull/2938)
(cherry picked from commit a19c013692a0c2a61652da67add51d10ba81ebf1)

Make auto-value compileOnly dependency. (#254)

---

core/src/main/java/com/google/instrumentation/internal/MillisClock.java
core/src/main/java/com/google/instrumentation/internal/TestClock.java
core/src/test/java/com/google/instrumentation/internal/TestClockTest.java

The two implementations are in the `internal` package for now.

Add Clock implementations for Java 6/7 and for testing.

---

core_impl_android/build.gradle
core_impl_java_8/build.gradle

Android is moving to API-14:
https://android-developers.googleblog.com/2016/11/google-play-services-and-firebase-for-android-will-support-api-level-14-at-minimum.html

Update animalsniffer signature requires

---

core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImplBase.java
core_impl/src/main/java/com/google/instrumentation/stats/ViewManager.java

Classes in the StatsManager class hierarchy should just specify the classes
that are used for different stats implementations.  This commit moves all
stats-handling logic out of StatsManagerImplBase into a new class, ViewManager.

Simplify StatsManager by delegating stats operations to new a class, ViewManager.

---

core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/MutableView.java
core_impl/src/main/java/com/google/instrumentation/stats/ViewManager.java
core_impl/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMapTest.java

Two main commits:
Previously, ViewManager.registerView() called
MeasurementDescriptorToViewMap.getView(...) followed by
MeasurementDescriptorToViewMap.putView(...) to insert a view only if it was not
present.  There was no locking, so the view could be created multiple times.
This commit refactors putView so that it covers the full transaction on the
underlying multimap.  It creates an empty MutableView if the view is not present
and inserts it into the multimap.
MeasurementDescriptorToViewMap previously used a SynchronizedMultimap for
synchronization of its Multimap.  However, every method ended up needing to
access the Multimap within a synchronized block anyway, because the Multimap's
values were not synchronized.  It is simpler to just use a HashMultimap and
synchronize on the whole …

MeasurementDescriptorToViewMap synchronization

---

core/src/main/java/com/google/instrumentation/stats/ViewDescriptor.java
core/src/test/java/com/google/instrumentation/stats/ViewDescriptorTest.java
core_impl/src/main/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMap.java
core_impl/src/main/java/com/google/instrumentation/stats/StatsManagerImplBase.java
core_impl/src/main/java/com/google/instrumentation/stats/ViewManager.java
core_impl/src/test/java/com/google/instrumentation/stats/MeasurementDescriptorToViewMapTest.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsManagerImplTest.java

This class can be used to query Views, since ViewDescriptor names must be
unique. This commit also prevents a view from being registered if it has the
same name as an existing view but is not the same view.
/cc @dinooliva @bogdandrutu @a-veitch

Add a class to represent a ViewDescriptor name.

---

core/src/main/java/com/google/instrumentation/trace/TraceExporter.java
core/src/test/java/com/google/instrumentation/trace/TraceExporterTest.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansContextTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansScopedTracing.java
examples/src/main/java/com/google/instrumentation/examples/trace/MultiSpansTracing.java

Change the interface of LoggingServiceHandler to enforce that maximum one instance is registered at any moment.

Change examples to use the logging service exporter.

---

core/src/main/java/com/google/instrumentation/stats/ContextUtils.java
core/src/main/java/com/google/instrumentation/stats/StatsContext.java
core/src/test/java/com/google/instrumentation/stats/ContextUtilsTest.java

This class is similar to [trace/ContextUtils.java](https://github.com/google/instrumentation-java/blob/master/core/src/main/java/com/google/instrumentation/trace/ContextUtils.java), to provide minimal util methods for StatsContext to interact with gRPC Context.
I made all the util methods package-private, and I plan to expose them via new APIs in StatsContextFactory.
/cc @bogdandrutu @sebright

Implement minimal functionality for StatsContext to interact with gRPC Context.

---

benchmarks/build.gradle
benchmarks/src/jmh/java/com/google/instrumentation/trace/RecordTraceEventsNonSampledSpanBenchmark.java
benchmarks/src/jmh/java/com/google/instrumentation/trace/RecordTraceEventsSampledSpanBenchmark.java
benchmarks/src/jmh/java/com/google/instrumentation/trace/StartEndSpanBenchmark.java

Benchmarks ran with https://github.com/google/instrumentation-java/pull/296 (mean values)
BinaryPropagationHandlerImplBenchmark.fromBinaryValueSpanContext      66.611 ±  1.568  ns/op
BinaryPropagationHandlerImplBenchmark.toBinaryValueSpanContext          67.977 ±  2.524  ns/op
BinaryPropagationHandlerImplBenchmark.toFromBinarySpanContext           146.850 ± 39.152  ns/op
RecordTraceEventsNonSampledSpanBenchmark.addAnnotation                  55.014 ±  1.872  ns/op
RecordTraceEventsNonSampledSpanBenchmark.addLink                             46.806 ±  1.752  ns/op
RecordTraceEventsNonSampledSpanBenchmark.addNetworkEvent             49.202 ±  1.996  ns/op
RecordTraceEventsSampledSpanBenchmark.addAnnotation                         79.445 ± 40.390  ns/op …

Add benchmarks for start/end span and record trace events.

---

core/src/main/java/com/google/instrumentation/stats/StatsContextFactory.java
core/src/main/java/com/google/instrumentation/trace/Tracer.java
core_impl/src/test/java/com/google/instrumentation/stats/StatsContextFactoryTest.java

Expose the util methods in PR https://github.com/google/instrumentation-java/pull/299 to public APIs in StatsContextFactory. This is similar to [Tracer](https://github.com/google/instrumentation-java/blob/master/core/src/main/java/com/google/instrumentation/trace/Tracer.java#L91), except that currently we don't have no-op objects for Stats (Issue https://github.com/google/instrumentation-java/issues/215), and `getCurrentStatsContext()` may return null (vesus `getCurrentSpan()` returns a no-op). I may need to update `getCurrentStatsContext()` after we came to an agreement on that issue.
/cc @zhangkun83

Add getCurrentStatsContext() and withStatsContext() API to StatsContextFactory.

---

checkstyle.xml

This rule conflicts with Error Prone's exhaustiveness checking.  When all enum
cases are handled in a switch block, Error Prone doesn't allow a "default" case,
but Checkstyle always requires a "default" case.
______________________
I fixed the conflict this way because I thought the Error Prone warning was more useful.  Is that okay?
/cc @dinooliva @a-veitch 
EDIT: I needed this for #276.

Disable Checkstyle's MissingSwitchDefault warning.

---

settings.gradle

No longer override projectDirs now that the gradle subproject names match the directory names.

No longer override projectDirs.

---

core/src/main/java/com/google/instrumentation/trace/TraceExporter.java

* Rename the old api for adding span names.

Add API to remove a span name from the list of the span names from which the library collects samples.

---

api/src/main/java/io/opencensus/trace/TraceComponent.java
api/src/main/java/io/opencensus/trace/Tracing.java
api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
api/src/main/java/io/opencensus/trace/propagation/PropagationComponent.java
api/src/test/java/io/opencensus/trace/TraceComponentTest.java
api/src/test/java/io/opencensus/trace/TracingTest.java
api/src/test/java/io/opencensus/trace/propagation/BinaryFormatTest.java
api/src/test/java/io/opencensus/trace/propagation/PropagationComponentImplTest.java
api/src/test/java/io/opencensus/trace/propagation/PropagationComponentTest.java
benchmarks/src/jmh/java/io/opencensus/trace/propagation/BinaryPropagationImplBenchmark.java
core_impl/src/main/java/io/opencensus/trace/TraceComponentImplBase.java
core_impl/src/main/java/io/opencensus/trace/propagation/BinaryFormatImpl.java
core_impl/src/main/java/io/opencensus/trace/propagation/PropagationComponentImpl.java
core_impl/src/test/java/io/opencensus/trace/TraceComponentImplBaseTest.java
core_impl/src/test/java/io/opencensus/trace/propagation/BinaryFormatImplTest.java
core_impl/src/test/java/io/opencensus/trace/propagation/PropagationComponentImplTest.java
core_impl_java/src/test/java/io/opencensus/trace/TracingTest.java

This change allows the library to add support for multiple formats without changing the Tracing class, and without polluting the main package (io.opencensus).
PR summary:
* Rename BinaryPropagationHandler -> BinaryFormat and move it to propagation package.
* Add a PropagationComponent as a container for all format implementations.
* Change Tracing/TraceComponent to return PropagationComponent instead of directly the BinaryFormat.
* Move benchmarks for BinaryFormat in propagation package.

Create a new package for all supported propagations.

---

api/src/main/java/io/opencensus/internal/package-info.java
api/src/main/java/io/opencensus/trace/export/InProcessDebuggingHandler.java
api/src/main/java/io/opencensus/trace/export/SpanData.java
api/src/main/java/io/opencensus/trace/export/SpanExporter.java
api/src/test/java/io/opencensus/trace/export/ExportComponentTest.java
api/src/test/java/io/opencensus/trace/export/SpanDataTest.java
core_impl/src/main/java/io/opencensus/trace/SpanImpl.java
core_impl/src/main/java/io/opencensus/trace/StartEndHandlerImpl.java
core_impl/src/main/java/io/opencensus/trace/TraceComponentImplBase.java
core_impl/src/main/java/io/opencensus/trace/export/ExportComponentImpl.java
core_impl/src/main/java/io/opencensus/trace/export/SpanExporterImpl.java
core_impl/src/test/java/io/opencensus/trace/SpanFactoryImplTest.java
core_impl/src/test/java/io/opencensus/trace/SpanImplTest.java
core_impl/src/test/java/io/opencensus/trace/TraceComponentImplBaseTest.java
core_impl/src/test/java/io/opencensus/trace/export/ExportComponentImplTest.java
core_impl/src/test/java/io/opencensus/trace/export/SpanExporterImplTest.java
core_impl_android/src/test/java/io/opencensus/trace/TraceComponentImplTest.java
core_impl_java/src/test/java/io/opencensus/trace/TracingTest.java

More cleanups included:
* Add internal annotation to all implementation classes.
* Fix javadoc export for implementation (avoid exporting io.opencensus.internal).

Move SpanData to export package. Move implementation of export package class to export package.

---

contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentBuilderListener.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java

Add a skeleton Java agent, which hooks up Bytebuddy, but doesn't do anything yet besides logging. Also add it to the build process, bundling the required classes and dependencies in a single agent JAR file.

Add a skeleton Java agent

---

.travis.yml

These settings are no longer required, because we aren't using Bazel.
This commit fixes the build after Travis updated the environment: https://travis-ci.org/census-instrumentation/opencensus-java/jobs/247751414
/cc @dinooliva @bogdandrutu

Remove "sudo: required" and "dist: trusty" from .travis.yml.

---

api/src/main/java/io/opencensus/trace/SpanBuilder.java
api/src/main/java/io/opencensus/trace/Tracer.java
api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
api/src/test/java/io/opencensus/trace/TracerTest.java
benchmarks/src/jmh/java/io/opencensus/trace/RecordTraceEventsNonSampledSpanBenchmark.java
benchmarks/src/jmh/java/io/opencensus/trace/RecordTraceEventsSampledSpanBenchmark.java
benchmarks/src/jmh/java/io/opencensus/trace/StartEndSpanBenchmark.java
benchmarks/src/jmh/java/io/opencensus/trace/propagation/BinaryPropagationImplBenchmark.java
examples/src/main/java/io/opencensus/examples/trace/MultiSpansContextTracing.java
examples/src/main/java/io/opencensus/examples/trace/MultiSpansScopedTracing.java
examples/src/main/java/io/opencensus/examples/trace/MultiSpansTracing.java
impl_core/src/main/java/io/opencensus/trace/SpanBuilderImpl.java
impl_core/src/main/java/io/opencensus/trace/TracerImpl.java
impl_core/src/test/java/io/opencensus/trace/SpanBuilderImplTest.java
impl_core/src/test/java/io/opencensus/trace/TracerImplTest.java

This is a followup after https://github.com/census-instrumentation/opencensus-java/pull/380.
* Rollback the change to not accept null for remote parent. It is better for our users to pass null there in case no context received or unable to parse.
* Rename the spanBuilder method that accepts an explicit parent to spanBuilderWithParent, this is consistent with spanBuilderWithRemoteParent.
* NoopSpanBuilder changed to have factory methods.
* Update SpanBuilderImpl factory methods to be consistent with NoopSpanBuilder.

Change tracer API names to create a SpanBuilder.

---

core/src/main/java/io/opencensus/stats/Measure.java
core/src/main/java/io/opencensus/stats/MeasureMap.java
core/src/main/java/io/opencensus/stats/Measurement.java
core/src/main/java/io/opencensus/stats/RpcMeasurementConstants.java
core/src/test/java/io/opencensus/stats/MeasureMapTest.java
core/src/test/java/io/opencensus/stats/MeasureTest.java
core/src/test/java/io/opencensus/stats/ViewDescriptorTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java
examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java

Rename to follow the name convention on Tag/TagKey:
- DoubleMeasure -> MeasureDouble
- LongMeasure -> MeasureLong
- DoubleMeasurement -> MeasurementDouble
- LongMeasure -> MeasurementLong 
This PR is built on top of https://github.com/census-instrumentation/opencensus-java/pull/405, I'll rebase this PR once I've merged PR https://github.com/census-instrumentation/opencensus-java/pull/405.

Rename Measure and Measurement subclasses.

---

api/src/main/java/io/opencensus/common/Function.java
api/src/main/java/io/opencensus/common/Functions.java
api/src/main/java/io/opencensus/trace/AttributeValue.java
api/src/test/java/io/opencensus/common/FunctionsTest.java
api/src/test/java/io/opencensus/trace/AttributeValueTest.java

Two commits:
AttributeValue.match takes four function arguments: functions for handling
String, Long, and Boolean values, and a function for handling any new types
that could be added in the future.
_____________________________________________
The `match` pattern is similar to the one used in #323 and #396.
/cc @dinooliva @songy23

Refactor AttributeValue to use a "match" method.

---

core/src/main/java/io/opencensus/stats/Measure.java
core/src/main/java/io/opencensus/stats/RpcMeasureConstants.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java

Based on our conversation, I think MeasureLong is needed for v0.1. I've changed a few RPC constants to use MeasureLong and add TODO to support record long values (which will be implemented in a separate PR),

Change *_COUNT RPC constants to MeasureLong, add TODO to support long

---

core/src/main/java/io/opencensus/stats/RpcViewConstants.java
core/src/main/java/io/opencensus/stats/View.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/ViewManagerImpl.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java

The View `getName` and factory methods had different versions for handling names as type `String` and `View.Name`.  This PR removes the String versions, since they are no longer needed for backwards compatibility.  View.Name can be used to look up views when only the name is known.

Remove View 'getName' and factory methods that use Strings for view name.

---

core/src/main/java/io/opencensus/stats/CurrentTagsUtils.java
core/src/main/java/io/opencensus/stats/StatsContextFactory.java
core/src/main/java/io/opencensus/tags/unsafe/ContextUtils.java
core/src/test/java/io/opencensus/stats/CurrentTagsUtilsTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextFactoryTest.java

This commit starts refactoring the stats io.grpc.Context key so that it can be
used to access a TagContext.  It also organizes the classes that interact with
the Context to be more similar to the tracing package.
The commit renames the constant from STATS_CONTEXT_KEY to TAG_CONTEXT_KEY and
moves it from io.opencensus.stats.ContextUtils to
io.opencensus.tags.unsafe.ContextUtils.  It also renames the
io.opencensus.stats.ContextUtils class to CurrentTagsUtils and makes it
package-private, since the only public member was the Context key.  The Context
key still has type Context.Key<StatsContext>, for now.

Move stats Context key to io.opencensus.tags.unsafe package.

---

api/src/main/java/io/opencensus/common/NonThrowingCloseable.java
api/src/main/java/io/opencensus/common/Scope.java
api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
api/src/main/java/io/opencensus/trace/ScopedSpanHandle.java
api/src/main/java/io/opencensus/trace/SpanBuilder.java
api/src/main/java/io/opencensus/trace/Tracer.java
api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java
api/src/test/java/io/opencensus/trace/ScopedSpanHandleTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
core/src/main/java/io/opencensus/stats/CurrentTagsUtils.java
core/src/main/java/io/opencensus/stats/StatsContextFactory.java
core/src/test/java/io/opencensus/stats/CurrentTagsUtilsTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextFactoryTest.java
examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java
examples/src/main/java/io/opencensus/examples/trace/MultiSpansContextTracing.java
examples/src/main/java/io/opencensus/examples/trace/MultiSpansScopedTracing.java

This interface allows users to write a shorter, more descriptive type name when
using scoped tags or spans.

Add Scope as interface for Closeables that work with current context.

---

api/src/main/java/io/opencensus/common/Scope.java

This reverts commit 969f95088a3a1e490460ad53931b24e46e6ca907.
The close() override is necessary to suppress a deprecation warning from
NonThrowingCloseable.close().

Revert "Remove Scope.close() method."

---

build.gradle
contrib/agent/README.md
contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/ContextStrategyImpl.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/GrpcContextStrategy.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextManager.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextStrategy.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/ExecutorInstrumentationTest.java

This change adds the required plumbing for accessing/manipulating the
context from the instrumented code. This completes the underlying infrastructure
for the executor instrumentation, which is also included in this change.

Add automatic context propagation for Executors.

---

impl_core/src/main/java/io/opencensus/trace/StartEndHandlerImpl.java
impl_core/src/test/java/io/opencensus/trace/export/SpanExporterImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/459

Fix a bug in the implementation that causes all Spans with RECORD_EVENTS options to also be exported.

---

core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/stats/StatsComponent.java
core/src/main/java/io/opencensus/stats/StatsRecorder.java
core/src/test/java/io/opencensus/stats/StatsRecorderTest.java
core/src/test/java/io/opencensus/stats/StatsTest.java

The no-op StatsComponent returns a no-op StatsRecorder and a null ViewManager.
The StatsRecorder is non-null so that code that only records stats doesn't need
to check for null.  NoopStatsRecorder.record(...) simply ignores the stats.
However, the ViewManager is null to avoid returning misleading empty results
from NoopStatsComponent.getViewManager().getView(...).

Add a no-op StatsComponent to return when no implementation is available.

---

api/src/main/java/io/opencensus/common/Functions.java
api/src/test/java/io/opencensus/common/FunctionsTest.java

The function can be used for all default cases in calls to "match" functions in
the API library, since a version mismatch isn't possible, and the default case
cannot occur in "match" functions that take all subclasses.

Add a function that always throws an AssertionError.

---

.travis.yml

The Java 7 build job started failing when Travis switched to Ubuntu Trusty.
This commit sets the version back to Precise to fix the build while we determine
how to upgrade or decide to remove the Java 7 job.
/cc @bogdandrutu @dinooliva

Work around Java 7 Travis build failure by specifying "dist: precise".

---

.travis.yml

Work around Java 7 Travis build failure by specifying "dist: precise".
The Java 7 build job started failing when Travis switched to Ubuntu Trusty.
This commit sets the version back to Precise to fix the build while we determine
how to upgrade or decide to remove the Java 7 job.
(cherry picked from commit 93ca8e0471eb3b5d9f05c53d59edde6c86cb4be5)
____________________________________________________
/cc @bogdandrutu @dinooliva 
This PR applies #474 to the v0.5.x branch.

Fix Travis build on the v0.5.x branch

---

core/src/main/java/io/opencensus/stats/BucketBoundaries.java
core/src/main/java/io/opencensus/stats/RpcViewConstants.java
core/src/main/java/io/opencensus/stats/View.java
core/src/main/java/io/opencensus/stats/ViewData.java
core/src/test/java/io/opencensus/stats/RpcViewConstantsTest.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/stats/StatsManager.java
core_impl/src/test/java/io/opencensus/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/stats/StatsContextTest.java
core_impl/src/test/java/io/opencensus/stats/ViewManagerImplTest.java

This PR is the API level changes.
- Updated `View` and `ViewData` based on our new data model. 
- Removed subclasses `DistributionView` and `IntervalView`, `DistributionViewData` and `IntervalViewData`, in favor of more generic `View` and `ViewData`.
- Comment out affected implementation and tests. Changes on implementations will be made after API changes.

Refactor to use more generic View and ViewData.

---

core/src/main/java/io/opencensus/tags/TagContextFactory.java
core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core/src/test/java/io/opencensus/tags/TagsTest.java
core_impl/src/main/java/io/opencensus/tags/TagContextFactoryImpl.java
core_impl/src/main/java/io/opencensus/tags/TagsComponentImplBase.java
core_impl_android/src/main/java/io/opencensus/tags/TagsComponentImplLite.java
core_impl_android/src/test/java/io/opencensus/tags/TagsTest.java
core_impl_java/src/main/java/io/opencensus/tags/TagsComponentImpl.java
core_impl_java/src/test/java/io/opencensus/tags/TagsTest.java

TagsComponent is an abstract class that holds the implementations for different
parts of the 'tags' package.  The class currently has one field, which is a
skeleton for a new TagContextFactory class.  It allows the implementation
library to determine the implementation of TagContext, which could be important
for performance.
This commit also adds a Tags class, which instantiates the TagsComponent with
reflection.  The design is very similar to the 'stats' package.  Tags
corresponds to the Stats class, and TagsComponent corresponds to StatsComponent.
___________________________________________________________________
This PR is part of #464.

Add Tags and TagsComponent classes to the 'tags' package.

---

core/src/main/java/io/opencensus/tags/TagContextFactory.java
core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core/src/test/java/io/opencensus/tags/TagsTest.java

The no-op TagsComponent will allow users to record stats without checking for
null.  If no implementation is available, the tagging operations should be very
fast, because the no-op TagsComponent contains a no-op TagContextFactory, which
will only ever return an empty TagContext.
__________________________________________
~~This PR contains #465, so only the last commit is new.~~

Add a no-op TagsComponent to return when no implementation is available.

---

core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core_impl/src/main/java/io/opencensus/impl/tags/TagContextFactoryImpl.java
core_impl/src/main/java/io/opencensus/impl/tags/TagsComponentImplBase.java
core_impl_android/src/main/java/io/opencensus/impl/tags/TagsComponentImplLite.java
core_impl_android/src/test/java/io/opencensus/impl/tags/TagsTest.java
core_impl_java/src/main/java/io/opencensus/impl/tags/TagsComponentImpl.java
core_impl_java/src/test/java/io/opencensus/impl/tags/TagsTest.java

This change will ensure that the 'tags' implementation only accesses the API
classes through their public API.  That will help us maintain backwards
compatibility.
EDIT: We should probably also put the core, Java 7/8, and Android implementation classes in different packages before the release.

Move tagging implementation classes into io.opencensus.impl.tags. (part of #379)

---

core/src/main/java/io/opencensus/stats/BucketBoundaries.java
core_impl/src/main/java/io/opencensus/stats/MutableAggregation.java
core_impl/src/test/java/io/opencensus/stats/MutableAggregationTest.java

This PR is implementation level changes.
MutableAggregation is the implementation class that does the actual recording and updates the corresponding summary stats (count, sum, etc.), similar to [MutableDistribution](https://github.com/census-instrumentation/opencensus-java/blob/master/core/src/main/java/io/opencensus/stats/MutableDistribution.java) in our previous design.

Add MutableAggregation and tests.

---

core_impl/src/main/java/io/opencensus/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/stats/MutableViewData.java

This PR is implementation level changes.
Modify the existing implementation to work with our new stats APIs and data models. As before, interval-based views and long measures are not supported at this time.

Modify stats-impl to use the new APIs and data models

---

contrib/agent/build.gradle

This is meant to make the build script easier to read. Otherwise, it's a no-op.

Move everything related to integration tests to its own section in the build script.

---

core/src/main/java/io/opencensus/stats/Aggregation.java
core_impl/src/main/java/io/opencensus/stats/MutableAggregation.java

Using `SumOfSquaredDeviation` will be more align with StackDriver APIs: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TypedValue, but users might also want to get standard deviation directly.

Add TODOs on whether we want to change StdDev.

---

api/src/main/java/io/opencensus/internal/StringUtil.java
core/src/main/java/io/opencensus/tags/TagKey.java
core/src/main/java/io/opencensus/tags/TagValueString.java

This commit splits tag validation into separate methods for handling tag keys
and values, since keys and values may need different restrictions on their input
Strings.  There should be no change in behavior.
/cc @dinooliva

Refactor tag validation code.

---

build.gradle
contrib/agent/build.gradle
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationTest.java
contrib/agent/src/jmh/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationBenchmark.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextStrategyImpl.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/Instrumenter.java

This reduces the coupling between AgentMain and the plugins (well, one ATM, but there should be more eventually).

Introduce a simplistic plug-in mechanism.

---

contrib/zpages/README.md
contrib/zpages/build.gradle
contrib/zpages/src/main/java/io/opencensus/zpages/TracezHttpHandler.java
contrib/zpages/src/main/java/io/opencensus/zpages/TracezPageFormatter.java
contrib/zpages/src/test/java/io/opencensus/zpages/TracezHttpHandlerTest.java
contrib/zpages/src/test/java/io/opencensus/zpages/TracezPageFormatterTest.java
examples/build.gradle
examples/src/main/java/io/opencensus/examples/zpages/Tester.java
examples/src/main/java/io/opencensus/examples/zpages/ZPagesTester.java
settings.gradle

Debugging page that displays data about all the active Spans and samples based on latency and errors. Used to debug real-time problems.

Add initial implementation of the tracez page.

---

build.gradle

Website: https://github.com/ben-manes/gradle-versions-plugin
Example run:
```
./gradlew dependencyUpdates
> Configure project :opencensus-agent
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
at build_yybdm0czmtrzmvw9xebzxag0.run(/usr/local/google/home/stschmidt/instrumentation-java/all/build.gradle:29)
> Task :dependencyUpdates
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- …
```

Add the Gradle Versions plugin.

---

core/src/main/java/io/opencensus/tags/unsafe/ContextUtils.java
core/src/test/java/io/opencensus/tags/CurrentTagContextUtilsTest.java
core/src/test/java/io/opencensus/tags/unsafe/ContextUtilsTest.java

This commit also adds tests for io.opencensus.tags.unsafe.ContextUtils.

Give TAG_CONTEXT_KEY a default value (an empty TagContext).

---

core/src/main/java/io/opencensus/stats/StatsRecorder.java
core/src/test/java/io/opencensus/stats/NoopStatsRecorderTest.java

~~Two commits:~~
~~#### Give TAG_CONTEXT_KEY a default value (an empty TagContext).~~
This `record` overload uses the current TagContext.  I also split StatsRecorderTest into StatsRecorderTest and NoopStatsRecorderTest.

Implement StatsRecorder.record(MeasureMap).

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java

This was useful during initial development, but is now annoying as info-level logs end up on stdout, assuming the default j.u.l. configuration.

Reduce log level to avoid spamming stdout.

---

contrib/agent/src/jmh/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationBenchmark.java

This is pretty naive. I currently don't have a good idea how to improve it, and don't want to sink too much time on it.

Add a naive JMH benchmark for ThreadInstrumentation.

---

contrib/agent/README.md
contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/zpages/README.md
examples/build.gradle
settings.gradle

This change renames the "contrib" projects so that their names (and their Maven artifactIds) consistently start with "opencensus-contrib-". We could have different project names and artifactIds, too, but I think it's not worth the potential confusion.
Fixes https://github.com/census-instrumentation/opencensus-java/issues/549.

Rename contrib projects.

---

.travis.yml

Because osx builds are very slow scheduled mark osx as not required and enable fast_finish which will mark the build as finished when all the required builds are done.

Make osx build not required and enable fast_finish.

---

checkstyle.xml
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationIT.java
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java

I'd like to rename integration test classes to `*IT` to avoid potential naming collisions with unit test classes. The `*IT` naming convention is somewhat widely used as it is the default in Maven's Failsafe plugin.
Now, `IT` triggers a checkstyle violation (module AbbreviationAsWordInName) given the current checkstyle rules. It seems to me that adding a `@SuppressWarnings("checkstyle:AbbreviationAsWordInName")` annotation would be a nice, uninstrusive solution. Thus enabling the support for `@SuppressWarnings` in `checkstyle.xml`, too.

Rename integration test classes to *IT.

---

.travis.yml

The other build jobs can upgrade to the new Travis default of Ubuntu Trusty,
because the Java 7 build was the only failure (#475).

Specify Ubuntu Precise only for Java 7 Travis build job.

---

core/src/main/java/io/opencensus/tags/TagContextBuilder.java
core/src/main/java/io/opencensus/tags/TagContexts.java
core/src/test/java/io/opencensus/tags/ScopedTagContextsTest.java

This PR adds methods for getting the current TagContext and setting the TagContext in a scope.  It also adds convenience methods for creating a builder from the current tags and setting the scoped tags with a builder.
The new methods correspond to methods for working with the current span.  (There are some differences, because the TagContext doesn't need to be started, and it doesn't have a parent-child relationship.)
Tagging                                                                    | Tracing
-------------------------------------------------------------------|------------------------------------------------------
`TagContexts.getCurrentTagContext()`                   | `Tracer.getCurrentSpan()`
`TagContexts.withTagContext(TagContext tags)`    | `Tracer.withSpan(Span span)` …

Add methods for interacting with the current TagContext.

---

contrib/agent/build.gradle

The permanent failure from https://github.com/census-instrumentation/opencensus-java/issues/557 is likely caused by this missing task dependency. 
After:
```none
+--- :opencensus-contrib-agent:integrationTest
|    +--- :opencensus-contrib-agent:classes *
|    +--- :opencensus-contrib-agent:integrationTestClasses *
|    +--- :opencensus-contrib-agent:shadowJar
|    |    +--- :opencensus-contrib-agent:bootstrapJar
|    |    |    \--- :opencensus-contrib-agent:classes *
|    |    \--- :opencensus-contrib-agent:classes *
|    \--- :opencensus-contrib-agent:testClasses *
\--- :opencensus-contrib-agent:test
+--- :opencensus-contrib-agent:classes *
\--- :opencensus-contrib-agent:testClasses *
```
Before:
```none
+--- :opencensus-contrib-agent:integrationTest
|    +--- …
```

Add missing task dependency on shadowJar.

---

contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationIT.java
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java

This should fix the occasional build failures seen on Travis, https://github.com/census-instrumentation/opencensus-java/issues/540. There could be other causes which I've not seen or thought of yet, though.

Increase test timeouts.

---

contrib/agent/build.gradle

Re-enable integration tests.

---

core_impl/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java

Add `MutableAggregation.combine()` so that we can combine `MutableAggregation`s from different `IntervalBucket`s.

Add combine() method to MutableAggregation.

---

core/src/main/java/io/opencensus/stats/View.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java

This method is needed to calculate interval stats based on time buckets, because buckets may be incomplete and we need to calculate the ratio of passed time / bucket duration. E.g, a time bucket starts at timestamp 0 and has a duration of 20 seconds, and now is 14th seconds, the aggregated data of this bucket should be weighted as `toMillis(14 - 0) / toMillis(20)` = 0.7. 
/cc @dinooliva

Add Duration.toMillis() method and tests.

---

impl/src/main/java/io/opencensus/impl/trace/TraceComponentImpl.java
impl/src/main/java/io/opencensus/trace/TraceComponentImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/TraceComponentImplBase.java
impl_core/src/test/java/io/opencensus/implcore/trace/TraceComponentImplBaseTest.java
impl_lite/src/main/java/io/opencensus/impllite/trace/TraceComponentImplLite.java
impl_lite/src/main/java/io/opencensus/trace/TraceComponentImplLite.java

The problem is caused by the fact that the constructor of the TraceComponent was package protected in the previous version (0.5.*) and if try to load via the old API the new implementation IllegalAccessError happens:
java.lang.IllegalAccessError: tried to access method io.opencensus.trace.TraceComponent.<init>()V from class io.opencensus.implcore.trace.TraceComponentImplBase
at io.opencensus.implcore.trace.TraceComponentImplBase.<init>(TraceComponentImplBase.java:49)
at io.opencensus.trace.TraceComponentImpl.<init>(TraceComponentImpl.java:32)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructor …

Fix backwards compatibility between TraceComponentBaseImpl and TraceComponent.

---

core/src/main/java/io/opencensus/tags/TagContexts.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextsImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextsImplTest.java

Now TagContextsImpl.getCurrentTagContext() always returns a TagContextImpl, and
TagContextsImpl.withTagContext(TagContext) always puts a TagContextImpl into
scope, even when they encounter other subclasses of TagContext.

Always return implementation classes from TagContextsImpl methods.

---

core/src/main/java/io/opencensus/tags/TagContexts.java

Users may assume that the current trace context is the same as what they
placed into scope. For example, they might wrap a trace context and be
suprised that whatever they decorated it with is lost. This clarifies
the type-level javadoc on `TagContexts` to clarify this isn't supported.
See https://github.com/census-instrumentation/opencensus-java/pull/569#discussion_r136727376

Clarifies the contract around scoping a trace context

---

core_impl/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Implementation and tests for Interval MutableView, using IntervalBuckets. 
Overall idea: 
For each IntervalView, we always keep a queue of N + 1 buckets (by default N is 4). Each bucket has a duration which is interval duration / N. Ideally:
1. the buckets should always be up-to-date, 
2. current time should always be within the latest bucket, currently recorded stats should fall into the latest bucket,
3. there are always N buckets before the current one, which holds the stats in the past interval duration. 
When getView() is called, we will extract and combine the stats from the current and past buckets (part of the stats from the oldest bucket could have expired).
However, in reality, we couldn't track the status of buckets all the time (keep monitoring and updating the bucket queue …

Implementation and tests for IntervalView.

---

core/src/main/java/io/opencensus/tags/TagContext.java
core/src/test/java/io/opencensus/tags/TagContextTest.java

TagContext should override Object.toString(), since it is a value class.  This
implementation doesn't print the tags because the tags are currently only
exposed by an "unsafe" method, unsafeGetIterator().

Override toString() in TagContext.

---

core/src/main/java/io/opencensus/tags/TagContextBinarySerializer.java
core_impl/src/main/java/io/opencensus/implcore/tags/SerializationUtils.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextBinarySerializerImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextRoundtripTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextSerializationTest.java

The signatures changed from
```java
void serialize(TagContext tags, OutputStream output) throws IOException
TagContext deserialize(InputStream input) throws IOException
```
to
```java
byte[] toByteArray(TagContext tags)
TagContext fromByteArray(byte[] bytes) throws IOException
```
fromByteArray can only fail if there is a parse error, so we should probably
change it to use a more appropriate exception type later.
This commit also refactors the toByteArray implementation to remove the
possibility of ~~an unchecked~~ a checked exception, since it is no longer doing IO.

Change TagContext serialization methods to use byte[] (closes #213).

---

core/src/main/java/io/opencensus/tags/TagContext.java
core/src/test/java/io/opencensus/tags/CurrentTagContextUtilsTest.java
core/src/test/java/io/opencensus/tags/TagContextTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextRoundtripTest.java

Both methods are non-final so that subclasses can provide more efficient
implementations.  For example, TagContextImpl can compare the tag maps directly
when it is compared with another TagContextImpl.

Implement equals and hashCode for TagContext.

---

core/src/main/java/io/opencensus/tags/TagContextBinarySerializer.java
core/src/main/java/io/opencensus/tags/TagContextParseException.java
core/src/test/java/io/opencensus/tags/TagContextParseExceptionTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/SerializationUtils.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextBinarySerializerImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextDeserializationTest.java

This class will allow us to add fields to the exception if we need to add more information about the error in the future.
____________________________________________________________
The exception isn't used yet, because it depends on updating the deserialization method to not do IO (#213).

Add TagContextParseException to throw from deserialization method.

---

core/src/main/java/io/opencensus/tags/TagContextBuilder.java
core/src/test/java/io/opencensus/tags/ScopedTagContextsTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextBuilderImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextUtils.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextRoundtripTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextSerializationTest.java
examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java

"put" is a more descriptive name, since these methods behave like Map.put.  The name is also more consistent with Span.putAttribute.
This method removes a specific key from the builder.  The corresponding methods
in Map and Collection are named "remove".  "clear" was slightly misleading,
because Map and Collection also have "clear" methods, but they remove all
values.

Rename TagContextBuilder methods to be more consistent with Map and Collection

---

core/src/main/java/io/opencensus/tags/TagContext.java
core/src/test/java/io/opencensus/tags/TagContextTest.java

This isn't a good place to throw a NullPointerException if the subclass
incorrectly returns a null Iterator.
These tests aren't needed, because we don't specify the behavior of TagContext.hashCode().

Clean up TagContext equals and hashCode

---

.travis.yml

This commit switches to openjdk7 to work around
https://github.com/travis-ci/travis-ci/issues/7884.  It also uses jdk_switcher
to work around an issue with Gradle and OpenJDK 7:
https://github.com/gradle/gradle/issues/2421
______________________________________________________
I tested the build by importing `java.util.function.Function`: https://travis-ci.org/sebright/opencensus-java/builds/276164249
@bogdandrutu I'm not sure if this is the right approach, since I'm not familiar with the `classes` and `testClasses` tasks.

Upgrade to Ubuntu Trusty for Java 7 build by using openjdk7 (fixes #475).

---

api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
api/src/main/java/io/opencensus/trace/propagation/SpanContextParseException.java
api/src/test/java/io/opencensus/trace/propagation/BinaryFormatTest.java
api/src/test/java/io/opencensus/trace/propagation/SpanContextParseExceptionTest.java
benchmarks/src/jmh/java/io/opencensus/trace/propagation/BinaryPropagationImplBenchmark.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java

Add new methods in BinaryFormat which throw the new exception and deprecate the old methods.

Add a new SpanContextParseException and use it in BinaryFormat.

---

core/src/main/java/io/opencensus/stats/AggregationData.java
core/src/main/java/io/opencensus/stats/RpcViewConstants.java
core/src/main/java/io/opencensus/stats/View.java
core/src/main/java/io/opencensus/stats/ViewData.java
core/src/test/java/io/opencensus/stats/AggregationDataTest.java
core/src/test/java/io/opencensus/stats/RpcViewConstantsTest.java
core/src/test/java/io/opencensus/stats/ViewDataTest.java
core/src/test/java/io/opencensus/stats/ViewTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/IntervalBucketTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Per our discussion, now each `View` will have one `Aggregation` and each `ViewData` will have one type of `AggregationData`. Also update `MeanData` so that users can get count from it.
Might be easier to review by each commit.
`Distribution` Aggregation will be added in PR #630 .

Update View and ViewData to have only one Aggregation/Data

---

core/src/main/java/io/opencensus/stats/MeasureMap.java
core/src/test/java/io/opencensus/stats/MeasureMapTest.java
core/src/test/java/io/opencensus/stats/NoopStatsRecorderTest.java
core/src/test/java/io/opencensus/stats/StatsRecorderTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java

1. Rename MeasureMap.Builder.set() to put(). Consistent with TagContextBuilder #627 
2. Overwrite existing Measure values, if there are subsequent updates to a Measure that is already put.

Refactor MeasureMap.Builder

---

core/src/main/java/io/opencensus/tags/NoopTags.java
core/src/main/java/io/opencensus/tags/TagContext.java
core/src/main/java/io/opencensus/tags/TagContextBinarySerializer.java
core/src/main/java/io/opencensus/tags/TagContextBuilder.java
core/src/main/java/io/opencensus/tags/TagPropagationComponent.java
core/src/main/java/io/opencensus/tags/Tagger.java
core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core/src/test/java/io/opencensus/tags/NoopTagsTest.java
core/src/test/java/io/opencensus/tags/TagsTest.java

This change will allow us to move the public serialization-related classes into
a new package without moving their no-op implementations.  Then the no-op classes
can remain package-private.
_____________________________________________________________________
This is needed for #641.

Move tagging no-op classes into a new class, NoopTags.

---

core_impl/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

For supporting long measure values. The output `AggregationData` will all be double, even if the input values are long.

Wrap long to double internally.

---

core_impl/src/test/java/io/opencensus/implcore/tags/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagsTestUtil.java

Clean up tests for tagging implementation.

---

.travis.yml

And quote.
https://google.github.io/styleguide/shell.xml says so, for good reasons.

Use $(command) instead of backticks.

---

api/src/main/java/io/opencensus/internal/NoopScope.java
core/src/main/java/io/opencensus/tags/NoopTags.java
core/src/main/java/io/opencensus/tags/TagContextBuilder.java
core/src/main/java/io/opencensus/tags/Tagger.java
core/src/test/java/io/opencensus/tags/NoopTagsTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/CurrentTagContextUtils.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextBuilderImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/CurrentTagContextUtilsTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/ScopedTagContextsTest.java

This commit makes all methods in Tagger and TagContextBuilder abstract.  It also
changes the no-op Tagger and TagContextBuilder so that they do not access the
current context.
This change gives the implementation more flexibility to control when it
accesses the current context.  For example, it could avoid setting the current
context when tagging is not enabled.  It also simplifies the code by not
splitting the current context logic between the API and implementation classes.

Move current TagContext logic from the API to the implementation (closes #632).

---

core/src/main/java/io/opencensus/tags/NoopTags.java
core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
core/src/main/java/io/opencensus/tags/propagation/TagContextParseException.java
core/src/main/java/io/opencensus/tags/propagation/TagPropagationComponent.java
core/src/test/java/io/opencensus/tags/NoopTagsTest.java
core/src/test/java/io/opencensus/tags/propagation/TagContextParseExceptionTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagsComponentImplBase.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/TagPropagationComponentImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java
core_impl_android/src/test/java/io/opencensus/impllite/tags/TagsTest.java
core_impl_java/src/test/java/io/opencensus/impl/tags/TagsTest.java

Move TagContext serialization classes into io.opencensus.tags.propagation.

---

api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
api/src/test/java/io/opencensus/trace/SpanContextTest.java
api/src/test/java/io/opencensus/trace/SpanTest.java
api/src/test/java/io/opencensus/trace/TraceOptionsTest.java
api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/SpanBuilderImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SampledSpanStoreImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java

Change when do we apply the sampling decision and simplify the PrioritySampler to not depend on the previous sampling decision.
This is the first part of solving the issue https://github.com/census-instrumentation/opencensus-java/issues/656

Change when we check the sampler.

---

.travis.yml
appveyor.yml
contrib/agent/build.gradle

This change let's Gradle execute the integration tests using different JRE versions. This makes it easy to test the agent on arbitrary JRE versions by just setting JAVA_HOMES appropriately. On Travis and AppVeyor, we test the Java 8-built agent on Java 6, 7, and 8 to increase our confidence in compatiblity with different Java versions. Also see #616, #619.

Run the integration tests using different Java versions.

---

api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
api/src/test/java/io/opencensus/trace/FakeSpan.java
api/src/test/java/io/opencensus/trace/NoopSpan.java
api/src/test/java/io/opencensus/trace/SpanTest.java
api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/SpanBuilderImplTest.java

Summary:
* Revert the change of keeping the sampling decision in the probability sampler. I will come with a better fix in 0.8.0 version of the library. This change came after adding the test in SpanBuilderImplTest.
* Keep the sampling decision from links as well.
* Extract the FakeSpan into a separate class in tests for the moment to be reused by other test classes.
TODOs:
* In 0.8.0 cleanup this based on the https://github.com/census-instrumentation/opencensus-specs/pull/6

Fix probability sampler and sampling.

---

build.gradle
exporters/trace_zipkin/README.md
exporters/trace_zipkin/build.gradle
exporters/trace_zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporter.java
exporters/trace_zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
exporters/trace_zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java
exporters/trace_zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterTest.java
settings.gradle

This adds `ZipkinExporter` which allows you to report traces to Zipkin.
By default, this uses http, but it can also work with Kafka, SQS, etc
as you can override the `Sender`.
Fixes #428

Adds ZipkinExporter

---

.travis.yml

The integration tests of contrib/agent work fine on Oracle JDK 9 so far, thus enabling these tests on Travis, too.
There's a warning about an illegal reflective access operation, which is triggered by Gradle and should be fixed in a future version of Gradle (https://github.com/gradle/gradle/issues/2995).
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by worker.org.gradle.internal.reflect.JavaMethod (file:/home/travis/.gradle/caches/4.0.1/workerMain/gradle-worker.jar) to method java.lang.ClassLoader.getPackages()
WARNING: Please consider reporting this to the maintainers of worker.org.gradle.internal.reflect.JavaMethod
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All …
```

Run integration tests of contrib/agent on Java 9, too.

---

core/src/main/java/io/opencensus/tags/NoopTags.java
core/src/test/java/io/opencensus/tags/NoopTagsTest.java

This behavior is more consistent with the corresponding implementation classes.

Check for null arguments in tagging no-op classes.

---

core/src/main/java/io/opencensus/stats/NoopStats.java
core/src/main/java/io/opencensus/stats/Stats.java
core/src/test/java/io/opencensus/stats/NoopStatsTest.java
core/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
core/src/test/java/io/opencensus/stats/StatsTest.java

NoopViewManager maintains a map of views so that it can return empty ViewDatas
from getView.  It also prevents different views with the same name from being
registered.

Add a no-op ViewManager (closes #614).

---

api/src/main/java/io/opencensus/internal/StringUtil.java
api/src/test/java/io/opencensus/internal/StringUtilTest.java

We don't need StringUtil.sanitize, since we no longer sanitize tags.
Additionally, we don't need to throw an AssertionError from the constructor to
discourage instantiation of the class, because the class is now in the internal
package.
_________________________________________________________________
@songy23 Do you think we can remove these constants and methods now?

Clean up io.opencensus.internal.StringUtil.

---

core/src/main/java/io/opencensus/tags/NoopTags.java
core/src/main/java/io/opencensus/tags/TaggingState.java
core/src/main/java/io/opencensus/tags/Tags.java
core/src/main/java/io/opencensus/tags/TagsComponent.java
core/src/test/java/io/opencensus/tags/NoopTagsTest.java
core/src/test/java/io/opencensus/tags/TagsTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagsComponentImplBase.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagComponentImplBaseTest.java

This commit adds an enum to represent the tagging state (TaggingState) and adds
getters and setters for the state to TagsComponent and Tags.  The state has no
effect yet.

Add API for enabling/disabling tagging (part of #608).

---

core_impl/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java

#658 moved the TagContext iterator method to an internal class.

Remove out of date TODO.

---

core_impl/src/main/java/io/opencensus/implcore/tags/CurrentTaggingState.java
core_impl/src/main/java/io/opencensus/implcore/tags/NoopTagContextBuilder.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagContextImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/TagsComponentImplBase.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/TagPropagationComponentImpl.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/CurrentTaggingStateTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/ScopedTagContextsTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

Disabling tagging does not disable stats collection, so disabling tagging could
cause stats to be recorded with empty or out-of-date tags.

Implement Tags.getState and Tags.setState (part of #608).

---

.travis.yml

This commit fixes a bug where TRAVIS_JDK_VERSION didn't match any cases on OS X,
because it wasn't set.  It probably wasn't set because the OS X image determines
the Java version, and the "jdk" field is ignored
(https://docs.travis-ci.com/user/reference/osx/#JDK-and-OS-X).
The OS X case avoids using jdk_switcher, because it isn't available on OS X.
This commit also adds a default case to fail the build when there is an unknown
OS or JDK.  The default case would have prevented the silent failure in #691.

Add a separate case for OS X to .travis.yml (fixes #691).

---

core_impl/src/main/java/io/opencensus/implcore/tags/NoopTagContextBuilder.java
core_impl/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java
impl_core/src/main/java/io/opencensus/implcore/internal/NoopScope.java

The tagging implementation was using NoopScope from the API library, even though
it was in an "internal" package.  This commit adds a NoopScope class to
io.opencensus.implcore.internal.
______________________________________
It would be nice if we could check for access to internal packages in CI, but I'm not sure how.

 Remove dependency between i.o.implcore.tags and i.o.internal.

---

core/src/main/java/io/opencensus/stats/Measurement.java

The values are set as primitives, so this change avoids unnecessary boxing.
/cc @dinooliva

Change Measurement value fields to primitive double and long.

---

core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

TagContext serialization test cleanup

---

core/src/main/java/io/opencensus/stats/NoopStats.java
core/src/main/java/io/opencensus/stats/ViewManager.java
core/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/ViewManagerImpl.java

Only one view can be registered per name, so only the name is needed to
unambiguously look up a registered view.
One benefit of this change is that users don't need to provide as much data.
This difference could be important when clients query views over the network.
Another benefit is that it eliminates the possibility that the input View's
non-name fields don't match the registered view.  One way to handle that case in
getView(View) is to check that the other fields match.  However, that is more
expensive than only looking up the name.

Change ViewManager.getView to take a View.Name instead of a View.

---

core/src/main/java/io/opencensus/stats/NoopStats.java
core/src/main/java/io/opencensus/stats/Stats.java
core/src/main/java/io/opencensus/stats/StatsCollectionState.java
core/src/main/java/io/opencensus/stats/StatsComponent.java
core/src/test/java/io/opencensus/stats/NoopStatsTest.java
core/src/test/java/io/opencensus/stats/StatsTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsComponentImplBaseTest.java

This commit adds an enum that represents the state of the StatsComponent,
StatsCollectionState, and getters and setters for that state.  The state has no
effect yet.
____________________________________________________________

Add API for enabling/disabling stats collection (part of #608).

---

api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
impl_core/src/main/java/io/opencensus/implcore/trace/TraceComponentImplBase.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/ExportComponentImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SampledSpanStoreImplTest.java

Change the logic of register/unregister the span name to local span store form directly accessing the lock to log an event into our event queue and consume it by the worker thread.
This way we remove a global lock (contention) between main threads and the worker thread.
Fixes https://github.com/census-instrumentation/opencensus-java/issues/711
Reason to not use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html is that the map is read intense not write and ConcurrentHashMap is optimized for writes.

Remove contention between threads and worker thread when register span names.

---

api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/test/java/io/opencensus/stats/AggregationDataTest.java
api/src/test/java/io/opencensus/stats/ViewDataTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java

`List<Long>` is consistent with the return type of
`DistributionData.getBucketCounts()`.

Make DistributionData.create take a List instead of a long[] for bucket counts.

---

api/src/main/java/io/opencensus/tags/TagKey.java
api/src/test/java/io/opencensus/tags/TagKeyTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java

Do you think we should add this restriction to tag keys?

Disallow empty tag keys.

---

core_impl/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

Now TagContextBinarySerializerImpl.fromByteArray skips the rest of the output
when it encounters an unknown field, instead of throwing a
TagContextParseException.
This change will increase compatibility between the first version of the tagging
implementation and later versions, because the first version will be able to
accept TagContexts even when they contain newer fields.
_______________________________________________________________
This PR is #704 rebased onto #710.  It is much simpler than #704, because it doesn't need to handle unsupported tag types differently from unknown fields.
EDIT: The first three commits are from #710.

Silently skip unknown TagContext fields during deserialization (issue #655).

---

api/src/test/java/io/opencensus/tags/TagKeyTest.java
api/src/test/java/io/opencensus/tags/TagValueTest.java

This commit adds a test for TagValue.asString and ensures that only one method
is called after ExpectedException.expect is called.

Make TagKey and TagValue tests consistent.

---

api/src/main/java/io/opencensus/stats/MeasureMap.java
api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/StatsRecorder.java
api/src/test/java/io/opencensus/stats/NoopStatsTest.java
core_impl/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
core_impl/src/main/java/io/opencensus/implcore/stats/MeasureMapInternal.java
core_impl/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsRecorderImpl.java
core_impl/src/test/java/io/opencensus/implcore/stats/MeasureMapInternalTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
examples/src/main/java/io/opencensus/examples/stats/StatsRunner.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/726
Per our discussion today, we're renaming `StatsRecord` to `MeasureMap`. There are also some temporary changes to the implementation (renamed the old internal `MeasureMap` to `MeasureMapInternal`), which will be updated after the API release.

Rename StatsRecord to MeasureMap

---

api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
api/src/main/java/io/opencensus/tags/propagation/TagContextSerializationException.java
api/src/test/java/io/opencensus/tags/NoopTagsTest.java
api/src/test/java/io/opencensus/tags/propagation/TagContextSerializationExceptionTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

The first version of the implementation will throw
TagContextSerializationException when the serialized TagContext would be larger
than 8192 bytes.

Make TagContextBinarySerializer.toByteArray throw a checked exception.

---

api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
api/src/main/java/io/opencensus/tags/propagation/TagContextDeserializationException.java
api/src/test/java/io/opencensus/tags/NoopTagsTest.java
api/src/test/java/io/opencensus/tags/propagation/TagContextDeserializationExceptionTest.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
core_impl/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java
core_impl/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

The new name is more consistent with TagContextSerializationException.

Rename TagContextParseException to TagContextDeserializationException. 

---

api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java

The value will probably be configurable in a future version, and the default
could change.

Avoid specifying maximum size of serialized TagContext.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextTrampoline.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/ContextTrampolineTest.java

This is a follow-up on https://github.com/census-instrumentation/opencensus-java/pull/548 (https://github.com/census-instrumentation/opencensus-java/pull/548#issuecomment-324511205, https://github.com/census-instrumentation/opencensus-java/pull/548#issuecomment-324781496), just renaming ContextManager to ContextTrampoline, which is better name. Going to add the TraceTrampoline (etc.) mentioned in https://github.com/census-instrumentation/opencensus-java/pull/548 in a separate PR.

Rename ContextManager to ContextTrampoline.

---

README.md
contrib/grpc_util/README.md
contrib/zpages/README.md
exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/zipkin/README.md

* Also added suggestion to depend on the API, this will make sure that the same version of the API artifact is used (at least when maven and gradle is used).

Update versions in the README files.

---

contrib/agent/build.gradle

Integration tests obviously depend on shadowJar. Without this task dependency, e.g. `./gradlew clean opencensus-contrib-agent:check` reproducibly fails.

Add the missing task dependency of integration tests on shadowJar.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextTrampolineInitializer.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java

Make ExecutorInstrumentation easier to test by moving the initialization of the static ContextManager to a separate class.

Make ExecutorInstrumentation easier to test.

---

contrib/agent/build.gradle

We are missing the Jacoco execution data for integration tests because the JaCoCo agent is added after our agent and thus cannot instrument our agent. This change fixes that.
There are a few more issues (e.g. merging execution data) that need to be fixed before the test coverage from integration tests is reflected in jacoco reports (and coveralls.io). I haven't yet figured out a complete solution, but this change is definitely part of it.

Add the Jacoco agent first so that it can instrument our agent.

---

build.gradle
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentationIT.java
contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java
contrib/agent/src/jmh/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationBenchmark.java

The formatter plugin only saw the main and test source sets, but not the additional source sets defined in the agent subproject. Thus, evaluate the subproject first, then configure the formatter. (also see "afterEvaluate" in https://docs.gradle.org/current/userguide/multi_project_builds.html)

Apply the Google Java Formatter on all source sets.

---

contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceStrategy.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceTrampoline.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceStrategyImpl.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceTrampolineInitializer.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/TraceTrampolineTest.java

This change adds a separate trampoline for tracing-related methods (cf. https://github.com/census-instrumentation/opencensus-java/pull/548#issuecomment-324511205). Besides the different naming and purpose, it's just a copy of the existing ContextTrampoline.

Add a trampoline for tracing-related methods.

---

impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
impl_core/src/main/java/io/opencensus/implcore/internal/DaemonThreadFactory.java
impl_core/src/main/java/io/opencensus/implcore/internal/EventQueue.java

This is a cleanup of the Disruptor code and extract the DeamonThreadFactory to be reused by exporters and other classes.

Extract the DeamonThreadFactory from Disruptor and clean code.

---

api/src/main/java/io/opencensus/trace/SpanBuilder.java

FWIW, I've reused parts of SpanBuilder#startScopedSpan's Javadoc in https://github.com/census-instrumentation/opencensus-java/pull/766/files#diff-cdc21ce534c8e27c5a611a054d00c6a2R70, but reworded it only slightly. Sound better to me, but then again, English is not my first language.

Slightly reword Javadoc on SpanBuilder#startScopedSpan.

---

api/src/main/java/io/opencensus/stats/StatsComponent.java
core_impl/src/main/java/io/opencensus/implcore/stats/CurrentStatsState.java
core_impl/src/main/java/io/opencensus/implcore/stats/IntervalBucket.java
core_impl/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
core_impl/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java
core_impl/src/main/java/io/opencensus/implcore/stats/StatsManager.java
core_impl/src/main/java/io/opencensus/implcore/stats/ViewManagerImpl.java
core_impl/src/test/java/io/opencensus/implcore/stats/CurrentStatsStateTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/MeasureToViewMapTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsComponentImplBaseTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
core_impl/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
core_impl/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Implement stats collection state. Stats library has 3 major operations that are affected by state: `registerView()`, `record()` and `getView()`. I think there are 2 options for implementing state for them:
1. When state is `DISABLED`, implement all the 3 operations above as no-op. `registerView()` won't really add the view to `MeasureToViewMap`, and `getView()` will always return null. (It's not possible to return empty `ViewData` in this case, since no `View` will be preserved.)
2. When state is `DISABLED`, we still add `View`s to `MeasureToViewMap` when `registerView()` is called. `record()` will be ignored, and `getView()` will return an empty `ViewData` for registered `View`s. When users re-enabled stats collection, they don't need to register views again.
I think either of these two …

Update Stats implementation to use Stats state

---

all/build.gradle
build.gradle
exporters/stats/stackdriver/README.md
exporters/stats/stackdriver/build.gradle
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThread.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/WorkerThread.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
settings.gradle

Per our discussion yesterday, we're not going to support a push model for exporting ViewData in Stats library in the first release. Instead, the StackDriver exporter will be more like an independent agent: users need to register views against exporter first, and then the exporter will poll stats from the Stats library for all registered views and upload it to StackDriver periodically.

Add a StackDriver exporter for stats using a Pull model

---

exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

`StackdriverStatsExporterTest.registerViewAndExport()` is slower on some machine. Previously it has an 1 second timeout for the asynchronous verification, however this limit seems too strict. Relax the timeout to 2 seconds to make it more stable.
Test failures:
https://travis-ci.org/census-instrumentation/opencensus-java/jobs/299758118

Increase timeout for an asynchronous verification

---

contrib/agent/build.gradle
contrib/agent/src/main/java/io/opencensus/contrib/agent/Resources.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/ResourcesTest.java

There's not enough benefit from 1.7 and then using retrolambda for
targetting 1.6. Just use plain 1.6 and get rid some of the otherwise
required magic.
Also fixes #445 by removing retrolambda.

Just target Java 1.6, it simplifies a few things.

---

api/src/test/java/io/opencensus/trace/ScopedSpanHandleTest.java
api/src/test/java/io/opencensus/trace/SpanTest.java
api/src/test/java/io/opencensus/trace/TracerTest.java
build.gradle
contrib/agent/src/test/java/io/opencensus/contrib/agent/ResourcesTest.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/ContextTrampolineTest.java
contrib/agent/src/test/java/io/opencensus/contrib/agent/bootstrap/TraceTrampolineTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
exporters/trace/logging/src/test/java/io/opencensus/exporter/trace/logging/LoggingExporterTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporterTest.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java

This reverts commit 3f946d748ea171c70c297cf3188e4b0dbadab1ad.
Reverting due to integration issues.

Revert "Use the current release version of Mockito. (#751)"

---

api/src/test/java/io/opencensus/trace/export/SpanDataTest.java
build.gradle
gradle/errorprone/experimental_errors
gradle/errorprone/experimental_warnings
gradle/errorprone/warnings
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
testing/src/main/java/io/opencensus/testing/export/TestHandler.java

Other changes:
- Remove references to warnings that were removed from Error Prone.
- Suppress occurrences of a new warning, JdkObsolete. All of the warnings are
about uses of LinkedList. We need to decide whether to use a different class
or continue suppressing the warnings. I left TODOs, since each occurrence may
need to be handled differently.
________________________________________________________________
@bogdandrutu I wasn't sure how to update the build file, so let me know if there is a better way to specify the Error Prone version.

Upgrade to Error Prone 2.1.2.

---

api/src/main/java/io/opencensus/tags/NoopTags.java
api/src/main/java/io/opencensus/tags/Tags.java
api/src/main/java/io/opencensus/tags/TagsComponent.java
api/src/test/java/io/opencensus/tags/NoopTagsTest.java
api/src/test/java/io/opencensus/tags/TagsTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/CurrentStatsState.java
impl_core/src/main/java/io/opencensus/implcore/tags/CurrentTaggingState.java
impl_core/src/main/java/io/opencensus/implcore/tags/TaggerImpl.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagsComponentImplBase.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
impl_core/src/test/java/io/opencensus/implcore/tags/CurrentTaggingStateTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/TagsComponentImplBaseTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImplTest.java

This commit is related to #608.  It deprecates Tags.setState and
TagsComponent.setState and makes NoopTagsComponent.setState and
TagsComponentImplBase.setState throw IllegalStateException when they are called
after getState.
_________________________________________________________________
This PR is similar to #789, but applied to tagging.

Deprecate Tags.setState, and throw an exception when it is called after getState.

---

api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/Stats.java
api/src/main/java/io/opencensus/stats/StatsComponent.java
api/src/test/java/io/opencensus/stats/NoopStatsTest.java
api/src/test/java/io/opencensus/stats/StatsTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsComponentImplBaseTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Changes on Stats state APIs, similar to https://github.com/census-instrumentation/opencensus-java/pull/790.
Closes https://github.com/census-instrumentation/opencensus-java/issues/762.

Deprecate Stats.setState, and throw an exception when it is called after getState.

---

api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/ViewManager.java
api/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/StatsManager.java
impl_core/src/main/java/io/opencensus/implcore/stats/ViewManagerImpl.java
impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

This method currently returns all registered cumulative views.  We could add a
way to specify which views should be exported later.  The API is currently
needed for the StackDriver exporter.
The NoopViewManager also returns all cumulative views.  However, the exporter
could choose to not export data when stats collection isn't enabled.

Add ViewManager.getAllExportedViews().

---

impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
impl_core/src/main/java/io/opencensus/implcore/tags/propagation/TagContextBinarySerializerImpl.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/761.

Enforce size limit when serializing and deserializing TagContext.

---

exporters/stats/stackdriver/README.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThread.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThreadTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

~~This PR depends on #794.~~
Remove `StackdriverStatsExporter.registerView()`. Instead, export views that are returned by `ViewManager.getAllExportedViews()`. Now `StackdriverStatsExporter` only has factory methods, and uploading `View` to Stackdriver will be handled by the worker thread.
In addition, due to the changes above, I've also moved tests on `register()` and `export()` to `StackdriverExporterWorkerThreadTest`. This also resolves a TODO from https://github.com/census-instrumentation/opencensus-java/pull/797, since there are no asynchronous verification in the unit tests now.

 Remove StackdriverStatsExporter.registerView() and rearrange unit tests.

---

api/src/main/java/io/opencensus/stats/Stats.java
api/src/main/java/io/opencensus/stats/StatsComponent.java

This commit updates the Javadocs for Stats.setState and StatsComponent.setState
to avoid guaranteeing that the state won't change.  It is consistent with Tags
and TagsComponent.

Use consistent wording in stats and tags 'setState' Javadocs.

---

impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextRoundtripTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/761

Only apply size limit to the bytes representing tag keys and values.

---

impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

Deserialization should succeed, and only the last tag value should be used.

Test deserializing duplicate tag keys and duplicate tags.

---

api/src/main/java/io/opencensus/tags/TagKey.java

We decided not to allow empty tag key names in
https://github.com/census-instrumentation/opencensus-specs/issues/12.

Remove an obsolete TODO from TagKey.java.

---

impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

TagContextBinarySerializer.fromByteArray should throw an exception, even though
the input represents a relatively small TagContext.
___________________________________________________________________
See https://github.com/census-instrumentation/opencensus-specs/issues/12#issuecomment-345353825.

Test deserializing TagContext with all duplicate keys that is over size limit.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

Fix https://github.com/census-instrumentation/opencensus-java/issues/831

Disable setting min/max for Stackdriver export

---

api/src/main/java/io/opencensus/stats/View.java
api/src/test/java/io/opencensus/stats/ViewTest.java

To be consistent with TagKey and Measure.

Update length limit for View.Name

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThread.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerThreadTest.java

If we batch export too many `Timeseries` with one `CreateTimeSeriesRequest`, Stackdriver client might throw an `Http2Exception: Header size exceeded max allowed size (10240)`
Fix https://github.com/census-instrumentation/opencensus-java/issues/840

Batch export 3 Timeseries at one RPC call

---

api/src/main/java/io/opencensus/trace/TraceComponent.java
api/src/main/java/io/opencensus/trace/Tracing.java
api/src/main/java/io/opencensus/trace/export/ExportComponent.java
api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
api/src/test/java/io/opencensus/trace/TraceComponentTest.java
api/src/test/java/io/opencensus/trace/TracingTest.java
api/src/test/java/io/opencensus/trace/export/ExportComponentTest.java
api/src/test/java/io/opencensus/trace/export/NoopRunningSpanStoreTest.java
api/src/test/java/io/opencensus/trace/export/NoopSampledSpanStoreTest.java

This change is a follow up of a comment by @bogdandrutu in #677 .
[NoopRunningSpanStore](https://github.com/census-instrumentation/opencensus-java/compare/master...HailongWen:noop-span-store?expand=1#diff-23ac90b4be2dc7cd150cb6ee4d849721) will always return empty list when querying running SpanData.
[NoopSampledSpanStore](https://github.com/HailongWen/opencensus-java/blob/d89b938b29497ad234a466c97dedd3002c7aa414/api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java) has a similar no-op implementation. It maintains a set of span names for data collections and return empty Summary for each span name.
Similar to [NoopViewManager](https://github.com/HailongWen/opencensus-java/blob/d89b938b29497ad234a466c97dedd3002c7aa414/api/src/main/java/io/opencensus/stats/NoopStats.java), …

Add NoopRunningSpanStore and NoopSampledSpanStore.

---

impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java

* Use continue when skip a value in a while-loop.
* Cleanup test code.
(cherry picked from commit bfa6f29b49de35bb7c9439ec4da6ae0547bfd190)

Use continue when skip a value in a while-loop. (#879)

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

This commit makes the following changes:
* Renamed `io.opencensus.implcore.internal.DaemonThreadFactory` to `io.opencensus.interl.OpenCensusThreadFactory` so that other components can reuse the logic to detect the runtime and create threads accordingly.
* Refactored the `StackdriverExporterWorkerThread` to a `Runnable` called `StackdriverExporterWorker`.
* Adapt all occurrences and invocation of the changes above.

Make stackdriver stats exporter GAE Java7 compatible. (fixes #878)

---

.travis.yml
examples/BUILD.bazel
examples/README.md
examples/WORKSPACE
examples/opencensus_workspace.bzl
scripts/travis_script

To resolve the transitive dependency, I used [migration-tooling](https://github.com/bazelbuild/migration-tooling) to auto-generate libraries definitions. Command can be found in the generated file, which might help when updating the build file in the future.
This PR is a sub-item of #855 and depends on #890 to be merged. I'll update the `README.md` later.

Add bazel build support for `examples`.

---

impl_core/src/main/java/io/opencensus/implcore/tags/propagation/SerializationUtils.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextDeserializationTest.java

Do we want to keep backwards-compatible on encoding? I'm not sure about this but Go allows bytes in previous versions: https://github.com/census-instrumentation/opencensus-go/blob/master/tag/map_codec.go#L191

Support previous encoding versions.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/844.
Use one span throughout exporting, and add annotations and status for each call to Stackdriver client.

Instrument the SD stats exporter with trace.

---

impl_core/src/main/java/io/opencensus/implcore/tags/TagContextBuilderImpl.java
impl_core/src/test/java/io/opencensus/implcore/tags/TagContextImplTest.java

This commit splits some of the existing tests in order to test different
operations separately. It also updates variable names and the implementation of
TagContextBuilder.put after the removal of tag types.

Improve TagContextImpl tests.

---

api/src/main/java/io/opencensus/tags/TagContext.java
api/src/main/java/io/opencensus/trace/SpanContext.java
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/Status.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/main/java/io/opencensus/trace/TraceOptions.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporter.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporter.java
findbugs-exclude.xml
gradle/errorprone/experimental_suggestions
impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/main/java/io/opencensus/implcore/tags/CurrentTagContextUtils.java
impl_core/src/main/java/io/opencensus/implcore/tags/TagContextImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/StartEndHandlerImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/internal/ConcurrentIntrusiveList.java

This commit adds some Nullable annotations that are required by the Checker
Framework, but it doesn't change any other code.  It also suppresses some Error
Prone and FindBugs warnings that conflict with the Checker Framework, since the
three tools use different algorithms.

Add more null annotations (issue #359).

---

exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerTest.java

Addresses the first two items in #854.
1. Add test for generated proto. The test is written against the [cloud trace v2 span definition](https://cloud.google.com/trace/docs/reference/v2/rpc/google.devtools.cloudtrace.v2#google.devtools.cloudtrace.v2.Span). During test I found that `childSpanCount` and `Links` are not put in the proto so I implement them.
2. Add mock for `TraceService` to test basic interaction. Since the class itself is final and cannot be mocked in Mockito v1, so I mock the `TraceServiceStub` instead, which will be called eventually by `TraceService`.

Add unit test for SD trace exporter proto generation method.

---

README.md
all/build.gradle
build.gradle
exporters/stats/signalfx/README.md
exporters/stats/signalfx/build.gradle
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxMetricsSenderFactory.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsConfiguration.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporter.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsConfigurationTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThreadTest.java
settings.gradle

A stats exporter to report stats as SignalFx metric timeseries.
Note that SignalFx doesn't have native histogram support yet, so those views can't be reported to SignalFx and are ignored for now.

SignalFx stats exporter

---

api/src/main/java/io/opencensus/trace/propagation/PropagationComponent.java

As suggested by adrian's [comment](https://github.com/census-instrumentation/opencensus-java/issues/908#issuecomment-351904433), the newly added API in `PropagationComponent` should be marked experimental.

Annotate `PropagationComponent#getB3Format()` with `ExperimentalApi`.

---

RELEASING.md
examples/build.gradle

This also fixes the release instructions to not repeat the same thing again.

Bump version in examples/build.gradle

---

RELEASING.md
examples/pom.xml

Fix #940 in master branch.
Once we release the new version I'll update the census dependency version in example gradle/maven/bazel, and update the corresponding script in `RELEASING.md`.

Update scripts in RELEASING.md to include examples/pom.xml, and apply the change.

---

contrib/http_util/src/main/java/io/opencensus/contrib/http/util/CloudTraceFormat.java
contrib/http_util/src/test/java/io/opencensus/contrib/http/util/CloudTraceFormatTest.java

The '/' char value is used to determine from where to start searching in order to find the trace options in the trace header.
I think that using this char value is done by mistake. Because the char value for '/' is 47 making it impossible to find the trace options in a trace header with a short span id (causing it to be shorter that 47).

Fixed bug in CloudTraceFormat that made it impossible to use short span id's

---

contrib/http_util/src/main/java/io/opencensus/contrib/http/util/CloudTraceFormat.java
contrib/http_util/src/test/java/io/opencensus/contrib/http/util/CloudTraceFormatTest.java

(cherry picked from commit 765318b5ec65fa840961ecc12d8e3683a861ccec)

Fixed bug that made it impossible to use short span id's (#950)

---

exporters/trace/logging/README.md
exporters/trace/stackdriver/README.md
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
exporters/trace/zipkin/README.md
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinTraceExporter.java

Fixes #947. The renaming is not released yet so I will use #955 to trace the change in example code.

Update occurrences of deprecated trace exporter in README.md and javadoc (except examples).

---

build.gradle
contrib/grpc_util/build.gradle
exporters/stats/signalfx/build.gradle
exporters/stats/stackdriver/build.gradle
exporters/trace/stackdriver/build.gradle

Maven Enforcer's dependencyConvergence is commonly used in Spring projects.
Currently we cannot do it for the SD exporters because of this https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2803

Keep artifacts dependencyConvergence-clean

---

api/src/main/java/io/opencensus/stats/Aggregation.java
api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/main/java/io/opencensus/stats/BucketBoundaries.java
api/src/main/java/io/opencensus/stats/Measure.java
api/src/main/java/io/opencensus/stats/MeasureMap.java
api/src/main/java/io/opencensus/stats/Measurement.java
api/src/main/java/io/opencensus/stats/Stats.java
api/src/main/java/io/opencensus/stats/StatsCollectionState.java
api/src/main/java/io/opencensus/stats/StatsComponent.java
api/src/main/java/io/opencensus/stats/StatsRecorder.java
api/src/main/java/io/opencensus/stats/View.java
api/src/main/java/io/opencensus/stats/ViewData.java
api/src/main/java/io/opencensus/stats/ViewManager.java
api/src/main/java/io/opencensus/tags/InternalUtils.java
api/src/main/java/io/opencensus/tags/Tag.java
api/src/main/java/io/opencensus/tags/TagContext.java
api/src/main/java/io/opencensus/tags/TagContextBuilder.java
api/src/main/java/io/opencensus/tags/TagKey.java
api/src/main/java/io/opencensus/tags/TagValue.java
api/src/main/java/io/opencensus/tags/Tagger.java
api/src/main/java/io/opencensus/tags/TaggingState.java
api/src/main/java/io/opencensus/tags/Tags.java
api/src/main/java/io/opencensus/tags/TagsComponent.java
api/src/main/java/io/opencensus/tags/propagation/TagContextBinarySerializer.java
api/src/main/java/io/opencensus/tags/propagation/TagContextDeserializationException.java
api/src/main/java/io/opencensus/tags/propagation/TagContextSerializationException.java
api/src/main/java/io/opencensus/tags/propagation/TagPropagationComponent.java
api/src/main/java/io/opencensus/tags/unsafe/ContextUtils.java

The only APIs that were missing `@since` tags were from the first stats/tagging API release.

Add '@since' Javadoc tag to all stats and tagging APIs (issue #864).

---

examples/README.md

In this [PR](https://github.com/census-instrumentation/opencensus-java/commit/c0be5b44ec9d787e0834dc418381f0a5b87fca85#diff-61bed45ac875f146b81f38ad4f26140c) we changed the name of the project and the generated path in the command should be updated accordingly.

Fix broken command in examples readme.

---

impl_core/src/main/java/io/opencensus/implcore/trace/export/ExportComponentImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/RunningSpanStoreImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SampledSpanStoreImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/ExportComponentImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessRunningSpanStoreImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/InProcessSampledSpanStoreImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopRunningSpanStoreImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/NoopSampledSpanStoreImplTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java

Since `XxxSpanStoreImpl` have the `final` modifier, they need to be removed to `abstract` so we can add no-op implementation and pass nullness check.
This PR contains two commits. 
- The first one removes "final" modifier of the concrete implementations and rename them to `InProcessXxxSpanStoreImpl` since they serve in-process data collection purpose, it is a WIP PR and temporarily breaks the build.
- The second one rebuilds the old classes with `abstract` modifier and adds no-op implementation and related tests.

Make `XxxSpanStoreImpl` abstract and add no-op implementation. (fixes #914)

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java

gRPC has already recorded stats for started and finished RPCs:
https://github.com/grpc/grpc-java/blob/4c483ef7a0434fd4a703fdeb9e5031a89fca89e3/core/src/main/java/io/grpc/internal/CensusStatsModule.java#L392

Register STARTED and FINISHED views for RpcViews.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

Previously we found an issue that if we batch too many `TimeSeries` in one call, Stackdriver metric service client might throw a `Http2Exception: Header size exceeded max allowed size (10240)` (https://github.com/census-instrumentation/opencensus-java/issues/840). I posted https://github.com/census-instrumentation/opencensus-java/pull/836 to fix this, which limit the batch size to 3. After running some E2E tests recently, I think this issue in Stackdriver client has been fixed, and it's safe to remove the batch limit.
Update the batch limit to 200, which is the maximum size allowed by Stackdriver client v3 (https://github.com/census-instrumentation/opencensus-go/issues/170).
/cc @jcd2

Increase batch export size of StackdriverStatsExporter to 200

---

README.md
RELEASING.md
build.gradle
exporters/trace/instana/README.md
exporters/trace/instana/build.gradle
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaTraceExporter.java
exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaTraceExporterTest.java
settings.gradle

Instana is happy to support OpenCensus with a proof of concept for its integration.
The target is to get this PR merged, but it can also used as basis for discussion for a while.
The exporter sends to an API that is intended for customers to report spans to, but is by far not as performant as several other internal APIs. This API also only supports a subset of the fields that Instana supports or would be desired for a OpenCensus integration.
Any Instana agent exposes this API via http. The agent then will handle offloading and authorization to the Instana backend(s).
The most significant limitation of Instanas data model compared to the OpenCencus one is that traceIds are only 64 bit wide. Instana is working on supporting wider ids in the near future, but currently this extension will …

First proof of concept for Instana integration

---

exporters/trace/stackdriver/build.gradle
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java

Similar to [StackdriverStatsConfiguration](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java).
Since we've just deprecated `StackdriverExporter` and rename it to `StackdriverTraceExporter` and it is not yet released, I simply removed those factory methods in the new class instead of deprecating them again.

Add a configuration class to help to create StackdriverTraceExporter. (closes #949)

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/AgentMain.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/Settings.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextStrategy.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/ContextTrampoline.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceStrategy.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/bootstrap/TraceTrampoline.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ContextTrampolineInitializer.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ExecutorInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/Instrumenter.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentation.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/TraceTrampolineInitializer.java
contrib/agent/src/main/java/io/opencensus/contrib/agent/instrumentation/UrlInstrumentation.java

This commit also adds a missing Javadoc.
@ubschmidt2 Do you think that the agent classes should have `@since` tags?  I wasn't sure, but I added them while I was updating the other contrib classes.

Add '@since' Javadoc tag to all agent APIs (issue #864).

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java

Since we're going to remove `Interval` window in the future, we'll need cumulative views for started and finished RPCs (currently there are only minute and hour views for them, which are to be removed).

Add cumulative views for started and finished RPCs.

---

contrib/zpages/build.gradle
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
contrib/zpages/src/test/java/io/opencensus/contrib/zpages/RpczZPageHandlerTest.java
contrib/zpages/src/test/java/io/opencensus/contrib/zpages/ZPageHandlersTest.java

Part of https://github.com/census-instrumentation/opencensus-java/issues/856.
Provides identical UI as [Go RpcZ page](https://github.com/census-instrumentation/opencensus-go/blob/master/zpages/rpcz.go). ~~Please note some stats are not supported in Java (cumulative RPC counts and max latency per minute/hour).~~
EDIT:

Add RpcZ Zpage for stats.

---

RELEASING.md
all/build.gradle
build.gradle
exporters/stats/prometheus/README.md
exporters/stats/prometheus/build.gradle
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
settings.gradle

Closes https://github.com/census-instrumentation/opencensus-java/issues/851.
Implement Prometheus Stats Exporter using a pull model, which is naturally supported by Prometheus client. Start with the minimal set of functionality - we have a collector that collects stats from OpenCensus library and converts them to Prometheus `Samples`, and users need to take care of registering this collector against the Prometheus backend. Once the collector is registered, `Samples` will be pulled every time when users query from Prometheus. This is consistent with the [OpenCensus-Go Prometheus exporter](https://github.com/census-instrumentation/opencensus-go/blob/master/exporter/prometheus/prometheus.go).
Here is an example that collects and exports stats from the [BigTable demo …

Implement Prometheus Stats exporter

---

api/src/main/java/io/opencensus/stats/ViewData.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java

So that the nullness checker framework could catch dereference of TagValues.

Add Nullable annotation to tag values.

---

contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
contrib/zpages/src/test/java/io/opencensus/contrib/zpages/ZPageHandlersTest.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/856.
Statsz page for displaying all exported views. (Currently only cumulative views are exported, and interval views will be removed soon.) Views are stored in a directory tree. Directory here refers to the namespace of a view. For example, view grpc.io/client/started_count/cumulative will be under directory structure root -> grpc.io -> client -> started_count.
For now the color and style of Statsz is similar to [Rpcz page](https://github.com/census-instrumentation/opencensus-java/blob/master/contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java).
Some screenshots:
EDIT:
/cc @tags07

Add StatsZ Zpage for stats.

---

README.md
exporters/stats/prometheus/README.md

Closes https://github.com/census-instrumentation/opencensus-java/issues/966.
This PR should be merged after Prometheus exporter is released.

Update READMEs to include Prometheus exporter.

---

build.gradle
impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java
impl_core/src/main/java/io/opencensus/implcore/internal/EventQueue.java

There are 2 bugs fixed in this PR:
1) The memory of SpanImpl, TagContext, MeasureMap was hold for all the objects in disruptor. Disruptor is configured with 8K objects so the memory for the past 8K recorded objects was hold.
2) The objects that are shared between threads via disruptor were not synchronized. Because the event is shared between producer and consumer thread all instances must be volatile.

Fix bugs, fix warnings and update disruptor.

---

build.gradle

Fixes https://github.com/census-instrumentation/opencensus-java/issues/801
This is a conservative upgrade because we want to cherry-pick this into 0.12.2. We will later upgrade to disruptor 3.4.0 but that release contains other changes as well so for the purpose of cherry-pick and minor release for OpenCensus is better to only upgrade to 3.3.9.

Upgrade disruptor to include the fix for SleepingWaitStrategy causing 100% CPU usage

---

build.gradle

They bring multiple dependencies for protobuf.

Remove stackdriver dependencyConvergence failure list because they are not clean.

---

build.gradle

This commit suppresses specific warnings for Java 7 and 9.  This allows us to
enable -Werror with Java 7, though there is still a warning with Java 9, due to
issue #1017.

Reorganize warning suppression and enable -Werror with Java 7.

---

findbugs-exclude.xml

The warnings are redundant with the Checker Framework's warnings, and they
sometimes conflict.

Suppress all FindBugs warnings about NullPointerExceptions.

---

api/src/test/java/io/opencensus/trace/samplers/SamplersTest.java

PropabilitySampler#getDescription returns a string that contains the
probability formatted according to the current locale, while the test
expects a certain format.

Fix probabilitySampler_getDescription for all locales.

---

examples/BUILD.bazel
examples/build.gradle
examples/pom.xml
examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java

Provides an (almost) identical quick start example to [OpenCensus-Go](https://github.com/census-instrumentation/opencensus-go/pull/507). As suggested from the documentation meeting, we'd like to have one consistent quick start for all languages.
/cc @rakyll

Add a QuickStart example.

---

contrib/agent/build.gradle

The shadowJar task replaces the default JAR with a self-contained JAR, which
doesn't have any dependencies. However, when uploading the "default" JAR, the
generated POM still declares all dependencies. When depending on this artifact
from a different project, these extraneous dependencies are pulled in and may
cause conflicts, exactly what the shadowed JAR is meant to avoid.
This change fixes this issue by removing all declared dependencies from the
generated POM.

Don't declare any dependencies in the generated POM because the agent JAR is self-contained.

---

api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/View.java
api/src/main/java/io/opencensus/stats/ViewData.java
api/src/test/java/io/opencensus/stats/NoopViewManagerTest.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/RpczZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/995. Might be easier to review by each commit.
- Deprecate Window and WindowData type in Stats API, and deprecate the factory method that takes Window or WindowData. Also add start and end timestamp to ViewData to replace WindowData.
- Implementation will continue to support Window (including interval stats). 
- ~~Remove usage of Window and WindowData from zpages and exporters except RpcZ, since most of them only need cumulative stats.~~
/cc @dinooliva @ramonza

Deprecate Window and WindowData.

---

exporters/stats/prometheus/build.gradle
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsConfiguration.java

Add a PrometheusStatsConfiguration class, so that users can use a custom Prometheus registry for exporting metrics.
Equivalent to https://github.com/census-instrumentation/opencensus-go/pull/533.

Add a PrometheusStatsConfiguration class.

---

build.gradle

For projects that depend on gRPC during test execution, make sure to
also configure ALPN if running on a platform (e.g. FreeBSD) that is not
supported by io.netty:netty-tcnative-boringssl-static:jar. Also see:
https://github.com/grpc/grpc-java/blob/master/SECURITY.md#tls-with-jdk-jetty-alpnnpn
I think something is better than nothing here.
This fixes the build issue on FreeBSD:
```
> Task :opencensus-exporter-stats-stackdriver:test 
io.opencensus.exporter.stats.stackdriver.StackdriverStatsExporterTest > createWithNegativeDuration FAILED
java.lang.AssertionError: 
Expected: (an instance of java.lang.IllegalArgumentException and exception with message a string containing "Duration must be positive")
but: exception with message a string containing "Duration must be positive" message was …
```

Fix build on platforms that are not supported by netty-tcnative.

---

README.md
examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java

This reflects the default gRPC views which use bytes as units.

Change MBy to By units.

---

.travis.yml

This change allows build jobs that are affected by more pull requests to run
first, to increase the probability of failures appearing in the first set of
concurrent job runs.

Move Travis jobs for example projects to the end of the build matrix.

---

contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java

Update TreeNode to store view names instead of the whole view, since for getting stats all we need is view name. ~~Also use AutoValue to implement TreeNode.~~
Hopefully this could reduce the memory usage of StatsZ a little bit, especially when there are a huge amount of exported views.

Improve StatszZPageHandler.TreeNode

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

Looks like the length of Jaeger span id is 15 with JDK7 and 16 with JDK8.
/cc @marccarre

Fix a failing test with Jaeger exporter

---

api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/main/java/io/opencensus/stats/ViewData.java
api/src/main/java/io/opencensus/tags/TagContext.java
api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
api/src/main/java/io/opencensus/trace/export/SpanData.java

This allows proguard to strip out the com.google.common.collect.* classes on Android, and is aimed at resolving https://github.com/census-instrumentation/opencensus-java/issues/1068
On Android, making this change saves 325 method references and 7.8KB in the APK size. I don't have numbers for an app that directly depends on OpenCensus, but for gRPC (grpc-core depends on opencensus-api) this is a 6.5% decrease in method references and a 3% decrease in APK size (percentages based on the increase an app will see from adding a dependency on gRPC Java and Protobuf Lite).
Dropping `Multiset` from `TagContext#equals` is the only change that looks potentially significant. But, if I understand correctly, `TagContextImpl` instances are used where the equality check may need to be fast. If this means …

Remove usages of guava collections in api/

---

impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java

Found during HTTP interop test. 
The non-ascii "─" will fail the tests.

Substitute non-ascii characters in B3Format header key.

---

.travis.yml
examples/build.gradle
scripts/travis_script

This change simplifies the example build file by removing plugins not necessary to build the project.  It adds two new build jobs, one for each check.  The google-java-format check is under allow_failures so that contributors aren't required to download and run the tool, but it is easy to see the status of the formatting.
I tested the change with license and formatting errors: https://travis-ci.org/sebright/opencensus-java/builds/356175781
A future improvement would be to move the two checks to the top-level build.gradle.

Simplify example Gradle build file by moving license and format checks to the Travis script.

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

If the trace/span ID is `0L` (resp. `1L`), then Jaeger simply returns `"0"` (resp. `"1"`) via its REST API.
Looking at `TraceId#generateRandomId`/`TraceId#INVALID` and `SpanId#generateRandomId`/`SpanId#INVALID`, it seems `0L` is a forbidden value which is actively filtered out, but anything else has the potential to happen.
Therefore, regexes for trace IDs and span IDs should be `{1,32}` and `{1,16}` respectively.
Improves on #1063.

Jaeger exporter test is now more robust to small IDs.

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

Running `docker -v`, as done before this change, succeeds even when the Docker daemon is down, which means integration tests are attempted even though we cannot start Jaeger's container.
Running `docker version`, as done after this change, checks both the version of the CLI and the daemon, which fails when the daemon is down, and is what we really want here.
Fixes #1066. Improves on #1077.

Run docker version to find whether Jaeger integration test can be performed.

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

This change implements option [1.b.](https://github.com/census-instrumentation/opencensus-java/issues/1066#issuecomment-375554352), in order to make the build more stable for now, while we discuss alternatives mentioned on this comment.
Fixes #1066, particularly, [this issue](https://github.com/census-instrumentation/opencensus-java/issues/1066#issuecomment-375453057) raised by @songy23.

Run jaegertracing/all-in-one:1.2.0 instead of latest.

---

api/src/test/java/io/opencensus/trace/export/NoopSampledSpanStoreTest.java
build.gradle
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
contrib/http_util/src/test/java/io/opencensus/contrib/http/util/CloudTraceFormatTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThreadTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerExportTest.java
findbugs-exclude.xml
impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/propagation/TagContextSerializationTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/SpanImplTest.java

This would have caught the unused variable that was fixed by #1082.
Changes in this commit:
- Enable FindBugs in tests in build.gradle.
- Fix some existing minor FindBugs issues in tests.
- Suppress some warnings in all test classes that are less important in test
code, such as requiring nested classes to be static whenever possible.
- Enable nullness-related FindBugs warnings in tests, since we don't run the
Checker Framework on test code.

Enable FindBugs in tests.

---

README.md

`TagKey.create("my.org/keys/frontend")` throws:
```
WARNING: ApiException thrown when creating MetricDescriptor.
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Field metricDescriptor.labels[0].key had an invalid value of "my.org/keys/frontend": Label key contains invalid characters.
at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:49)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:72)
at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:60)
at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:95)
at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:61)
at …
```

Fix warning-throwing README.md instructions

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

Changelog:
- Wait for Jaeger to be ready by polling it over HTTP rather than waiting an arbitrary amount of time.
- Add unit to all times and durations.
- Fix/improve assertion on span duration.
Fixes #1066, particularly [point 2. in this comment](https://github.com/census-instrumentation/opencensus-java/issues/1066#issuecomment-375554352), i.e. should avoid build failures like https://travis-ci.org/census-instrumentation/opencensus-java/jobs/357147554.

More robust integration test for Jaeger exporter.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

Inspired by https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-logging/src/main/java/com/google/cloud/logging/MonitoredResourceUtil.java.
When creating a `StackdriverStatsExporter`, if users explicitly set a Stackdriver `MonitoredResource`, we will use the given resource for exporting; otherwise, the library will try to create an appropriate `MonitoredResource` based on current environment variables:
- If the process is running in a GKE container, a `gke_container` resource will be used;
- If the process is running on a GCE instance, a `gce_instance` resource will be used;
- Otherwise, the library will use the global resource with no labels.
In the long term, we may want to work with Veneer so that we can use some of their tools to detect the environment. …

Auto detect GCE and GKE Stackdriver MonitoredResources.

---

build.gradle

Make Error Prone and FindBugs annotations 'compileOnly' dependencies.

---

api/src/main/java/io/opencensus/common/Duration.java
api/src/main/java/io/opencensus/common/Timestamp.java
api/src/main/java/io/opencensus/stats/Aggregation.java
api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/main/java/io/opencensus/stats/BucketBoundaries.java
api/src/main/java/io/opencensus/stats/Measure.java
api/src/main/java/io/opencensus/stats/Measurement.java
api/src/main/java/io/opencensus/stats/View.java
api/src/main/java/io/opencensus/stats/ViewData.java
api/src/main/java/io/opencensus/tags/Tag.java
api/src/main/java/io/opencensus/tags/TagKey.java
api/src/main/java/io/opencensus/tags/TagValue.java
api/src/main/java/io/opencensus/trace/Annotation.java
api/src/main/java/io/opencensus/trace/AttributeValue.java
api/src/main/java/io/opencensus/trace/EndSpanOptions.java
api/src/main/java/io/opencensus/trace/Link.java
api/src/main/java/io/opencensus/trace/MessageEvent.java
api/src/main/java/io/opencensus/trace/NetworkEvent.java
api/src/main/java/io/opencensus/trace/config/TraceParams.java
api/src/main/java/io/opencensus/trace/export/RunningSpanStore.java
api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
api/src/main/java/io/opencensus/trace/export/SpanData.java
api/src/main/java/io/opencensus/trace/samplers/ProbabilitySampler.java
build.gradle
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsConfiguration.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java

This change allows the Checker Framework to check the classes annotated with
`@AutoValue`, even though their generated subclasses are skipped.  This commit
also fixes some previously suppressed warnings in the ViewData class.

Suppress Checker Framework warnings in AutoValue generated classes (fixes #917).

---

gradle/errorprone/experimental_warnings

MutableMethodReturnType suggests returning Guava immutable collections from API
methods, but OpenCensus doesn't expose Guava in its API. See
https://github.com/google/error-prone/issues/982.

Turn off Error Prone warning MutableMethodReturnType.

---

build.gradle

Checker Framework 2.4.0 is the second latest version.  The latest, 2.5.0, ends support for annotations in comments (https://github.com/typetools/checker-framework/releases/tag/checker-framework-2.5.0), so we probably can't upgrade further until we can use Java 8 syntax.
This PR also enables `-AinvariantArrays`.

Checker Framework: 2.3.2 -> 2.4.0

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java

Update RPC constants according to [specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/gRPC.md) and our meeting today.
Equivalent changes to OC C++: https://github.com/census-instrumentation/opencensus-cpp/pull/138.

Add new RPC measure and view constants, deprecate old ones.

---

impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java

Before, we didn't error when these were missing.

Makes the trace and span ID fields mandatory in binary format

---

impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java

(cherry picked from commit 3683e6263dbbada41a9f8f72845c19222d05b4fc)
Cherry-picked for v0.12.3 patch release. This issue is blocking our customer.

Substitute non-ascii characters in B3Format header key. (#1072)

---

api/src/main/java/io/opencensus/common/Duration.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/1133.
We have a [limit on seconds](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/common/Duration.java#L44) and [nanoseconds](https://github.com/census-instrumentation/opencensus-java/blob/master/api/src/main/java/io/opencensus/common/Duration.java#L49) for Duration. That range is within (Long.MIN_VALUE, Long.MAX_VALUE) so the conversion should never cause overflow.

Remove java doc about overflow cases in Duration.toMillis().

---

CONTRIBUTING.md
api/src/main/java/io/opencensus/common/Duration.java
api/src/main/java/io/opencensus/common/TimeUtils.java
api/src/main/java/io/opencensus/common/Timestamp.java
api/src/main/java/io/opencensus/internal/Utils.java
api/src/test/java/io/opencensus/common/TimeUtilsTest.java
api/src/test/java/io/opencensus/internal/UtilsTest.java
buildscripts/checkstyle.xml
buildscripts/import-control.xml
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java

This commit uses the Checkstyle ImportControl feature
(http://checkstyle.sourceforge.net/config_imports.html#ImportControl) to specify
the allowed imports for each package.  Specifying imports has several benefits:
- It makes some parts of the design more concrete.  For example, it shows that
`stats` can depend on `tags`, but `tags` shouldn't depend on `stats` or
`trace`.
- We can use it to restrict access to `internal` packages.
- It can help us remove the dependency on Guava incrementally.  For example,
this commit specifies that the API can only depend on
`com.google.common.io.BaseEncoding`, which should help us avoid accidentally
adding more uses of Guava to the API.
One downside is that the check seems to only apply to import statements, not
qualified class names.
This commit …

Control package dependencies with Checkstyle.

---

CHANGELOG.md
CONTRIBUTING.md

Most of the entries are copied from the GitHub releases page or commit messages.

Add a Markdown changelog, starting at version 0.9.0 (closes #945).

---

api/src/main/java/io/opencensus/trace/BlankSpan.java
api/src/main/java/io/opencensus/trace/Span.java
api/src/test/java/io/opencensus/trace/NoopSpan.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanImpl.java

This PR adds null checking to classes that implement Span. Specifically,
- `BlankSpan`
- `NoopSpan`
- `Span`
- `SpanImpl`
For the latter, I had to use `Preconditions.checkNotNull` because `io.opencensus.internal` shouldn't be imported into `ImplCore`.
Let me know if you have any questions!

#785 - Check for null status/annotations/etc in Span

---

examples/BUILD.bazel
examples/README.md
examples/build.gradle
examples/pom.xml
examples/src/main/java/io/opencensus/examples/tags/TagContextExample.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/1154.

Rename StatsRunner to TagContextExample because it's more about TagContext.

---

api/src/main/java/io/opencensus/stats/Aggregation.java
api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/main/java/io/opencensus/stats/ViewData.java
api/src/test/java/io/opencensus/stats/AggregationDataTest.java
api/src/test/java/io/opencensus/stats/AggregationTest.java
api/src/test/java/io/opencensus/stats/ViewDataTest.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/StatszZPageHandler.java
contrib/zpages/src/test/java/io/opencensus/contrib/zpages/StatszZPageHandlerTest.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptor.java
exporters/stats/signalfx/src/test/java/io/opencensus/exporter/stats/signalfx/SignalFxSessionAdaptorTest.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/test/java/io/opencensus/implcore/stats/MutableAggregationTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsTestUtil.java
impl_core/src/test/java/io/opencensus/implcore/stats/ViewManagerImplTest.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/1047.
Add Aggregation.LastValue and AggregationData.LastValueData to support Gauge, according to the design doc and [OpenCensus-specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/DataAggregation.md#aggregation).
Might be easier to review by each commit. ~~I'll post a follow-up PR to support LastValue/LastValueData for zpage and exporters.~~

Add Aggregation.LastValue and AggregationData.LastValueData to support Gauge

---

CHANGELOG.md
exporters/stats/prometheus/README.md
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java

Closes https://github.com/census-instrumentation/opencensus-java/issues/1164.
Previously we don't set the bucket bounds for Prometheus `Sample`s, since bucket bounds is a [built-in feature](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/Histogram.java#L329) for Prometheus Histogram. However, as https://github.com/census-instrumentation/opencensus-java/issues/1164 suggested, we can manually set the bucket bounds with the same label `le` that the built-in Histogram uses, to achieve the same output as the built-in Prometheus Histogram `Sample`s.
Prometheus metrics page with this change:
Which is the expected output for https://github.com/census-instrumentation/opencensus-java/issues/1164.

Set bucket bounds as le labels for Prometheus exporter.

---

CHANGELOG.md

Should be submitted after https://github.com/census-instrumentation/opencensus-java/pull/1173.

Update CHANGELOG about v0.13.1 release.

---

api/src/main/java/io/opencensus/common/Functions.java
contrib/zpages/src/main/java/io/opencensus/contrib/zpages/TracezZPageHandler.java
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java

The Checker Framework didn't detect this error, because the method used
`@SuppressWarnings("unchecked")` for a different reason.
This commit also fixes a potential NPE in ZipkinExporterHandler.

Add missing Nullable annotation to Functions.returnNull().

---

api/src/main/java/io/opencensus/stats/NoopStats.java
build.gradle
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java

2.5.1 includes a fix for
https://github.com/typetools/checker-framework/issues/1838.  This commit also
adds a few more `@Nullable` annotations that are required now.

Checker Framework: 2.5.0 -> 2.5.1

---

impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java

This PR fixes a nullness warning by splitting the constructor into a factory method and a constructor, to ensure that the DisruptorEventQueue is fully initialized before any events are enqueued.  It also fixes a varargs warning by creating an explicit array.

Remove warning suppression in DisruptorEventQueue.

---

api/src/main/java/io/opencensus/trace/Status.java

This method is already used by the Stackdriver stats exporter to convert status
types, so it should be part of the API.

Remove PublicForTesting from Status.CanonicalCode.toStatus() (fixes #976).

---

CHANGELOG.md
api/src/main/java/io/opencensus/common/Duration.java
api/src/test/java/io/opencensus/common/DurationTest.java

Fixes #1179.  Throwing IllegalArgumentException for invalid arguments is more
consistent with the rest of the opencensus-java API.

Throw IllegalArgumentException when Duration.create receives invalid arguments.

---

CHANGELOG.md
api/src/main/java/io/opencensus/common/Timestamp.java
api/src/test/java/io/opencensus/common/TimestampTest.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

Throwing IllegalArgumentException for invalid arguments is more consistent with
the rest of the opencensus-java API.  This commit also fixes a test that created
an invalid Timestamp.
___________________________________________________________________
This change is similar to #1198, but applied to Timestamp.  @songy23 is this the correct fix for StackdriverExportUtilsTest?

Throw IllegalArgumentException when Timestamp.create receives invalid arguments.

---

api/src/main/java/io/opencensus/stats/metrics/package-info.java

Add package info first, will send separate PRs that implement each of the data types in [metrics.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto).

Starts adding a metrics package.

---

exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1218.
So that the span that instruments stats exporter should have the same sampling probability to that of [trace exporters](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java#L72), instead of always being sampled.
/cc @odeke-em

 Overwrite the sampling probability to default for stats exporters.

---

contrib/agent/src/main/java/io/opencensus/contrib/agent/Settings.java

This constructor is only made public for testing within the project, so it
should have an `@Internal` annotation to show that it is not part of the API.
_____________________________________________________________
@ubschmidt2 Is this change correct, or should the Settings constructor be considered part of the API?

Add @Internal to io.opencensus.contrib.agent.Settings constructor (issue #977).

---

.travis.yml

Bazel just released a new version today and that broke our build. Disable bazel build target temporarily, we can re-enable example-bazel build using a stable version later (tracked in https://github.com/census-instrumentation/opencensus-java/issues/1228).

Temporarily disable example-bazel build for Travis CI.

---

exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java

* Change to use the new Span.Kind.
* In SD add Sent/Recv based on Span.Kind.
* In Zipkin/Instana use this to determine the kind of the Span in the backend format.
* Cleanup usage of the deprecated NetworkEvents.
* Make static final immutable fields in tests.
Fixes https://github.com/census-instrumentation/opencensus-java/issues/1054

Cleanup trace exporters.

---

CHANGELOG.md
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java

Related to https://github.com/census-instrumentation/opencensus-specs/pull/120.
Client/server started_rpcs are required by gRPC, add them back to RPC constants.
/cc @zhangkun83

Add started_rpcs measures and views to RPC constants.

---

build.gradle
buildscripts/import-control.xml
metrics/README
metrics/README.md
metrics/build.gradle
metrics/src/main/java/io/opencensus/metrics/package-info.java
settings.gradle

I haven't added this artifact to `build.gradle` or `setting.gradle` since it doesn't have any classes yet, and the `javaDoc` task will fail (I haven't found a way to disable this task).

Metrics: Move Metrics to a separate artifact.

---

buildscripts/checkstyle.xml

The `VariableDeclarationUsageDistance` rules restricts the distance between variable declaration and its first usage to 3 lines. In my opinion it's not useful, especially in unit tests where we define all the variables first.

Remove Checkstyle rule VariableDeclarationUsageDistance

---

examples/build.gradle
examples/pom.xml

gRPC no longer shades the netty dependency `netty-tcnative-boringssl-static` in their latest release, but it is required by the cloud client libraries. We need to explicitly add runtime dependency of it to make example work.
Thanks @zhengyr for reporting this.

Examples: add runtime dependency on netty-tcnative-boringssl-static.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java

This one is for Stackdriver Stats Exporter.

Stackdriver Stats Exporter: remove unnecessary SuppressWarnings.

---

CHANGELOG.md
contrib/monitored_resource_util/src/main/java/io/opencensus/contrib/monitoredresource/util/MonitoredResource.java
contrib/monitored_resource_util/src/test/java/io/opencensus/contrib/monitoredresource/util/MonitoredResourceTest.java

To make the unit tests of other libraries that depend on `monitored-resource-utils` easier to write.

Expose the factory methods of MonitoredResource.

---

buildscripts/import-control.xml
exporters/trace/stackdriver/build.gradle
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

Resource labels are consistent with [Specs](https://github.com/census-instrumentation/opencensus-specs/blob/master/utils/MonitoredResource.md). The format of label key is `g.co/r/<resource_type>/<label>`, for example `g.co/r/aws_ec2_instance/aws_account`.

Stackdriver Trace Exporter: add resource labels to Spans.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

From https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries#point:
> For GAUGE metrics, only the end time of the interval is used. 
Equivalent to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/18.

Stackdriver Stats Exporter: don't set StartTime for Gauge values.

---

contrib/log_correlation/stackdriver/build.gradle
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

The full name of the property is
`io.opencensus.contrib.logcorrelation.stackdriver.OpenCensusTraceLoggingEnhancer.spanSelection`.
It can be set in logging.properties or set as a system property.
Allowed values for spanSelection:
NO_SPANS: disables the log correlation feature
ALL_SPANS: adds tracing data to all log entries
SAMPLED_SPANS: adds tracing data to log entries when the current span is sampled
SAMPLED_SPANS is the default.
_______________________________________________________________________
I'm not sure if this is the best way to allow configuration of the `spanSelection` field.  My goal is to make it work with as many logging frameworks as possible that could be used in combination with google-cloud-logging, though I've only tested it with Logback and java.util.logging so far. …

Add ALL_SPANS/NO_SPANS/SAMPLED_SPANS property to OpenCensusTraceLoggingEnhancer.

---

contrib/log_correlation/stackdriver/README.md
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

Three commits:
This commit changes the label key from "sampled" to "openCensusTraceSampled".
The new name is more descriptive and less likely to conflict with other labels
on log entries.
This constructor is better than the no-arg constructor for situations where a
no-arg constructor is not required, e.g., when reflection is not used.

Document and clean up opencensus-contrib-log-correlation-stackdriver.

---

metrics/src/main/java/io/opencensus/metrics/LabelKey.java
metrics/src/main/java/io/opencensus/metrics/LabelValue.java
metrics/src/test/java/io/opencensus/metrics/LabelKeyTest.java
metrics/src/test/java/io/opencensus/metrics/LabelValueTest.java
settings.gradle

Add LabelKey and LabelValue classes based on [metrics.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto). I think these two classes should have been finalized.
Both classes are marked as `ExperimentalApi` for now.

Metrics: Add LabelKey and LabelValue.

---

api/src/main/java/io/opencensus/stats/ViewData.java
api/src/test/java/io/opencensus/stats/ViewDataTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1265.
When there's a mismatch between `Aggregation` - `AggregationData` or `Window` - `WindowData`, all we care about is their types. Only include the subclass name in the error message instead of calling the `toString` method to reduce overhead.
/cc @steveniemitz

Stats: Only include the simple class name in the error message for ViewData.check methods.

---

build.gradle

Note that recently a bunch of former beta client libraries (including Cloud Monitoring) have changed to a different version set since they are moving from beta to GA:
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.cloud%22%20AND%20a%3A%22google-cloud-monitoring%22
Also see https://github.com/GoogleCloudPlatform/google-cloud-java#google-cloud-client-library-for-java.

Update Google Cloud version.

---

api/src/main/java/io/opencensus/common/ServerStats.java
api/src/main/java/io/opencensus/common/ServerStatsDeserializationException.java
api/src/main/java/io/opencensus/common/ServerStatsEncoding.java
api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
api/src/test/java/io/opencensus/common/ServerStatsEncodingTest.java
api/src/test/java/io/opencensus/common/ServerStatsFieldEnumsTest.java
api/src/test/java/io/opencensus/common/ServerStatsTest.java

Encoder/decoder for Server Stats as per the [spec](https://github.com/census-instrumentation/opencensus-specs/blob/master/encodings/CensusServerStatsEncoding.md).

Summary Span: Add encoder/decoder for Server Stats.

---

metrics/src/main/java/io/opencensus/metrics/Distribution.java
metrics/src/main/java/io/opencensus/metrics/Point.java
metrics/src/main/java/io/opencensus/metrics/Utils.java
metrics/src/main/java/io/opencensus/metrics/Value.java
metrics/src/test/java/io/opencensus/metrics/DistributionTest.java
metrics/src/test/java/io/opencensus/metrics/PointTest.java
metrics/src/test/java/io/opencensus/metrics/ValueTest.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1261.~~
From [metrics.proto](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto):
```
// A timestamped measurement.
message Point {
// The moment when this point was recorded.
google.protobuf.Timestamp timestamp = 1; // required
// The actual point value.
oneof value {
// A 64-bit integer.
int64 int64_value = 2;
// A 64-bit double-precision floating-point number.
double double_value = 3;
// A distribution value.
DistributionValue distribution_value = 4;
// TODO: Add support for Summary type. This is an aggregation that produces
// percentiles directly.
//
// See also: https://prometheus.io/docs/concepts/metric_types/#summary
}
}
// Distribution …
```

Metrics:  Add Value and Point.

---

CHANGELOG.md
api/src/main/java/io/opencensus/stats/MeasureMap.java
api/src/main/java/io/opencensus/stats/NoopStats.java
api/src/test/java/io/opencensus/stats/NoopStatsTest.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapInternal.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java

Add a builder API that supports attaching contextual information of exemplars to measure maps. This should make the API easier to use, compared to overloading and having multiple versions of record (https://github.com/census-instrumentation/opencensus-java/pull/1284).
To do next (in another PR): add the Exemplar class, record and store Exemplars in impl.
/cc @rghetia

Stats: Add API MeasureMap.putAttachment() for recording exemplars.

---

api/src/main/java/io/opencensus/stats/AggregationData.java
api/src/test/java/io/opencensus/stats/AggregationDataTest.java

[Proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L236-L250):
```
// Exemplars are example points that may be used to annotate aggregated
// Distribution values. They are metadata that gives information about a
// particular value added to a Distribution bucket.
message Exemplar {
// Value of the exemplar point. It determines which bucket the exemplar
// belongs to.
double value = 1;
// The observation (sampling) time of the above value.
google.protobuf.Timestamp timestamp = 2;
// Contextual information about the example value.
map<string, string> attachments = 3;
}
```
Next step: record and store the `Exemplar`s in the impl (in another PR).

Stats: Add Exemplar class to DistributionData.

---

README.md

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1286.
Definition of [Alpha](https://github.com/GoogleCloudPlatform/google-cloud-java#versioning) quality level:
> Alpha: Libraries defined at an Alpha quality level are still a work-in-progress and are more likely to get backwards-incompatible updates. Additionally, it's possible for Alpha libraries to get deprecated and deleted before ever being promoted to Beta or GA.
Definition of [Beta](https://github.com/GoogleCloudPlatform/google-cloud-java#versioning) quality level:
> Beta: Libraries defined at a Beta quality level are expected to be mostly stable and we're working towards their release candidate. We will address issues and requests with a higher priority.
~~I think it's time to call OpenCensus-Java a Beta-stage …

Readme: Update library stage to Beta.

---

metrics/src/main/java/io/opencensus/metrics/TimeSeries.java
metrics/src/main/java/io/opencensus/metrics/Utils.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesTest.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1263.~~
[Proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L107-L132):
```
// A collection of data points that describes the time-varying values
// of a gauge metric.
message GaugeTimeSeries {
// The set of label values that uniquely identify this timeseries. Applies to
// all points. The order of label values must match that of label keys in the
// metric descriptor.
repeated LabelValue label_values = 1;
// The data points of this timeseries. Point type MUST match the MetricDescriptor.type.
repeated Point points = 2;
}
// A collection of data points that describes the time-varying values
// of a cumulative metric.
message …
```

Metrics: Add TimeSeries.

---

metrics/src/main/java/io/opencensus/metrics/MetricDescriptor.java
metrics/src/test/java/io/opencensus/metrics/MetricDescriptorTest.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesTest.java

[Proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L54-L96):
```proto
// Defines a metric type and its schema.
message MetricDescriptor {
// The metric type, including its DNS name prefix. It must be unique.
string name = 1;
// A detailed description of the metric, which can be used in documentation.
string description = 2;
// The unit in which the metric value is reported. Follows the format
// described by http://unitsofmeasure.org/ucum.html.
string unit = 3;
// The kind of metric. It describes how the data is reported.
//
// A gauge is an instantaneous measurement of a value.
//
// A cumulative measurement is a value accumulated over a time interval. In
// a time series, cumulative measurements should …
```

Metrics: Add MetricDescriptor.

---

CHANGELOG.md

Related to https://github.com/census-instrumentation/opencensus-java/pull/1295. This is a user-visible change so I think we should add a record in CHANGELOG.
/cc @adamgarza

Add ZPage updates to CHANGELOG.

---

README.md

Add specification on Bazel build so that it's easier for Bazel users to try out OpenCensus-Java.

Add specification on Bazel build in README.

---

README.md
examples/src/main/java/io/opencensus/examples/helloworld/QuickStart.java

Three commits:
Changes in this commit:
- Remove use of deprecated AggregationWindow.
- Make methods public to show that they could be called by code that isn't part of the example.
- Rename the class for consistency with the tracing example.
- Run google-java-format.

Update and add imports to examples in readme.

---

exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java

Fixing #1307.
Prometheus uses cumulative values in the histogram buckets thus the buckets from OpenCensus `Distribution` needs to be summarized as they are exported to Prometheus. Otherwise the built-in functions in Prometheus, e.g., `histogram_quantile`, wont work as expected.

Export cumulative buckets for Prometheus

---

metrics/src/main/java/io/opencensus/metrics/TimeSeries.java
metrics/src/main/java/io/opencensus/metrics/TimeSeriesCumulative.java
metrics/src/main/java/io/opencensus/metrics/TimeSeriesGauge.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesCumulativeTest.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesGaugeTest.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesTest.java

To make APIs more consistent with the [proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L101-L126).

Metrics: Move TimeSeriesCumulative and TimeSeriesGauge to top level. Hide TimeSeries.

---

metrics/src/main/java/io/opencensus/metrics/TimeSeriesList.java
metrics/src/test/java/io/opencensus/metrics/TimeSeriesListTest.java

[Proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L32-L45):
```proto
...
// One or more timeseries for a single metric, where each timeseries has
// one or more points. The type of the timeseries must match
// metric_descriptor.type, so only one of the two should be populated.
repeated GaugeTimeSeries gauge_timeseries = 2;
repeated CumulativeTimeSeries cumulative_timeseries = 3;
```

Metrics: Add TimeSeriesList.

---

metrics/src/main/java/io/opencensus/metrics/Metric.java
metrics/src/test/java/io/opencensus/metrics/MetricTest.java

[Proto definition](https://github.com/census-instrumentation/opencensus-proto/blob/master/opencensus/proto/stats/metrics/metrics.proto#L32-L45):
```proto
// Defines a Metric which has one or more timeseries.
message Metric {
// The definition of the Metric. For now, we send the full MetricDescriptor
// every time in order to keep the protocol stateless, but this is one of the
// places where we can make future changes to make the protocol more
// efficient.
MetricDescriptor metric_descriptor = 1;
// One or more timeseries for a single metric, where each timeseries has
// one or more points. The type of the timeseries must match
// metric_descriptor.type, so only one of the two should be populated.
repeated GaugeTimeSeries gauge_timeseries = 2;
repeated CumulativeTimeSeries …
```

Metrics: Add Metric.

---

CHANGELOG.md
api/src/main/java/io/opencensus/trace/config/TraceParams.java
api/src/test/java/io/opencensus/trace/config/TraceParamsTest.java

Per Specs: https://github.com/census-instrumentation/opencensus-specs/pull/139.

Tracing: Reduce default limit on Links to 32.

---

.travis.yml

This reverts commit 8ab1628f4daad0489c41f2c9ac96085a7948e84d.
The Bazel build is passing again, so this commit removes it from
'allow_failures'.  Fixes #1228.

Revert "Temporarily disable example-bazel build for Travis CI. (#1229)"

---

all/build.gradle

I didn't add opencensus-metrics to subprojects_javadoc, because I didn't want the Javadocs to be published before the artifact is released.

Add opencensus-metrics to all/build.gradle.

---

README.md

Before there are two sections in README on adding OpenCensus dependencies to users' project. I think they are somewhat duplicated. In addition the first section doesn't mention the `impl` dependency, and that has caused confusion to users. Update README to keep one section on dependency instead.

Update 'Add dependencies' section in README.

---

buildscripts/import-control.xml

`metrics` should not depend on `stats` or `tags`. Instead `stats` should depend on `metrics`.

Update import control.

---

api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
api/src/main/java/io/opencensus/trace/SpanBuilder.java
build.gradle
buildscripts/checkstyle.xml
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringAspect.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/Handler.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java

709d97aa321d5729988fd63b960bbece04cfba10 modified the -AskipDefs argument to the
Checker Framework (a regular expression) in a way that caused it to skip
checking all files.  This commit fixes the regular expression and the new
Checker Framework warnings.

Fix incorrect argument to Checker Framework, and fix nullness warnings.

---

exporters/stats/stackdriver/README.md

The Stackdriver Monitoring service tier is going away: https://cloud.google.com/monitoring/accounts/tiers.
Related to https://github.com/census-instrumentation/opencensus-go/issues/853.

Update README of Stackdriver stats exporter.

---

api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
checker-framework/stubs/grpc.astub

The stub file adds Nullable annotations to indicate that Context.Key.get can
return null when the key has no default or the key has a nullable value type.

Add Checker Framework stub file for gRPC Context.Key.

---

api/src/main/java/io/opencensus/trace/SpanBuilder.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/646
Thanks @adriancole for reporting this a while ago.

Add a warning about try-with-resource to auto-close spans.

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1350
Equivalent to https://github.com/census-instrumentation/opencensus-go/pull/583.

Allow users to use custom metric name prefix for Stackdriver

---

buildscripts/import-control.xml
impl_core/build.gradle
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/MetricMap.java
impl_core/src/main/java/io/opencensus/implcore/stats/MetricUtils.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableAggregation.java
impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/test/java/io/opencensus/implcore/stats/MetricMapTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/MetricUtilsTest.java

Support recording `Metric`s in stats impl. This works as the following:
- When a `View` is registered, convert that `View` to a `MetricDescriptor` and register it;
- When a `Measurement` along with a `TagContext` are recorded, convert them into a data row consisting of `LabelValue`s and `Point`s;
- If `getMetrics()` is called, convert the `MetricDescriptor`s and data rows into `Metric`s. Then flush all data rows.
This PR only contains internal support in the impl. None of these changes are user-visible yet.
Next step: implements `MetricProducer` interface so that the stored `Metric`s can be exposed.

Metrics: Produce and store Metrics in Stats impl.

---

CHANGELOG.md
api/src/main/java/io/opencensus/trace/SpanContext.java
api/src/main/java/io/opencensus/trace/Tracestate.java
api/src/test/java/io/opencensus/trace/SpanContextTest.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/BinaryPropagationImplBenchmark.java
contrib/appengine_standard_util/src/main/java/io/opencensus/contrib/appengine/standard/util/AppEngineCloudTraceContextUtils.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/util/CloudTraceFormat.java
impl_core/src/main/java/io/opencensus/implcore/trace/SpanBuilderImpl.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/B3Format.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java

One caveat in this PR: Tracestate name seems to not be consistent with the other class names. Maybe TraceState is better (just want to have others opinion).

Add Tracestate into SpanContext.

---

api/src/main/java/io/opencensus/common/ServerStatsFieldEnums.java
api/src/main/java/io/opencensus/stats/BucketBoundaries.java
api/src/main/java/io/opencensus/trace/NetworkEvent.java
api/src/main/java/io/opencensus/trace/Span.java
api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java
api/src/main/java/io/opencensus/trace/propagation/BinaryFormat.java
build.gradle
buildscripts/checkstyle.xml
buildscripts/kokoro/linux_presubmit.sh
contrib/grpc_util/src/main/java/io/opencensus/contrib/grpc/util/StatusConverter.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringAspect.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/CensusSpringSqlAspect.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/aop/Traced.java
scripts/travis_script

This commit also merges new changes to checkstyle.xml and fixes new checkstyle
warnings related to Javadocs.
________________________________________________________________________________
This upgrade seems to fix a bug in parsing Javadocs where a `@value` tag is split between two lines.

checkstyle: 8.0 -> 8.12

---

api/build.gradle
contrib/agent/build.gradle
contrib/exemplar_util/build.gradle
contrib/grpc_metrics/build.gradle
contrib/grpc_util/build.gradle
contrib/http_util/build.gradle
contrib/log_correlation/stackdriver/build.gradle
contrib/monitored_resource_util/build.gradle
contrib/spring/build.gradle
exporters/stats/prometheus/build.gradle
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/signalfx/build.gradle
exporters/stats/signalfx/src/main/java/io/opencensus/exporter/stats/signalfx/SignalFxStatsExporterWorkerThread.java
exporters/stats/stackdriver/build.gradle
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/trace/instana/build.gradle
exporters/trace/jaeger/build.gradle
exporters/trace/logging/build.gradle
exporters/trace/stackdriver/build.gradle
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/zipkin/build.gradle
impl/build.gradle
impl_core/build.gradle
impl_lite/build.gradle
testing/build.gradle

gRPC updated to java7/android14 for io.context and all their artifacts see https://github.com/grpc/grpc-java/pull/4727
Currently we still cannot use try-with-resources (android 19) or ThreadLocalRandom (android 21).

 Update all targets to at least java7 and android14

---

CHANGELOG.md
findbugs-exclude.xml
impl_core/src/main/java/io/opencensus/implcore/stats/CurrentStatsState.java
impl_core/src/main/java/io/opencensus/implcore/stats/StatsComponentImplBase.java

Alternative implementation of the https://github.com/census-instrumentation/opencensus-java/pull/1376 that does not change the API behavior.
Also this PR fixes an undefined behavior when setState is called. Previously if 2 threads call setStats the current library state and the view manager state can be inconsistent.

Implement CurrentStatsState using atomic variables.

---

CHANGELOG.md
api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/test/java/io/opencensus/trace/TraceOptionsTest.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/trace/propagation/BinaryPropagationImplBenchmark.java
exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/propagation/BinaryFormatImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/B3FormatTest.java
impl_core/src/test/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplTest.java

Related to @zhangkun83's comment about using "byte[]" from https://github.com/census-instrumentation/opencensus-java/pull/197

Add get/from{Byte} methods on TraceOptions and deprecate get/from{Bytes}.

---

api/src/main/java/io/opencensus/internal/Utils.java
api/src/main/java/io/opencensus/stats/Measure.java
api/src/main/java/io/opencensus/tags/TagKey.java
api/src/main/java/io/opencensus/tags/TagValue.java
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/main/java/io/opencensus/trace/Tracestate.java
api/src/test/java/io/opencensus/internal/UtilsTest.java
build.gradle
findbugs-exclude.xml

This improves performance significantly for our propagations:
Before (mean latency):
propagation.B3FormatImplBenchmark.extract  sample  163623       1993.963 ±   61.193  ns/op
After (mean latency):
propagation.B3FormatImplBenchmark.extract  sample  142707        174.384 ±    26.763  ns/op

Avoid doing string formatting when calling checkArgument.

---

api/src/main/java/io/opencensus/internal/Utils.java
api/src/main/java/io/opencensus/stats/Measure.java
api/src/main/java/io/opencensus/tags/TagKey.java
api/src/main/java/io/opencensus/tags/TagValue.java
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/main/java/io/opencensus/trace/Tracestate.java
api/src/test/java/io/opencensus/internal/UtilsTest.java
build.gradle
findbugs-exclude.xml

(cherry picked from commit eabc800c3749ca6f8e3a17f057ae11c8d1385d0c)
Manual edits compared to https://github.com/census-instrumentation/opencensus-java/commit/eabc800c3749ca6f8e3a17f057ae11c8d1385d0c:
1. Remove `Tracestate` since it's not there in v0.15;
2. Use `new TraceOptions(buffer[0])` instead of `fromByte(buffer[0])`, since `fromByte` is not there in v0.15.

Avoid doing string formatting when calling checkArgument. (#1394)

---

api/build.gradle
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/main/java/io/opencensus/trace/internal/LowerCaseBase16Encoding.java
api/src/test/java/io/opencensus/trace/internal/LowerCaseBase16EncodingTest.java
buildscripts/import-control.xml
contrib/grpc_metrics/build.gradle
exporters/stats/prometheus/build.gradle
exporters/stats/signalfx/build.gradle
exporters/stats/stackdriver/build.gradle
exporters/trace/instana/build.gradle
exporters/trace/jaeger/build.gradle
exporters/trace/stackdriver/build.gradle
exporters/trace/zipkin/build.gradle
testing/build.gradle

Copied the BaseEncoding class for base16 from Guava (including tests).
/cc @saturnism
EDIT: fixes https://github.com/census-instrumentation/opencensus-java/issues/1081

Remove guava dependency from the API artifact.

---

contrib/agent/src/integration-test/java/io/opencensus/contrib/agent/instrumentation/ThreadInstrumentationIT.java

Part of https://github.com/census-instrumentation/opencensus-java/issues/1407.

Contrib/agent: detach() should take the context returned from attach().

---

contrib/log_correlation/log4j2/README.md
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java

For example, this commit renames "openCensusTraceId" to "opencensusTraceId".

Log4j log correlation: Capitalize "opencensus" as one word in context key names.

---

buildscripts/import-control.xml
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java

This commit adds the internal package to import-control.xml and removes the use
of org.apache.logging.log4j.core.impl.ThreadContextDataInjector.

Avoid using internal org.apache.logging.log4j.core.impl package.

---

CONTRIBUTING.md
all/build.gradle
api/build.gradle
benchmarks/README.md
benchmarks/build.gradle
build.gradle
contrib/agent/build.gradle
impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/B3FormatImplBenchmark.java
impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/BinaryFormatImplBenchmark.java
impl_core/src/jmh/java/io/opencensus/implcore/trace/propagation/TextFormatBenchmarkBase.java

Main pros:
* Use the same version across all artifacts (for example agent was using jmh 1.19);
* Allow to easily create/add benchmarks in every artifact (allows access to package protected classes for example the propagation implementations);

Make jmh available for all subprojects.

---

buildscripts/import-control.xml
checker-framework/stubs/log4j.astub
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationAllSpansTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java

This commit improves the thread safety of OpenCensusTraceContextDataInjector by
following the thread safety requirements in the Javadocs of the overridden
methods from ContextDataInjector.  It also handles the possibility of
ThreadContext.getThreadContextMap() returning null by adding a Nullable
annotation in a Checker Framework stub file and adding null checks to the code.
________________________________________________________________________________
I'm not sure if there is a good way to test the thread safety, since it depends on the behavior of Log4j.

Improve implementation of OpenCensusTraceContextDataInjector.

---

CHANGELOG.md
build.gradle

This pull request depends on #1413 and #1414.

Add opencensus-contrib-log-correlation-log4j2 to the list of released artifacts.

---

RELEASING.md

Now protected branches can be specified with a pattern, so we can protect all
release branches with one rule. See
https://help.github.com/articles/about-protected-branches/.  There is no need to
enable branch protection when making a release.

Update release instructions for new Github branch protection rules.

---

RELEASING.md

Some directory names were changed, so the list of readmes in RELEASING.md needed
to be updated.

Update directory names in RELEASING.md.

---

contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java

Fixes #1436.
Log4j's SortedArrayStringMap can contain Object values, but
`SortedArrayStringMap.getValue` has signature `<V> V getValue(String key)` and
unsafely casts the Objects to type `V`.  When the OpenCensus ContextDataInjector
returned a SortedArrayStringMap, and then a Log4j ContextMapLookup looked up
values as Strings to insert them into log entries
(https://github.com/apache/logging-log4j2/blob/fa27894c13c3890e4ae545f6b6365ea2e159757c/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/ContextMapLookup.java#L58),
it resulted in a ClassCastException.
This commit fixes the ClassCastException by only inserting String values into
the Log4j SortedArrayStringMap.

Fix ClassCastException in opencensus-contrib-log-correlation-log4j2.

---

contrib/log_correlation/log4j2/README.md

This PR depends on https://github.com/census-ecosystem/opencensus-experiments/pull/63.

Update links to Log4j log correlation demo.

---

contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java

Fixes #1436.
Log4j's SortedArrayStringMap can contain Object values, but
`SortedArrayStringMap.getValue` has signature `<V> V getValue(String key)` and
unsafely casts the Objects to type `V`.  When the OpenCensus ContextDataInjector
returned a SortedArrayStringMap, and then a Log4j ContextMapLookup looked up
values as Strings to insert them into log entries
(https://github.com/apache/logging-log4j2/blob/fa27894c13c3890e4ae545f6b6365ea2e159757c/log4j-core/src/main/java/org/apache/logging/log4j/core/lookup/ContextMapLookup.java#L58),
it resulted in a ClassCastException.
This commit fixes the ClassCastException by only inserting String values into
the Log4j SortedArrayStringMap.
(cherry picked from commit 7aab20a9704ceb544bdb01974134c56c7aedc0f2)

Fix ClassCastException in opencensus-contrib-log-correlation-log4j2. (v0.16.x)

---

CHANGELOG.md
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java

There may be cases where you want to be able to configure aspects of the HttpSender, like adding headers or authentication.
This will allow the exporter to use a sender with those configurations when the default isn't enough

Pass a preconfigured HttpSender to the trace exporter

---

RELEASING.md
examples/BUILD.bazel
examples/opencensus_workspace.bzl

This commit also sets the version of the com.google.guava:guava-jdk5 artifact in
the generate_workspace command and removes the
com_fasterxml_jackson_core_jackson_core dependency from BUILD.bazel.

Update release version for Bazel build files.

---

.travis.yml

I've seen a bunch of build failures for JDK9 build in Travis. For example https://travis-ci.org/census-instrumentation/opencensus-java/jobs/430817764:
> Could not unzip /home/travis/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip to /home/travis/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t.
Reason: /home/travis/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip (Permission denied)
Exception in thread "main" java.io.FileNotFoundException: /home/travis/.gradle/wrapper/dists/gradle-4.9-bin/e9cinqnqvph59rr7g70qubb4t/gradle-4.9-bin.zip (Permission denied)
at java.base/java.io.RandomAccessFile.open0(Native Method)
at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:343)
at …

Travis: Temporarily disable JDK 9 build.

---

contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/TestSpan.java

This commit adds unit tests for
OpenCensusTraceContextDataInjector.rawContextData().  It also makes two
other minor improvements to the Log4j log correlation tests:
- Puts TestSpan in a separate file for reuse.
- Explicitly sets the SpanSelection in tests, where possible.
_______________________________________________________________________
~~This PR depends on #1413 and includes it.~~

Improve tests for OpenCensusTraceContextDataInjector.

---

contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/TestSpan.java

This commit adds unit tests for
OpenCensusTraceContextDataInjector.rawContextData().  It also makes several
other minor improvements to the Log4j log correlation tests:
- Puts TestSpan in a separate file for reuse.
- Explicitly sets the SpanSelection in tests, where possible.
- Simplifies the tests by calling ReadOnlyStringMap.toMap().
(cherry picked from commit ba5b8310495939a2912934836283ca356b353580)
____________________________________________________________________________
This PR improves the tests on the release branch so that all tests run if any fixes need to be applied to the released version of opencensus-contrib-log-correlation-log4j2.

Improve tests for OpenCensusTraceContextDataInjector. (v0.16.x)

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

 Monitored Resource: replace gke_container with k8s_container in SD exporter

---

RELEASING.md
buildscripts/import-control.xml
exporters/trace/ocagent/build.gradle
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/TraceProtoUtils.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtilsTest.java

Updates https://github.com/census-instrumentation/opencensus-java/issues/1408.
Add utilities for detecting and creating Node.
Equivalent to https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/nodeinfo.go.

Exporter/OCAgent: Add OcAgentNodeUtils.

---

build.gradle
buildscripts/import-control.xml
exporters/trace/ocagent/build.gradle
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImplTest.java

This fake server will be used to test against the clients in https://github.com/census-instrumentation/opencensus-java/pull/1476.
Equivalent to https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/master/mock_agent_test.go.

Testing: Add a fake implementation of TraceService.

---

api/src/main/java/io/opencensus/metrics/export/Metric.java
api/src/test/java/io/opencensus/metrics/export/MetricTest.java
contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
impl_core/src/main/java/io/opencensus/implcore/metrics/Gauge.java
impl_core/src/main/java/io/opencensus/implcore/metrics/LongGaugeImpl.java
impl_core/src/test/java/io/opencensus/implcore/metrics/GaugeTest.java
impl_core/src/test/java/io/opencensus/implcore/metrics/LongGaugeImplTest.java

Metrics/Metric: Add a version of create that accepts only one timeseries.

---

api/src/main/java/io/opencensus/common/ToDoubleFunction.java
api/src/main/java/io/opencensus/metrics/DerivedDoubleGauge.java
api/src/main/java/io/opencensus/metrics/DerivedLongGauge.java
api/src/test/java/io/opencensus/metrics/DerivedDoubleGaugeTest.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedDoubleGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedLongGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DoubleGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/LongGaugeImpl.java
impl_core/src/test/java/io/opencensus/implcore/metrics/DerivedDoubleGaugeImplTest.java

This is the last installment in Gauges API. 
**Gauge API : Add LongGauge Support (Part1)**  https://github.com/census-instrumentation/opencensus-java/pull/1489
**Gauge API : Add DoubleGauge Support (Part2)** https://github.com/census-instrumentation/opencensus-java/pull/1496
**Gauge API : Add support for DerivedLongGauge (Part3)** https://github.com/census-instrumentation/opencensus-java/pull/1497

Gauge API : Add support for DerivedDoubleGauge

---

api/src/main/java/io/opencensus/metrics/export/TimeSeries.java
api/src/test/java/io/opencensus/metrics/export/TimeSeriesTest.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedDoubleGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedLongGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DoubleGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/LongGaugeImpl.java

TimeSeries/Create: Avoid re-evaluate the labelValues all the time

---

buildscripts/import-control.xml
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorker.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExporterWorkerTest.java

Dependency on https://github.com/census-instrumentation/opencensus-java/pull/1499
This PR is part of https://github.com/census-instrumentation/opencensus-java/issues/1483

Stats/Stackdriver: export data using metrics API

---

buildscripts/import-control.xml
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java

Stats/Prometheus: export data using metrics API

---

exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

Chatted with @rghetia today, I found that in the Stackdriver Trace Exporter we never set the `SameProcessAsParentSpan` field for `Span`s, while this field is already available in cloudtrace.v2 proto: https://github.com/googleapis/google-cloud-java/blob/master/google-api-grpc/proto-google-cloud-trace-v2/src/main/proto/google/devtools/cloudtrace/v2/trace.proto#L232.
I'm not sure if this is intentional or we just forgot to set it.

Exporter/Trace/Stackdriver: Set SameProcessAsParentSpan.

---

examples/build.gradle
examples/pom.xml

Otherwise there will be Guava version conflict when running the examples (https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/stats/stackdriver#why-did-i-get-an-error-javalangnosuchmethoderror-comgooglecommon-like-javalangnosuchmethoderrorcomgooglecommonbasethrowablesthrowifinstanceof).

Example: Update dependency versions.

---

CHANGELOG.md
contrib/log_correlation/log4j2/README.md
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/AbstractOpenCensusLog4jLogCorrelationTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusLog4jLogCorrelationAllSpansTest.java
contrib/log_correlation/log4j2/src/test/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjectorTest.java

This commit updates the context key names to match the shorter names in
https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/LogCorrelation.md.
It also removes the warning about the library being experimental.

Update opencensus-contrib-log-correlation-log4j2 to match log correlation spec.

---

contrib/log_correlation/stackdriver/README.md
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

This feature wasn't included in the initial log correlation spec
(https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/LogCorrelation.md),
but we can add it back later if necessary.

Remove "span selection" feature from opencensus-contrib-log-correlation-stackdriver.

---

contrib/log_correlation/stackdriver/README.md
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

Currently, opencensus-contrib-log-correlation-stackdriver adds the sampling
decision to a LogEntry as a custom label.  Once google-cloud-logging adds a
sampling decision field to its LogEntry class, we can set that field instead, so
that the value will be intepreted by Stackdriver.  However, removing the custom
label will be a breaking change.  This commit temporarily removes the custom
label so that we can make a non-experimental release of
opencensus-contrib-log-correlation-stackdriver and add the sampling decision to
the LogEntry later as a backwards-compatible change.

Temporarily remove "traceSampled" label from Stackdriver log correlation.

---

CHANGELOG.md
contrib/log_correlation/stackdriver/README.md
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java

opencensus-contrib-log-correlation-stackdriver is consistent with the log
correlation spec, so it no longer needs to be labeled experimental.
___________________________________________________________________________
This PR depends on #1532.

Remove warning about Stackdriver log correlation being experimental.

---

contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

opencensus-contrib-log-correlation-stackdriver is still experimental, so this is
a good time to improve the API.

Replace OpenCensusTraceLoggingEnhancer(String) constructor with factory method.

---

contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

Code that creates or uses OpenCensusTraceLoggingEnhancer probably won't know its
type, so it will only call the no-arg constructor and 'enhanceLogEntry'.  This
commit hides the other methods in the class, create(String) and getProjectId().
They can be re-exposed in the future if necessary.

Hide methods in OpenCensusTraceLoggingEnhancer that aren't necessary currently.

---

contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/OpenCensusTraceContextDataInjector.java
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/log_correlation/stackdriver/src/test/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancerTest.java

0.17 is the first non-experimental release, and it has some breaking changes, so
so we should reset the "since" tags to 0.17.
_______________________________________________________________
This PR includes #1538.

 Update Javadoc "since" tags in log correlation libraries.

---

checker-framework/stubs/google-cloud-java.astub
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java

This commit stores null instead of an empty string when the project ID can't be
found, which allows distinguishing between null and empty project IDs.
This commit also improves null safety by adding a Nullable annotation to
com.google.cloud.ServiceOptions.getDefaultProjectId(), which can return null
when no project ID is available.  I had to suppress three warnings and add TODOs
where the result was already assumed to be non-null.
_____________________________________________________________________________
I'm planning to open an issue to fix the TODOs after this PR is merged.

Improve handling of null project ID in Stackdriver log correlation.

---

api/src/main/java/io/opencensus/trace/BigendianEncoding.java
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/test/java/io/opencensus/trace/BigendianEncodingTest.java

In a followup PR the LowerCaseBase16Encoding should be changed to work with longs to avoid more allocations (not doing that here to keep this PR simple).

Avoid one extra allocation in TraceId and SpanId.

---

exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java

Looks like https://github.com/census-instrumentation/opencensus-java/pull/1482 broke the build. Fix the `@Nullable` annotation.

Exporter/Jaeger: Fix an annotation.

---

build.gradle

OC-Agent exporter depends on grpc-core which depends on errorprone annotations, and it doesn't work with checker framework.

Build: Exclude oc-agent-exporter from nullness checker.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceConfigRpcHandler.java

Exporter/OcAgent: Add config RPC handler.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

Equivalent to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stats.go#L80-L81.
See also https://github.com/googleapis/gax-java/blob/a60bd347b69fbf725b0dd8ae18bbcf5b00b66b7b/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcHeaderInterceptor.java#L63-L67.

Exporter/Stats/Stackdriver: Add user agent as client header. 

---

api/src/main/java/io/opencensus/trace/BigendianEncoding.java
api/src/main/java/io/opencensus/trace/SpanId.java
api/src/main/java/io/opencensus/trace/TraceId.java
api/src/main/java/io/opencensus/trace/TraceOptions.java
api/src/test/java/io/opencensus/trace/BigendianEncodingTest.java
api/src/test/java/io/opencensus/trace/SpanIdTest.java
api/src/test/java/io/opencensus/trace/TraceIdTest.java
api/src/test/java/io/opencensus/trace/TraceOptionsTest.java

Split from https://github.com/census-instrumentation/opencensus-java/pull/1401 to simplify the review process.
Also improves the toLowerBase16 by avoiding one extra allocation of the StringBuilder.

Add helper functions for base16 encoding.

---

exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java

Tests are flaky on kokoro macos.
> Task :opencensus-exporter-trace-jaeger:test
io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest > exportToJaeger FAILED
java.lang.AssertionError: Not true that <0> is equal to <1>
at io.opencensus.exporter.trace.jaeger.JaegerExporterHandlerIntegrationTest.exportToJaeger(JaegerExporterHandlerIntegrationTest.java:146)
Caused by:
java.lang.AssertionError: Not true that <0> is equal to <1>
at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:28)
at com.google.common.truth.FailureStrategy.fail(FailureStrategy.java:22)
at com.google.common.truth.Subject.failComparingToStrings(Subject.java:335)
at com.google.common.truth.Subject.doEqualCheck(Subject.java:127)
at com.google.common.truth.Subject.isEqualTo(Subject.java:104)
... …

Fix jaeger integration tests.

---

CHANGELOG.md
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java

~~Blocked waiting on https://github.com/census-instrumentation/opencensus-specs/pull/206.~~
The new views won't be included in the default view set and need to be registered separately.

gRPC metrics: Add measures and views for real-time metrics in streaming RPCs.

---

contrib/dropwizard/src/main/java/io/opencensus/contrib/dropwizard/DropWizardMetrics.java
contrib/dropwizard/src/test/java/io/opencensus/contrib/dropwizard/DropWizardMetricsTest.java

startTimestamp: Must be non-null for cumulative points.

Fix bug: Dropwizard Meter should have non-null start Timestamp

---

examples/WORKSPACE

> The native git_repository rule is deprecated. load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository") for a replacement.
See https://travis-ci.org/census-instrumentation/opencensus-java/jobs/462666269#L567.

Example: Fix Bazel Build.

---

exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsServiceExportRpcHandler.java
exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/FakeOcAgentMetricsServiceGrpcImpl.java
exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsServiceExportRpcHandlerTest.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1627.~~
Updates https://github.com/census-instrumentation/opencensus-java/issues/1567.
Similar RPC handler to https://github.com/census-instrumentation/opencensus-java/pull/1570.

 Exporter/Metrics/OcAgent: Add export RPC handler and tests.

---

exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/MetricsProtoUtils.java
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/MetricsProtoUtilsTests.java

~~Blocked by https://github.com/census-instrumentation/opencensus-java/pull/1627.~~
Updates https://github.com/census-instrumentation/opencensus-java/issues/1567.
Metrics APIs and Metrics protos are one-to-one mapping.

Exporter/Metrics/OcAgent: Add MetricsProtoUtils.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceServiceConnectionWorker.java

Split from https://github.com/census-instrumentation/opencensus-java/pull/1492.
Updates https://github.com/census-instrumentation/opencensus-java/issues/1408.

Exporter/OcAgent: Skeleton and workflow for worker thread.

---

CHANGELOG.md
build.gradle
buildscripts/import-control.xml
exporters/trace/datadog/README.md
exporters/trace/datadog/build.gradle
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogSpan.java
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceConfiguration.java
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceExporter.java
exporters/trace/datadog/src/test/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandlerTest.java
settings.gradle

Similar to the Instana exporter, this sends to an API that is intended to be run locally through the Datadog agent. The agent handles batching, authentication, sampling, and so on before communicating with the Datadog servers. 
AFAIK, the expected span format matches up pretty closely with OpenCensus's format. There are some fields with extra meaning which would otherwise just be attributes, which I've tried to map appropriately.

Add trace exporter for Datadog.

---

contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpClientHandler.java
contrib/http_util/src/main/java/io/opencensus/contrib/http/HttpServerHandler.java

Changing `HttpServerHandler` to follow [HTTP Stats](https://github.com/census-instrumentation/opencensus-specs/blob/master/stats/HTTP.md) such that the `http_server_status` will contain the http status code - not the OpenCensus canonical status.
See issue #1654

http_server_status tag should hold http status code

---

contrib/http_jaxrs/README.md
contrib/http_jaxrs/build.gradle
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/ExtendedContainerRequest.java
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsClientExtractor.java
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilter.java
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerExtractor.java
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilter.java
contrib/http_jaxrs/src/main/java/io/opencensus/contrib/http/jaxrs/Metrics.java
contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientExtractorTest.java
contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsClientFilterTest.java
contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerExtractorTest.java
contrib/http_jaxrs/src/test/java/io/opencensus/contrib/http/jaxrs/JaxrsContainerFilterTest.java
settings.gradle

Adding module to provide a JAX-RS container and client filter utilizing the existing http utilities to provide instrumentation for REST services developed using any JAX-RS stack (e.g., RESTeasy or Jersey).

Adding support for JAX-RS client and server

---

.travis.yml

Avoid blocking other PRs while fixing bazel (https://github.com/census-instrumentation/opencensus-java/pull/1697).

CI: Temporarily disable example bazel build.

---

examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldClient.java
examples/src/main/java/io/opencensus/examples/grpc/helloworld/HelloWorldServer.java

The recommended export interval from Stackdriver Monitoring is >= 60s now. If exporting too fast we may get error like "one or more timeseries cannot be written...".

Example: Don't export to Stackdriver too frequent.

---

build.gradle

(cherry picked from commit 1224f0ab8dc2e064d10cefb4e1ec0726d92089b9)

enable javadoc for jetty client. (#1734)

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java

Intentionally split this into 2 commits to make it easy to see the changes, first commit just moves the code of deprecated measures after the new measures, second commit actually does the main change.
This fixes an issue with registerAllGrpcBasicViews because we had 2 measures (rountrip_latency) with different descriptions and this will fail here https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/stats/MeasureToViewMap.java#L115
This is a breaking change in regard to the measure name/description for the old measures, but nobody should depend on that.

 Deprecated measures use instance of new measures when 1to1 mapping.

---

buildscripts/import-control.xml
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandlerProtoTest.java

This PR also changes a bit the name of the resources that we export to stackdriver traces, by simplifying the name: `"g.co/r/" + resourceKey` where the `resourceKey` is the key that we used in our resource definitions.
For AWS:
g.co/r/aws.com/ec2/account_id
g.co/r/aws.com/ec2/instance_id
g.co/r/aws.com/ec2/region
For GCE:
g.co/r/cloud.google.com/gce/project_id
g.co/r/cloud.google.com/gce/instance_id
g.co/r/cloud.google.com/gce/zone
For k8s:
g.co/r/k8s.io/cluster/name
g.co/r/k8s.io/namespace/name
g.co/r/k8s.io/pod/name
g.co/r/k8s.io/container/name

Change Stackdriver trace to use Resource.

---

buildscripts/import-control.xml
contrib/http_jetty_client/src/main/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClient.java
contrib/http_jetty_client/src/test/java/io/opencensus/contrib/http/jetty/client/OcJettyHttpClientTest.java
examples/src/main/java/io/opencensus/examples/http/jetty/client/HelloWorldClient.java

Added options to OcJettyHttpClient constructor address issues/1756 [OcJettyHttpClient doesn't work with HTTPS](https://github.com/census-instrumentation/opencensus-java/issues/1756)

Fix jetty https

---

buildscripts/import-control.xml
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfiguration.java
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterWorker.java
exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfigurationTest.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java

Also make `useInsecure` as the default option. Users need to either use
insecure connection or provide a TLS credential.
Counterpart in Go: https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/45.

Exporter/OcAgent: Support TLS credentials.

---

exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java

Export Handler is called every 5 seconds in a different thread (where [SpanExporter](https://github.com/census-instrumentation/opencensus-java/blob/master/impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java) is running).
- If no connection is established with Agent, try to reconnect every time when a new batch of spans comes.
- If connection is already established, use the connected `exportRpcHandler` to send spans.
`Config` is not included in the PR. (It's not yet supported on Agent either.)
Tested locally against the [FakeOcAgentTraceServiceGrpcImpl](https://github.com/census-instrumentation/opencensus-java/blob/master/exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java) and it worked fine.

Exporter/Trace/OcAgent: Refactor Export RPC.

---

exporters/metrics/ocagent/README.md
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporter.java
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterConfiguration.java
exporters/trace/ocagent/README.md
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java

OcAgent Exporters are not included in the last release. Update to 0.20.
Split from #1761.

Exporter/OcAgent: Update all since tags.

---

exporters/trace/ocagent/build.gradle
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/FakeOcAgentTraceServiceGrpcImpl.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterIntegrationTest.java

Updates https://github.com/census-instrumentation/opencensus-java/issues/1408.
As a follow-up of https://github.com/census-instrumentation/opencensus-java/pull/1773.

Exporter/Trace/OcAgent: Add integration test.

---

contrib/http_servlet/src/main/java/io/opencensus/contrib/http/servlet/OcHttpServletFilter.java
contrib/http_servlet/src/test/java/io/opencensus/contrib/http/servlet/OcHttpServletFilterTest.java

To enable application developers to set the value of publicEndpoint more easily, changed from a servlet context attribute to an init parameter.

Changed Public endpoint publicEndpoint from an attribute to init parameter

---

build.gradle
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedDoubleGaugeImpl.java
impl_core/src/main/java/io/opencensus/implcore/metrics/DerivedLongGaugeImpl.java

This commit also fixes some new warnings by removing raw types and uncommenting
some Nullable annotations that didn't need to be commented.

Checker Framework: 2.6.0 -> 2.7.0

---

api/src/main/java/io/opencensus/stats/AggregationData.java

Upgrading to Checker Framework 2.7.0 in #1792 seemed to fix issue #1782, so this
commit removes the unnecessary package qualification.
Fixes #1782.

Remove package qualification from Immutable annotations.

---

buildscripts/import-control.xml
exporters/stats/stackdriver/build.gradle
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporter.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporterTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

~~Depending on https://github.com/census-instrumentation/opencensus-java/pull/1770.~~
Stackdriver Monitoring has added support for `Exemplar` in the latest client libraries. Modify our Stackdriver Stats exporter to support it. 
~~Note that for now Stackdriver Monitoring backend only accepts string attachments. If we were to send other attachments (e.g `type.googleapis.com/google.devtools.cloudtrace.v1.Trace`), Stackdriver would return an error response saying that type is not supported.~~

Exporter/Stats/Stackdriver: Support Exemplar.

---

examples/build.gradle

When running the examples with gRPC 1.18.0, I got:
```bash
io.grpc.internal.ManagedChannelImpl$1 uncaughtException
SEVERE: [Channel<49>: (localhost:55678)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoSuchMethodError: io.grpc.internal.ClientTransportFactory$ClientTransportOptions.getProxyParameters()Lio/grpc/internal/ProxyParameters;
at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.newClientTransport(NettyChannelBuilder.java:547)
...
```
Upgrading to 1.19.0 fixed this.

Examples: Update gRPC version.

---

benchmarks/src/jmh/java/io/opencensus/benchmarks/stats/RecordBatchedBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/stats/RecordDifferentTagValuesBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/stats/RecordMultipleViewsBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/stats/StatsBenchmarksUtil.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/tags/NestedTagContextCreationBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/tags/TagContextBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/tags/TagsBenchmark.java
benchmarks/src/jmh/java/io/opencensus/benchmarks/tags/TagsBenchmarksUtil.java

Adds microbenchmarks for OpenCensus Stats.

Stats Benchmarks

---

CHANGELOG.md
exporters/stats/stackdriver/README.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporter.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporterTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateTimeSeriesExporterTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1844.
Equivalent to https://github.com/census-instrumentation/opencensus-python/pull/622 in Python and https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/20 in Go.

Exporter/Stackdriver: Allow to override the opencensus_task label.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfiguration.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceExporter.java
exporters/trace/stackdriver/src/main/java/io/opencensus/exporter/trace/stackdriver/StackdriverV2ExporterHandler.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java

Also require a few configurations to be non-null.
Related to https://github.com/census-instrumentation/opencensus-java/issues/1547. /cc @sebright

Exporter/Stackdriver: Fail fast on invalid project ID.

---

examples/src/main/java/io/opencensus/examples/http/jetty/client/HelloWorldClient.java
examples/src/main/java/io/opencensus/examples/http/jetty/server/HelloWorldServer.java

- use client api that supports ssl context.
- use default value for publicEndpoint on server.
- Add comment on how to use B3 format on both sides, client and server.

 update jetty client and server example to use updated api.

---

CHANGELOG.md
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtils.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollector.java
exporters/stats/prometheus/src/main/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsConfiguration.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusExportUtilsTest.java
exporters/stats/prometheus/src/test/java/io/opencensus/exporter/stats/prometheus/PrometheusStatsCollectorTest.java

Reported offline by @paivagustavo.

Exporter/Prometheus: Allow to set custom namespace.

---

CHANGELOG.md
api/src/main/java/io/opencensus/metrics/DerivedDoubleCumulative.java
api/src/main/java/io/opencensus/metrics/DerivedLongCumulative.java
api/src/main/java/io/opencensus/metrics/DoubleCumulative.java
api/src/main/java/io/opencensus/metrics/LongCumulative.java
api/src/main/java/io/opencensus/metrics/MetricRegistry.java
api/src/test/java/io/opencensus/metrics/DerivedDoubleCumulativeTest.java
api/src/test/java/io/opencensus/metrics/DerivedLongCumulativeTest.java
api/src/test/java/io/opencensus/metrics/DoubleCumulativeTest.java
api/src/test/java/io/opencensus/metrics/LongCumulativeTest.java
api/src/test/java/io/opencensus/metrics/MetricRegistryTest.java
impl_core/src/main/java/io/opencensus/implcore/metrics/MetricRegistryImpl.java

Updates https://github.com/census-instrumentation/opencensus-java/issues/1815.
Although the Spec PR (https://github.com/census-instrumentation/opencensus-specs/pull/254) hasn't been submitted, Cumulative APIs have already been added to Go and Node. This PR adds the Cumulative APIs in Java similar to Go (https://github.com/census-instrumentation/opencensus-go/pull/1090).
Most are a copy-and-paste from Gauge APIs since they are very similar.

Metrics: Add Cumulative APIs.

---

CHANGELOG.md
api/src/main/java/io/opencensus/tags/TagContextBuilder.java
impl_core/src/test/java/io/opencensus/implcore/tags/TagMapImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1849.
Add a convenient API so that users don't need to put a tag metadata over and over again when putting tags.

Tags: Add TagContextBuilder.putLocal().

---

CHANGELOG.md
api/src/main/java/io/opencensus/tags/TagContextBuilder.java
impl_core/src/test/java/io/opencensus/implcore/tags/TagMapImplTest.java

Follow up of https://github.com/census-instrumentation/opencensus-java/pull/1851.
Another convenient API that allows adding propagating tags without the need to always put a tag metadata.

Tags: Add TagContextBuilder.putPropagating().

---

api/src/main/java/io/opencensus/metrics/DoubleCumulative.java
api/src/main/java/io/opencensus/metrics/LongCumulative.java

Discussion is https://github.com/bogdandrutu/openconsensus/pull/168#discussion_r277065945. We cannot find a good use case for `Cumulative.Set`. Users should use DerivedCumulative instead.

Metrics: Remove Set from Cumulative.

---

impl_core/src/main/java/io/opencensus/implcore/stats/RecordUtils.java
impl_core/src/test/java/io/opencensus/implcore/stats/RecordUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java

gRPC may migrate to use the new RPC tags (e.g "grpc_client_method") in https://github.com/grpc/grpc-java/pull/5601 and stop recording against the deprecated tags (e.g "method"). However probably there're users who still use the deprecated RPC constants. To avoid breaking their metrics, we need to do some mappings when recording stats against the new tags.
Note the deprecated RPC measures are already mapped to the new ones in https://github.com/census-instrumentation/opencensus-java/pull/1738.
Updates https://github.com/census-instrumentation/opencensus-java/issues/1764.

Stats: Map deprecated RPC tags when record against new tags.

---

contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/GcpMetadataConfig.java

When running Istio on Google Kubernetes Enginge (GKE), the Envoy sidecar
proxy will fail to route any requests made to the metadata server via
the `metadata` hostname (requests will 404). Requests made to the fully
qualified `metadata.google.internal` hostname can be routed.
Update the constant for the metadata host in `GcpMetadataConfig` to use
the FQDN.

Update static GCP metadata URL

---

exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java

Not all test hosts have a default GCP project ID set up. These tests used to crash on such hosts. This PR fixes it.

Exporter/Stackdriver: Fix a few flaky tests.

---

CHANGELOG.md
api/src/main/java/io/opencensus/tags/unsafe/ContextUtils.java
api/src/main/java/io/opencensus/trace/CurrentSpanUtils.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
api/src/test/java/io/opencensus/trace/CurrentSpanUtilsTest.java
api/src/test/java/io/opencensus/trace/unsafe/ContextUtilsTest.java
contrib/log_correlation/log4j2/src/main/java/io/opencensus/contrib/logcorrelation/log4j2/ContextDataUtils.java
contrib/log_correlation/stackdriver/src/main/java/io/opencensus/contrib/logcorrelation/stackdriver/OpenCensusTraceLoggingEnhancer.java
contrib/spring_sleuth_v1x/src/main/java/io/opencensus/contrib/spring/sleuth/v1x/OpenCensusSleuthSpanContextHolder.java
impl_core/src/main/java/io/opencensus/implcore/stats/MeasureMapImpl.java
impl_core/src/main/java/io/opencensus/implcore/tags/CurrentTagMapUtils.java
impl_core/src/test/java/io/opencensus/implcore/stats/StatsRecorderImplTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/CurrentTagMapUtilsTest.java
impl_core/src/test/java/io/opencensus/implcore/tags/TaggerImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1863.
Similar to https://github.com/bogdandrutu/openconsensus/pull/211.
/cc @zhangkun83

Restrict access to context key, add helper methods to interact with Context.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporterTest.java
exporters/trace/stackdriver/src/test/java/io/opencensus/exporter/trace/stackdriver/StackdriverTraceConfigurationTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1841.
Previously metric names like "my.org/metric" are treated as Stackdriver built-in metrics by accident. This PR fixes this bug.

Exporter/Stackdriver: Do create metric descriptor for custom metrics.

---

contrib/zpages/src/main/java/io/opencensus/contrib/zpages/ZPageHandlers.java

A follow-up of https://github.com/census-instrumentation/opencensus-java/issues/1813#issuecomment-489685886.
Enable RunningSpanStore only when /tracez is in use, instead of always enabling it statically.

zPages: Enable RunningSpanStore only when /tracez is in use.

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

Stackdriver Monitoring part of #1880.

Exporter/Stats/Stackdriver: Provide Deadline option and don't do retry by default.

---

CHANGELOG.md
exporters/trace/jaeger/build.gradle
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterConfiguration.java
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerTraceExporter.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterConfigurationTest.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java

Jaeger part of https://github.com/census-instrumentation/opencensus-java/issues/1880.

Exporter/Jaeger: Use configurations and add deadline.

---

CHANGELOG.md
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceConfiguration.java
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogTraceExporter.java
exporters/trace/datadog/src/test/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandlerTest.java
exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceConfiguration.java
exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceHandler.java

Another two of https://github.com/census-instrumentation/opencensus-java/issues/1880.
I'm consider adding a common `SpanExportWithDeadline` interface to reduce the duplicated codes, similar to https://github.com/census-instrumentation/opencensus-java/tree/master/exporters/metrics/util. WDYT?

Exporter/Datadog, Elasticsearch: Add deadline option.

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtils.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverExportUtilsTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1888.
According to https://cloud.google.com/monitoring/api/resources#tag_k8s_container:
> k8s_container
Display name: Kubernetes Container
Description: A Kubernetes container instance.
Labels:
project_id: The identifier of the GCP project associated with this resource, such as "my-project".
location: The physical location of the cluster that contains the container.
cluster_name: The name of the cluster that the container is running in.
namespace_name: The name of the namespace that the container is running in.
pod_name: The name of the pod that the container is running in.
container_name: The name of the container.
`k8s_container` resource doesn't have an `instance_id` label.

Exporter/Stackdriver: Fix k8s_container resource.

---

buildscripts/import-control.xml
exporters/trace/datadog/build.gradle
exporters/trace/datadog/src/main/java/io/opencensus/exporter/trace/datadog/DatadogExporterHandler.java
exporters/trace/elasticsearch/build.gradle
exporters/trace/elasticsearch/src/main/java/io/opencensus/exporter/trace/elasticsearch/ElasticsearchTraceHandler.java
exporters/trace/instana/build.gradle
exporters/trace/jaeger/build.gradle
exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
exporters/trace/util/src/main/java/io/opencensus/exporter/trace/util/TimeLimitedHandler.java
exporters/trace/zipkin/build.gradle
exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java

Updates #1880.
The goal of this change is to reduce the code duplication added in recent exporter PRs (e.g #1884 #1885 #1886), as a follow up of #1887.

Exporter/Trace: Refactor to use TimeLimitedHandler.

---

CHANGELOG.md
exporters/trace/instana/build.gradle
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterConfiguration.java
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaExporterHandler.java
exporters/trace/instana/src/main/java/io/opencensus/exporter/trace/instana/InstanaTraceExporter.java

Exporter/Instana: Use configurations and add deadline option.

---

exporters/metrics/ocagent/src/test/java/io/opencensus/exporter/metrics/ocagent/OcAgentMetricsExporterIntegrationTest.java
impl_core/src/main/java/io/opencensus/implcore/trace/export/SpanExporterImpl.java
impl_core/src/test/java/io/opencensus/implcore/trace/export/SpanExporterImplTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1767

Start dropping spans when the span exporter thread holds more than 10K spans references.

---

CHANGELOG.md
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporter.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfiguration.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterHandler.java
exporters/trace/ocagent/src/test/java/io/opencensus/exporter/trace/ocagent/OcAgentTraceExporterConfigurationTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1880.

Exporter/OcAgent: Add deadline option.

---

examples/build.gradle
exporters/metrics/ocagent/README.md
exporters/trace/ocagent/README.md

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1897.

Exporter/OcAgent: Add a note about netty-tcnative-boringssl dependency.

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporterTest.java

Fixes https://github.com/census-instrumentation/opencensus-java/issues/1917.

Exporter/Stackdriver: Expose unregister API.

---

contrib/spring/src/main/java/io/opencensus/contrib/spring/autoconfig/OpenCensusProperties.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/autoconfig/TraceWebAsyncClientAutoConfiguration.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/instrument/web/HttpServletFilter.java
contrib/spring/src/main/java/io/opencensus/contrib/spring/instrument/web/client/TracingAsyncClientHttpRequestInterceptor.java

Provide an api to configure propagation for spring servlet and client

---

exporters/trace/jaeger/src/main/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandler.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerIntegrationTest.java
exporters/trace/jaeger/src/test/java/io/opencensus/exporter/trace/jaeger/JaegerExporterHandlerTest.java

Fixes #1927.
Tags conversion matches Go Jaeger exporter: 
https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/blob/e8b55949d948652e47aae4378212f933ecee856b/jaeger.go#L210-L219

Exporter/Jaeger: Set span status as tags.

---

exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java
exporters/trace/zipkin/src/test/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandlerTest.java

Suggested by https://github.com/census-instrumentation/opencensus-java/pull/1928#issuecomment-500671005. Seems this is the convention from OpenTracing.

Exporter/Zipkin: Add a note about status tags.

---

CHANGELOG.md
api/src/main/java/io/opencensus/tags/unsafe/ContextUtils.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
build.gradle
examples/build.gradle
examples/pom.xml

Users are discouraged from accessing these keys directly, instead they should use the `getValue`/`withValue` APIs. gRPC is also migrated.

Context: Remove CONTEXT_SPAN_KEY and TAG_CONTEXT_KEY from API.

---

contrib/resource_util/src/main/java/io/opencensus/contrib/resource/util/K8sResource.java
contrib/resource_util/src/test/java/io/opencensus/contrib/resource/util/K8sResourceTest.java

Followed https://github.com/census-instrumentation/opencensus-specs/pull/267, https://github.com/census-instrumentation/opencensus-go/pull/1148 and https://github.com/census-ecosystem/kubernetes-operator/pull/13.

Resource: Add deployment label for k8s resource.

---

exporters/trace/zipkin/README.md

The group id of the Zipkin Server maven artifact has changed in recent versions, so the previous instructions would not download the latest version of the server. The quickstart script provided by Zipkin is the recommended way to download the Zipkin Server jar and will download the latest version.

Use Zipkin quickstart script in download instructions

---

exporters/trace/zipkin/src/main/java/io/opencensus/exporter/trace/zipkin/ZipkinExporterHandler.java

The previous Zipkin values used to be plain `census` but those changed to be
`opencensus`.
This change was proposed in census-instrumentation/opencensus-go#242
Closes #904

Set Zipkin status values to OpenCensus.

---

build.gradle
contrib/appengine_standard_util/build.gradle

deps: update protobuf

---

exporters/trace/instana/src/test/java/io/opencensus/exporter/trace/instana/InstanaExporterHandlerTest.java

Four tests for `InstanaExporterHandler`. These hit four previously uncovered branches in `convertToJson()`, namely the `if` statements that check for:
- null status
- Error status
- Multiple spans in a collection
- Multiple attributes in a span

Add more InstanaExporterHandler tests

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfiguration.java
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporterTest.java
exporters/stats/stackdriver/src/test/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsConfigurationTest.java

Allow users to specify a metric display name prefix, separately from the metric name prefix

feat: Allow users to specify a metric display name prefix

---

buildscripts/checkstyle.xml
impl_core/src/main/java/io/opencensus/implcore/trace/RecordEventsSpanImpl.java

Fixes #2045
This will reduce GC pressure since the VM will not call
Finalizer.register() when creating Span objects.
Since this method is synchronized on a static lock
it can be a source of contention.
It also avoids contention on the same lock when running
runFinalizer() as part of GC

Remove finalize from RecordEventsSpanImpl

---

impl_core/src/main/java/io/opencensus/implcore/trace/TracerImpl.java

Missed this in the previous PR to support OpenCensus to OpenTelemetry migration library 😞

Make TracerImpl constructor public

---

impl_core/src/main/java/io/opencensus/implcore/stats/MutableViewData.java
impl_core/src/test/java/io/opencensus/implcore/stats/MutableViewDataTest.java

For now, we fix all known issues with time skew in Metric Views.
- In the event of a detected time skew, we just throw away all our data.  We really don't know if it's safe to push anything we have, and we cannot safely do any aggregation / report correct timestamps.
- We add (the first?) tests for `MutableViewData` to ensure it does not throw when time rewinds, but instead drops recorded data points and resets itself.
Fixes #2068 (deemed to not have a workaround)

Fix time skew exceptions crashing disruptor thread

---

api/src/main/java/io/opencensus/trace/unsafe/ContextHandleUtils.java
api/src/main/java/io/opencensus/trace/unsafe/ContextManagerImpl.java
api/src/main/java/io/opencensus/trace/unsafe/ContextUtils.java
api/src/test/java/io/opencensus/trace/unsafe/ContextUtilsTest.java

Fixes #2069  - bincompat issues with 0.18.0->0.18.1

Mark ContextUtils as public (but deprecated) 

---

api/src/main/java/io/opencensus/common/OpenCensusLibraryInformation.java
build.gradle
examples/build.gradle
examples/pom.xml
examples/spring/servlet/build.gradle
exporters/metrics/ocagent/src/main/java/io/opencensus/exporter/metrics/ocagent/OcAgentNodeUtils.java
exporters/trace/ocagent/src/main/java/io/opencensus/exporter/trace/ocagent/OcAgentNodeUtils.java

- Bump major version to 0.28.4
- Allow GPG agent for publishing (leaked into the release)
- Include the commit with the 0.28.3 tag.

Updates for 0.28.3 release

---

.github/workflows/build-checker.yml
.github/workflows/build-gradle-examples.yml
.github/workflows/build-maven-examples.yml
.github/workflows/build.yml

- Migrate our existing travis CI workflow to github actions.
- ONLY runs Java8 build (no Java9/Java10 etc.)   Java 11 build is not working right now
- This is a precursor to getting some of the security fixes in.

Add github action PR build

---

api/src/test/java/io/opencensus/trace/LinkTest.java

LinkTest has recently been having flaky failures. It turns out that the `link_ToString()` test relied on hash ordering. The failing assertion only passed when a copy of the `HashMap` had the same `toString()` as the original map. If copying the map changed the iteration order, the test would fail.
This entire test function is questionable, however, as it is testing the `toString()` method on an `AutoValue`. This is problematic, because `AutoValue` specifies its `toString()` as "returning a useful (but unspecified) string representation of the instance" (see https://github.com/google/auto/blob/master/value/userguide/index.md#whats-going-on-here). As such, it could make sense to remove this test altogether. This change does not remove the test, because it's operating under the assumption …

Fix flaky LinkTest

---

build.gradle
contrib/log_correlation/log4j2/build.gradle

* Use the more recent 2.15.0 as baseline
* For the published package, express a provided dependency
rather than actually pulling in Log4J2 ourselves

Update and weaken Log4J2 dependency

---

CHANGELOG.md
exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java

Using the default configuration of `StackdriverStatsConfiguration`, a `MetricServiceClient` is initialized by the `StackdriverStatsExporter`.
This client was never closed, this will be done now when the `StackdriverStatsExporter.unregister()` method is called.
If a custom `MetricServiceStub` is given by the user, it will *not* be closed as the user should be in charge of it.
This should fix #2007.

fix: Shutdown Stackdriver MetricServiceClient properly

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java
contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViews.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewConstantsTest.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcViewsTest.java

Based on my [conversation](https://gitter.im/grpc/grpc?at=61a4e26bc2cc0e5343d657d8) with the grpc-java core team, the retry stats implementation of grpc-java is complete but lacks opencensus views. This PR adds them according to the measures and views outlined in the [A45-retry-stats](https://github.com/grpc/proposal/blob/master/A45-retry-stats.md#metrics-to-expose) proposal.
Some open questions:
- ~Given that `maxAttempts` maxes out at 5 in [A6-client-retries](https://github.com/grpc/proposal/blob/master/A6-client-retries.md#validation-of-retrypolicy) should we specify a tighter set of buckets for the views (possibly [0, 5]) that use a distribution aggregation~ (resolved)
- Do we need hourly and minute views for these stats? I can add them but I've left them off for now
- I followed the …

implement gRPC client retry stats measures and views

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java
contrib/grpc_metrics/src/test/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstantsTest.java

- fixes the retry stat measure to match those in grpc-java exactly as defined in [CensusStatsModule](https://github.com/grpc/grpc-java/blob/v1.44.0/census/src/main/java/io/grpc/census/CensusStatsModule.java#L401-L409)
- it wasn't obvious to me that the description field for a measure has a meaningful purpose beyond describing the measure and because they didn't match what was in grpc-java #2084 did not have the intended effect
- corrects type of `GRPC_CLIENT_RETRY_DELAY_PER_CALL` from `MeasureLong` to `MeasureDouble` 
In the medium term grpc-java should reference the retry stat `Measure`s defined in opencensus-java instead of creating its own, although these are referenced in a file called [DeprecatedCensusConstants.java](https://github.com/grpc/grpc-java/blob/v1.44.0/census/src/main/java/ …

Fix retry stat measures to match those in grpc-java exactly

---

contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcMeasureConstants.java

* update descriptions of retry measures to match those in grpc-java exactly
* change GRPC_CLIENT_RETRY_DELAY_PER_CALL from MeasureLong to MeasureDouble

[v0.31.x] Fix retry stat measures to match those in grpc-java exactly (#2097) 

---

exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/CreateMetricDescriptorExporter.java

This allows metric descriptors to be created for metrics in that domain

Stackdriver exporter: add workload.googleapis.com as a supported external domain

---

.github/workflows/build-checker.yml
.github/workflows/build-gradle-examples.yml
.github/workflows/build-maven-examples.yml
.github/workflows/build.yml

18.04 runner is deprecated https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

Upgrade ubuntu runner to latest
